Importing libraries

In [13]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import math
from sklearn.metrics import confusion_matrix, roc_auc_score, mean_squared_error, cohen_kappa_score, matthews_corrcoef
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from sklearn.preprocessing import label_binarize
from imblearn.metrics import geometric_mean_score
from imblearn.over_sampling import SMOTE
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier


Reading dataset

In [14]:
df = pd.read_csv('UCI.csv')
print (df.Result.value_counts())
df.head()

Result
 1    6157
-1    4898
Name: count, dtype: int64


having_IP_Address  URL_Length  Shortining_Service  having_At_Symbol  \
0                 -1           1                   1                 1   
1                  1           1                   1                 1   
2                  1           0                   1                 1   
3                  1           0                   1                 1   
4                  1           0                  -1                 1   

   double_slash_redirecting  Prefix_Suffix  having_Sub_Domain  SSLfinal_State  \
0                        -1             -1                 -1              -1   
1                         1             -1                  0               1   
2                         1             -1                 -1              -1   
3                         1             -1                 -1              -1   
4                         1             -1                  1               1   

   Domain_registeration_length  Favicon  ...  popUpWidnow  Iframe  \
0                           -1        1  ...            1       1   
1                           -1        1  ...            1       1   
2                           -1        1  ...            1       1   
3                            1        1  ...            1       1   
4                           -1        1  ...           -1       1   

   age_of_domain  DNSRecord  web_traffic  Page_Rank  Google_Index  \
0             -1         -1           -1         -1             1   
1             -1         -1            0         -1             1   
2              1         -1            1         -1             1   
3             -1         -1            1         -1             1   
4             -1         -1            0         -1             1   

   Links_pointing_to_page  Statistical_report  Result  
0                       1                  -1      -1  
1                       1                   1      -1  
2                       0                  -1      -1  
3                      -1                   1      -1  
4                       1                   1       1  

[5 rows x 31 columns]

Data pre-processing

In [15]:
Label = LabelEncoder()
df['Result'] = Label.fit_transform(df['Result'])
print (df.Result.value_counts())
df.head()

Result
1    6157
0    4898
Name: count, dtype: int64


having_IP_Address  URL_Length  Shortining_Service  having_At_Symbol  \
0                 -1           1                   1                 1   
1                  1           1                   1                 1   
2                  1           0                   1                 1   
3                  1           0                   1                 1   
4                  1           0                  -1                 1   

   double_slash_redirecting  Prefix_Suffix  having_Sub_Domain  SSLfinal_State  \
0                        -1             -1                 -1              -1   
1                         1             -1                  0               1   
2                         1             -1                 -1              -1   
3                         1             -1                 -1              -1   
4                         1             -1                  1               1   

   Domain_registeration_length  Favicon  ...  popUpWidnow  Iframe  \
0                           -1        1  ...            1       1   
1                           -1        1  ...            1       1   
2                           -1        1  ...            1       1   
3                            1        1  ...            1       1   
4                           -1        1  ...           -1       1   

   age_of_domain  DNSRecord  web_traffic  Page_Rank  Google_Index  \
0             -1         -1           -1         -1             1   
1             -1         -1            0         -1             1   
2              1         -1            1         -1             1   
3             -1         -1            1         -1             1   
4             -1         -1            0         -1             1   

   Links_pointing_to_page  Statistical_report  Result  
0                       1                  -1       0  
1                       1                   1       0  
2                       0                  -1       0  
3                      -1                   1       0  
4                       1                   1       1  

[5 rows x 31 columns]

Data Cleaning

In [16]:
# df = df.replace([np.inf, -np.inf], np.nan)
# df.fillna(0, inplace=True)
# print(df.max())
# print(df.min())
# df.head()

In [17]:
input = df.drop (['Result'], axis='columns')
target = df.Result
print(target.head())
input.head()

0    0
1    0
2    0
3    0
4    1
Name: Result, dtype: int64


having_IP_Address  URL_Length  Shortining_Service  having_At_Symbol  \
0                 -1           1                   1                 1   
1                  1           1                   1                 1   
2                  1           0                   1                 1   
3                  1           0                   1                 1   
4                  1           0                  -1                 1   

   double_slash_redirecting  Prefix_Suffix  having_Sub_Domain  SSLfinal_State  \
0                        -1             -1                 -1              -1   
1                         1             -1                  0               1   
2                         1             -1                 -1              -1   
3                         1             -1                 -1              -1   
4                         1             -1                  1               1   

   Domain_registeration_length  Favicon  ...  RightClick  popUpWidnow  Iframe  \
0                           -1        1  ...           1            1       1   
1                           -1        1  ...           1            1       1   
2                           -1        1  ...           1            1       1   
3                            1        1  ...           1            1       1   
4                           -1        1  ...           1           -1       1   

   age_of_domain  DNSRecord  web_traffic  Page_Rank  Google_Index  \
0             -1         -1           -1         -1             1   
1             -1         -1            0         -1             1   
2              1         -1            1         -1             1   
3             -1         -1            1         -1             1   
4             -1         -1            0         -1             1   

   Links_pointing_to_page  Statistical_report  
0                       1                  -1  
1                       1                   1  
2                       0                  -1  
3                      -1                   1  
4                       1                   1  

[5 rows x 30 columns]

Data splitting

In [18]:
X_train, X_test, y_train, y_test = train_test_split(input, target, test_size=0.2)
print (len (X_test))
print (len (X_train))

2211
8844


In [19]:
y_train.value_counts()

Result
1    4913
0    3931
Name: count, dtype: int64

In [20]:
# smote = SMOTE(random_state=42)
# X_train, y_train = smote.fit_resample(X_train, y_train)
# y_train.value_counts()

In [21]:
def report (y_test, y_pred):
    n_classes = 2
    y_true_binary = label_binarize(y_test, classes=range(n_classes))
    y_pred_binary = label_binarize(y_pred, classes=range(n_classes))
    auc_score = roc_auc_score(y_true_binary, y_pred_binary, average='macro')

    report = classification_report(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    
    mse = mean_squared_error(y_test, y_pred)
    kappa = cohen_kappa_score(y_test, y_pred)
    mcc = matthews_corrcoef(y_test, y_pred)
    g_mean = geometric_mean_score(y_test, y_pred)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='micro')
    recall = recall_score(y_test, y_pred, average='micro')
    f1 = f1_score(y_test, y_pred, average='micro')

    print("Classification Report:\n", report)
    print("Accuracy:", accuracy)
    print("Precision:", precision)
    print("Recall:", recall)
    print("F1-Score:", f1)
    print("AUC Score:", auc_score)
    print("MSE:", mse)
    print("G-Mean", g_mean)
    print("Kappa:", kappa)
    print("MCC:", mcc)
    print("Confusion Matrix:\n", conf_matrix)


Logistic Regression

In [22]:
model = LogisticRegression ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.91      0.92       967
           1       0.93      0.95      0.94      1244

    accuracy                           0.93      2211
   macro avg       0.93      0.93      0.93      2211
weighted avg       0.93      0.93      0.93      2211

Accuracy: 0.9298959746720941
Precision: 0.9298959746720941
Recall: 0.9298959746720941
F1-Score: 0.9298959746720941
AUC Score: 0.9276843221818399
MSE: 0.07010402532790593
G-Mean 0.9275163409221902
Kappa: 0.8572439019208684
MCC: 0.8573751845629586
Confusion Matrix:
 [[ 880   87]
 [  68 1176]]


Decision Tree

In [23]:
model = DecisionTreeClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.94      0.95       967
           1       0.96      0.96      0.96      1244

    accuracy                           0.95      2211
   macro avg       0.95      0.95      0.95      2211
weighted avg       0.95      0.95      0.95      2211

Accuracy: 0.9534147444595206
Precision: 0.9534147444595206
Recall: 0.9534147444595206
F1-Score: 0.9534147444595206
AUC Score: 0.9523840598263599
MSE: 0.046585255540479424
G-Mean 0.95234852652679
Kappa: 0.9052892667157688
MCC: 0.905298834871125
Confusion Matrix:
 [[ 913   54]
 [  49 1195]]


Naive Bayes

In [24]:
model = GaussianNB ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.52      1.00      0.68       967
           1       1.00      0.27      0.43      1244

    accuracy                           0.59      2211
   macro avg       0.76      0.64      0.56      2211
weighted avg       0.79      0.59      0.54      2211

Accuracy: 0.5920398009950248
Precision: 0.5920398009950248
Recall: 0.5920398009950248
F1-Score: 0.5920398009950248
AUC Score: 0.637459807073955
MSE: 0.4079601990049751
G-Mean 0.5243277735805246
Kappa: 0.2490550691894945
MCC: 0.3771476875356637
Confusion Matrix:
 [[967   0]
 [902 342]]


Random Forest

In [25]:
model = RandomForestClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.96      0.96       967
           1       0.97      0.98      0.97      1244

    accuracy                           0.97      2211
   macro avg       0.97      0.97      0.97      2211
weighted avg       0.97      0.97      0.97      2211

Accuracy: 0.968340117593849
Precision: 0.968340117593849
Recall: 0.968340117593849
F1-Score: 0.968340117593849
AUC Score: 0.9669141974549191
MSE: 0.031659882406151064
G-Mean 0.9668472081511098
Kappa: 0.9355518133938298
MCC: 0.9356533385878021
Confusion Matrix:
 [[ 924   43]
 [  27 1217]]


LightBoost

In [26]:
model = LGBMClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

[LightGBM] [Info] Number of positive: 4913, number of negative: 3931
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000844 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 89
[LightGBM] [Info] Number of data points in the train set: 8844, number of used features: 30
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.555518 -> initscore=0.222991
[LightGBM] [Info] Start training from score 0.222991
Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.96      0.96       967
           1       0.97      0.97      0.97      1244

    accuracy                           0.97      2211
   macro avg       0.96      0.96      0.96      2211
weighted avg       0.97      0.97      0.97      2211

Accuracy: 0.9651741293532339
Precision: 0.9651741293532339
Recall: 0.9651741293532339
F1-Score:

CatBoost

In [27]:
model = CatBoostClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Learning rate set to 0.026131
0:	learn: 0.6503509	total: 154ms	remaining: 2m 34s
1:	learn: 0.6070366	total: 172ms	remaining: 1m 25s
2:	learn: 0.5686019	total: 193ms	remaining: 1m 4s
3:	learn: 0.5337101	total: 206ms	remaining: 51.4s
4:	learn: 0.5040325	total: 215ms	remaining: 42.7s
5:	learn: 0.4737876	total: 222ms	remaining: 36.8s
6:	learn: 0.4482424	total: 228ms	remaining: 32.4s
7:	learn: 0.4236776	total: 233ms	remaining: 28.9s
8:	learn: 0.4013360	total: 236ms	remaining: 25.9s
9:	learn: 0.3822166	total: 239ms	remaining: 23.6s
10:	learn: 0.3646077	total: 242ms	remaining: 21.8s
11:	learn: 0.3476154	total: 245ms	remaining: 20.2s
12:	learn: 0.3335495	total: 248ms	remaining: 18.8s
13:	learn: 0.3206872	total: 251ms	remaining: 17.7s
14:	learn: 0.3107724	total: 255ms	remaining: 16.7s
15:	learn: 0.3004659	total: 258ms	remaining: 15.9s
16:	learn: 0.2899363	total: 261ms	remaining: 15.1s
17:	learn: 0.2806191	total: 264ms	remaining: 14.4s
18:	learn: 0.2733736	total: 267ms	remaining: 13.8s
19:	learn

Gradient Boost

In [28]:
model = GradientBoostingClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.93      0.94       967
           1       0.94      0.96      0.95      1244

    accuracy                           0.95      2211
   macro avg       0.95      0.95      0.95      2211
weighted avg       0.95      0.95      0.95      2211

Accuracy: 0.9479873360470376
Precision: 0.9479873360470376
Recall: 0.9479873360470376
F1-Score: 0.9479873360470376
AUC Score: 0.945718767561025
MSE: 0.05201266395296246
G-Mean 0.945545399320231
Kappa: 0.8940108071335585
MCC: 0.8942482139830485
Confusion Matrix:
 [[ 897   70]
 [  45 1199]]


SVM

In [29]:
model = SVC ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.92      0.94       967
           1       0.94      0.96      0.95      1244

    accuracy                           0.95      2211
   macro avg       0.95      0.94      0.94      2211
weighted avg       0.95      0.95      0.95      2211

Accuracy: 0.9457259158751696
Precision: 0.9457259158751696
Recall: 0.9457259158751696
F1-Score: 0.9457259158751696
AUC Score: 0.9432485859737911
MSE: 0.054274084124830396
G-Mean 0.943041296522974
Kappa: 0.889364257299407
MCC: 0.8896607481453599
Confusion Matrix:
 [[ 893   74]
 [  46 1198]]


KNN

In [30]:
X_train = np.array(X_train)
X_test = np.array(X_test)
model = KNeighborsClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.94      0.93      0.94       967
           1       0.95      0.95      0.95      1244

    accuracy                           0.94      2211
   macro avg       0.94      0.94      0.94      2211
weighted avg       0.94      0.94      0.94      2211

Accuracy: 0.9448213478064225
Precision: 0.9448213478064225
Recall: 0.9448213478064225
F1-Score: 0.9448213478064225
AUC Score: 0.9434809318441029
MSE: 0.055178652193577565
G-Mean 0.9434202654797713
Kappa: 0.8877795713239699
MCC: 0.8878036092475077
Confusion Matrix:
 [[ 902   65]
 [  57 1187]]


Deep Learning

In [31]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

ANN

In [32]:
model = Sequential()
model.add(Dense(128, activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(64, activation='relu'))
model.add(Dense(1, activation='sigmoid'))  # Adjust for multiclass

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

y_pred = model.predict (X_test)
y_pred_binary = (y_pred > 0.5).astype(int)
report (y_test, y_pred_binary)



Epoch 1/10


222/222 [==============================] - 2s 2ms/step - loss: 0.2389 - accuracy: 0.9110 - val_loss: 0.1742 - val_accuracy: 0.9276
Epoch 2/10
222/222 [==============================] - 0s 2ms/step - loss: 0.1591 - accuracy: 0.9401 - val_loss: 0.1821 - val_accuracy: 0.9243
Epoch 3/10
222/222 [==============================] - 0s 2ms/step - loss: 0.1425 - accuracy: 0.9411 - val_loss: 0.1384 - val_accuracy: 0.9389
Epoch 4/10
222/222 [==============================] - 0s 2ms/step - loss: 0.1247 - accuracy: 0.9473 - val_loss: 0.1454 - val_accuracy: 0.9361
Epoch 5/10
222/222 [==============================] - 0s 2ms/step - loss: 0.1208 - accuracy: 0.9480 - val_loss: 0.1248 - val_accuracy: 0.9446
Epoch 6/10
222/222 [==============================] - 0s 2ms/step - loss: 0.1111 - accuracy: 0.9534 - val_loss: 0.1384 - val_accuracy: 0.9457
Epoch 7/10
222/222 [==============================] - 0s 2ms/step - loss: 0.1001 - accuracy: 0.9569 - val_loss: 0.1155 - val_accuracy: 0.9536
Ep

C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


CNN

In [33]:
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten

In [34]:
model = Sequential()
model.add(Conv1D(64, kernel_size=3, activation='relu', input_shape=(X_train.shape[1], 1)))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation='sigmoid'))  # Adjust for multiclass

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

y_pred = model.predict (X_test)
y_pred_binary = (y_pred > 0.5).astype(int)
report (y_test, y_pred_binary)


Epoch 1/10
222/222 [==============================] - 2s 4ms/step - loss: 0.2491 - accuracy: 0.8991 - val_loss: 0.1864 - val_accuracy: 0.9282
Epoch 2/10
222/222 [==============================] - 1s 3ms/step - loss: 0.1778 - accuracy: 0.9298 - val_loss: 0.1662 - val_accuracy: 0.9322
Epoch 3/10
222/222 [==============================] - 1s 3ms/step - loss: 0.1669 - accuracy: 0.9346 - val_loss: 0.1612 - val_accuracy: 0.9384
Epoch 4/10
222/222 [==============================] - 1s 3ms/step - loss: 0.1507 - accuracy: 0.9368 - val_loss: 0.1825 - val_accuracy: 0.9265
Epoch 5/10
222/222 [==============================] - 1s 3ms/step - loss: 0.1519 - accuracy: 0.9374 - val_loss: 0.1610 - val_accuracy: 0.9367
Epoch 6/10
222/222 [==============================] - 1s 3ms/step - loss: 0.1406 - accuracy: 0.9392 - val_loss: 0.1543 - val_accuracy: 0.9361
Epoch 7/10
222/222 [==============================] - 1s 3ms/step - loss: 0.1385 - accuracy: 0.9426 - val_loss: 0.1507 - val_accuracy: 0.9395
Epoch

C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


RNN

In [35]:
from tensorflow.keras.layers import SimpleRNN

In [36]:
model = Sequential()
model.add(SimpleRNN(64, activation='relu', input_shape=(X_train.shape[1], 1)))
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation='sigmoid'))  # Adjust for multiclass

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

y_pred = model.predict (X_test)
y_pred_binary = (y_pred > 0.5).astype(int)
report (y_test, y_pred_binary)

Epoch 1/10
222/222 [==============================] - 4s 9ms/step - loss: 0.4965 - accuracy: 0.7493 - val_loss: 0.4010 - val_accuracy: 0.8315
Epoch 2/10
222/222 [==============================] - 1s 6ms/step - loss: 0.3403 - accuracy: 0.8550 - val_loss: 0.3248 - val_accuracy: 0.8457
Epoch 3/10
222/222 [==============================] - 2s 7ms/step - loss: 0.2833 - accuracy: 0.8841 - val_loss: 0.2416 - val_accuracy: 0.9096
Epoch 4/10
222/222 [==============================] - 1s 6ms/step - loss: 0.2228 - accuracy: 0.9090 - val_loss: 0.2436 - val_accuracy: 0.9045
Epoch 5/10
222/222 [==============================] - 1s 7ms/step - loss: 0.2147 - accuracy: 0.9136 - val_loss: 0.2030 - val_accuracy: 0.9152
Epoch 6/10
222/222 [==============================] - 1s 6ms/step - loss: 0.1930 - accuracy: 0.9244 - val_loss: 0.2106 - val_accuracy: 0.9146
Epoch 7/10
222/222 [==============================] - 1s 6ms/step - loss: 0.1918 - accuracy: 0.9204 - val_loss: 0.2296 - val_accuracy: 0.9107
Epoch 

C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


LSTM

In [37]:
from tensorflow.keras.layers import LSTM

In [38]:
model = Sequential()
model.add(LSTM(64, activation='relu', input_shape=(X_train.shape[1], 1)))
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation='sigmoid'))  # Adjust for multiclass

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

y_pred = model.predict (X_test)
y_pred_binary = (y_pred > 0.5).astype(int)
report (y_test, y_pred_binary)

Epoch 1/10
222/222 [==============================] - 6s 15ms/step - loss: 0.6080 - accuracy: 0.6277 - val_loss: 0.7323 - val_accuracy: 0.6145
Epoch 2/10
222/222 [==============================] - 3s 14ms/step - loss: 0.6081 - accuracy: 0.6300 - val_loss: 0.5535 - val_accuracy: 0.6710
Epoch 3/10
222/222 [==============================] - 3s 13ms/step - loss: 0.6702 - accuracy: 0.5993 - val_loss: 0.6490 - val_accuracy: 0.6393
Epoch 4/10
222/222 [==============================] - 3s 13ms/step - loss: 0.5928 - accuracy: 0.6625 - val_loss: 0.5606 - val_accuracy: 0.6778
Epoch 5/10
222/222 [==============================] - 3s 14ms/step - loss: 0.5420 - accuracy: 0.7052 - val_loss: 0.5512 - val_accuracy: 0.7010
Epoch 6/10
222/222 [==============================] - 3s 15ms/step - loss: 0.5271 - accuracy: 0.7169 - val_loss: 0.5192 - val_accuracy: 0.7179
Epoch 7/10
222/222 [==============================] - 3s 13ms/step - loss: 0.5205 - accuracy: 0.7298 - val_loss: 0.5251 - val_accuracy: 0.7213

C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
