Importing libraries

In [17]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import math
from sklearn.metrics import confusion_matrix, roc_auc_score, mean_squared_error, cohen_kappa_score, matthews_corrcoef
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from sklearn.preprocessing import label_binarize
from imblearn.metrics import geometric_mean_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier



Reading dataset

In [18]:
df = pd.read_csv('UCI.csv')
print (df.Result.value_counts())
df.head()

Result
 1    6157
-1    4898
Name: count, dtype: int64


having_IP_Address  URL_Length  Shortining_Service  having_At_Symbol  \
0                 -1           1                   1                 1   
1                  1           1                   1                 1   
2                  1           0                   1                 1   
3                  1           0                   1                 1   
4                  1           0                  -1                 1   

   double_slash_redirecting  Prefix_Suffix  having_Sub_Domain  SSLfinal_State  \
0                        -1             -1                 -1              -1   
1                         1             -1                  0               1   
2                         1             -1                 -1              -1   
3                         1             -1                 -1              -1   
4                         1             -1                  1               1   

   Domain_registeration_length  Favicon  ...  popUpWidnow  Iframe  \
0                           -1        1  ...            1       1   
1                           -1        1  ...            1       1   
2                           -1        1  ...            1       1   
3                            1        1  ...            1       1   
4                           -1        1  ...           -1       1   

   age_of_domain  DNSRecord  web_traffic  Page_Rank  Google_Index  \
0             -1         -1           -1         -1             1   
1             -1         -1            0         -1             1   
2              1         -1            1         -1             1   
3             -1         -1            1         -1             1   
4             -1         -1            0         -1             1   

   Links_pointing_to_page  Statistical_report  Result  
0                       1                  -1      -1  
1                       1                   1      -1  
2                       0                  -1      -1  
3                      -1                   1      -1  
4                       1                   1       1  

[5 rows x 31 columns]

Data pre-processing

In [19]:
Label = LabelEncoder()
df['Result'] = Label.fit_transform(df['Result'])
print (df.Result.value_counts())
df.head()

Result
1    6157
0    4898
Name: count, dtype: int64


having_IP_Address  URL_Length  Shortining_Service  having_At_Symbol  \
0                 -1           1                   1                 1   
1                  1           1                   1                 1   
2                  1           0                   1                 1   
3                  1           0                   1                 1   
4                  1           0                  -1                 1   

   double_slash_redirecting  Prefix_Suffix  having_Sub_Domain  SSLfinal_State  \
0                        -1             -1                 -1              -1   
1                         1             -1                  0               1   
2                         1             -1                 -1              -1   
3                         1             -1                 -1              -1   
4                         1             -1                  1               1   

   Domain_registeration_length  Favicon  ...  popUpWidnow  Iframe  \
0                           -1        1  ...            1       1   
1                           -1        1  ...            1       1   
2                           -1        1  ...            1       1   
3                            1        1  ...            1       1   
4                           -1        1  ...           -1       1   

   age_of_domain  DNSRecord  web_traffic  Page_Rank  Google_Index  \
0             -1         -1           -1         -1             1   
1             -1         -1            0         -1             1   
2              1         -1            1         -1             1   
3             -1         -1            1         -1             1   
4             -1         -1            0         -1             1   

   Links_pointing_to_page  Statistical_report  Result  
0                       1                  -1       0  
1                       1                   1       0  
2                       0                  -1       0  
3                      -1                   1       0  
4                       1                   1       1  

[5 rows x 31 columns]

Data Cleaning

In [20]:
df = df.replace([np.inf, -np.inf], np.nan)
df.fillna(0, inplace=True)
print(df.max())
print(df.min())
df.head()

having_IP_Address              1
URL_Length                     1
Shortining_Service             1
having_At_Symbol               1
double_slash_redirecting       1
Prefix_Suffix                  1
having_Sub_Domain              1
SSLfinal_State                 1
Domain_registeration_length    1
Favicon                        1
port                           1
HTTPS_token                    1
Request_URL                    1
URL_of_Anchor                  1
Links_in_tags                  1
SFH                            1
Submitting_to_email            1
Abnormal_URL                   1
Redirect                       1
on_mouseover                   1
RightClick                     1
popUpWidnow                    1
Iframe                         1
age_of_domain                  1
DNSRecord                      1
web_traffic                    1
Page_Rank                      1
Google_Index                   1
Links_pointing_to_page         1
Statistical_report             1
Result    

having_IP_Address  URL_Length  Shortining_Service  having_At_Symbol  \
0                 -1           1                   1                 1   
1                  1           1                   1                 1   
2                  1           0                   1                 1   
3                  1           0                   1                 1   
4                  1           0                  -1                 1   

   double_slash_redirecting  Prefix_Suffix  having_Sub_Domain  SSLfinal_State  \
0                        -1             -1                 -1              -1   
1                         1             -1                  0               1   
2                         1             -1                 -1              -1   
3                         1             -1                 -1              -1   
4                         1             -1                  1               1   

   Domain_registeration_length  Favicon  ...  popUpWidnow  Iframe  \
0                           -1        1  ...            1       1   
1                           -1        1  ...            1       1   
2                           -1        1  ...            1       1   
3                            1        1  ...            1       1   
4                           -1        1  ...           -1       1   

   age_of_domain  DNSRecord  web_traffic  Page_Rank  Google_Index  \
0             -1         -1           -1         -1             1   
1             -1         -1            0         -1             1   
2              1         -1            1         -1             1   
3             -1         -1            1         -1             1   
4             -1         -1            0         -1             1   

   Links_pointing_to_page  Statistical_report  Result  
0                       1                  -1       0  
1                       1                   1       0  
2                       0                  -1       0  
3                      -1                   1       0  
4                       1                   1       1  

[5 rows x 31 columns]

In [21]:
input = df.drop (['Result'], axis='columns')
target = df.Result
print(target.head())
input.head()

0    0
1    0
2    0
3    0
4    1
Name: Result, dtype: int64


having_IP_Address  URL_Length  Shortining_Service  having_At_Symbol  \
0                 -1           1                   1                 1   
1                  1           1                   1                 1   
2                  1           0                   1                 1   
3                  1           0                   1                 1   
4                  1           0                  -1                 1   

   double_slash_redirecting  Prefix_Suffix  having_Sub_Domain  SSLfinal_State  \
0                        -1             -1                 -1              -1   
1                         1             -1                  0               1   
2                         1             -1                 -1              -1   
3                         1             -1                 -1              -1   
4                         1             -1                  1               1   

   Domain_registeration_length  Favicon  ...  RightClick  popUpWidnow  Iframe  \
0                           -1        1  ...           1            1       1   
1                           -1        1  ...           1            1       1   
2                           -1        1  ...           1            1       1   
3                            1        1  ...           1            1       1   
4                           -1        1  ...           1           -1       1   

   age_of_domain  DNSRecord  web_traffic  Page_Rank  Google_Index  \
0             -1         -1           -1         -1             1   
1             -1         -1            0         -1             1   
2              1         -1            1         -1             1   
3             -1         -1            1         -1             1   
4             -1         -1            0         -1             1   

   Links_pointing_to_page  Statistical_report  
0                       1                  -1  
1                       1                   1  
2                       0                  -1  
3                      -1                   1  
4                       1                   1  

[5 rows x 30 columns]

Data splitting

In [22]:
X_train, X_test, y_train, y_test = train_test_split(input, target, test_size=0.3)
print (len (X_test))
print (len (X_train))

3317
7738


In [23]:
def report (y_test, y_pred):
    n_classes = 2
    y_true_binary = label_binarize(y_test, classes=range(n_classes))
    y_pred_binary = label_binarize(y_pred, classes=range(n_classes))
    auc_score = roc_auc_score(y_true_binary, y_pred_binary, average='macro')

    report = classification_report(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    
    mse = mean_squared_error(y_test, y_pred)
    kappa = cohen_kappa_score(y_test, y_pred)
    mcc = matthews_corrcoef(y_test, y_pred)
    g_mean = geometric_mean_score(y_test, y_pred)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='micro')
    recall = recall_score(y_test, y_pred, average='micro')
    f1 = f1_score(y_test, y_pred, average='micro')

    print("Classification Report:\n", report)
    print("Accuracy:", accuracy)
    print("Precision:", precision)
    print("Recall:", recall)
    print("F1-Score:", f1)
    print("AUC Score:", auc_score)
    print("MSE:", mse)
    print("G-Mean", g_mean)
    print("Kappa:", kappa)
    print("MCC:", mcc)
    print("Confusion Matrix:\n", conf_matrix)


Logistic Regression

In [24]:
model = LogisticRegression ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.94      0.89      0.92      1493
           1       0.92      0.95      0.93      1824

    accuracy                           0.93      3317
   macro avg       0.93      0.92      0.93      3317
weighted avg       0.93      0.93      0.93      3317

Accuracy: 0.9261380765752185
Precision: 0.9261380765752185
Recall: 0.9261380765752185
F1-Score: 0.9261380765752185
AUC Score: 0.9231161722541451
MSE: 0.07386192342478143
G-Mean 0.9226193204041181
Kappa: 0.8501071354990621
MCC: 0.851003495370311
Confusion Matrix:
 [[1333  160]
 [  85 1739]]


Decision Tree

In [25]:
model = DecisionTreeClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.95      0.95      1493
           1       0.96      0.97      0.96      1824

    accuracy                           0.96      3317
   macro avg       0.96      0.96      0.96      3317
weighted avg       0.96      0.96      0.96      3317

Accuracy: 0.9583961410913476
Precision: 0.9583961410913476
Recall: 0.9583961410913476
F1-Score: 0.9583961410913476
AUC Score: 0.9574915027437986
MSE: 0.0416038589086524
G-Mean 0.9574485857047299
Kappa: 0.915873577143731
MCC: 0.9159171467024413
Confusion Matrix:
 [[1416   77]
 [  61 1763]]


Naive Bayes

In [26]:
model = GaussianNB ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.54      1.00      0.70      1493
           1       1.00      0.31      0.47      1824

    accuracy                           0.62      3317
   macro avg       0.77      0.65      0.59      3317
weighted avg       0.79      0.62      0.57      3317

Accuracy: 0.618631293337353
Precision: 0.618631293337353
Recall: 0.618631293337353
F1-Score: 0.618631293337353
AUC Score: 0.6531738757476411
MSE: 0.381368706662647
G-Mean 0.5539060442467163
Kappa: 0.28450970472078085
MCC: 0.40657060939150863
Confusion Matrix:
 [[1492    1]
 [1264  560]]


Random Forest

In [27]:
model = RandomForestClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.94      0.96      1493
           1       0.95      0.99      0.97      1824

    accuracy                           0.97      3317
   macro avg       0.97      0.96      0.97      3317
weighted avg       0.97      0.97      0.97      3317

Accuracy: 0.9656315948145915
Precision: 0.9656315948145915
Recall: 0.9656315948145915
F1-Score: 0.9656315948145915
AUC Score: 0.9634627163605598
MSE: 0.0343684051854085
G-Mean 0.9632175303204764
Kappa: 0.930317745684041
MCC: 0.9309440376951955
Confusion Matrix:
 [[1406   87]
 [  27 1797]]


LightBoost

In [28]:
model = LGBMClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

[LightGBM] [Info] Number of positive: 4333, number of negative: 3405
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000767 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 89
[LightGBM] [Info] Number of data points in the train set: 7738, number of used features: 30
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.559964 -> initscore=0.241015
[LightGBM] [Info] Start training from score 0.241015
Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.94      0.96      1493
           1       0.95      0.98      0.97      1824

    accuracy                           0.96      3317
   macro avg       0.96      0.96      0.96      3317
weighted avg       0.96      0.96      0.96      3317

Accuracy: 0.9626168224299065
Precision: 0.9626168224299065
Recall: 0.9626168224299065
F1-Score:

CatBoost

In [29]:
model = CatBoostClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Learning rate set to 0.024682
0:	learn: 0.6524674	total: 144ms	remaining: 2m 24s
1:	learn: 0.6158239	total: 146ms	remaining: 1m 13s
2:	learn: 0.5787582	total: 149ms	remaining: 49.6s
3:	learn: 0.5474501	total: 152ms	remaining: 37.9s
4:	learn: 0.5178505	total: 155ms	remaining: 30.9s
5:	learn: 0.4884285	total: 158ms	remaining: 26.2s
6:	learn: 0.4600399	total: 161ms	remaining: 22.8s
7:	learn: 0.4370148	total: 165ms	remaining: 20.4s
8:	learn: 0.4148025	total: 168ms	remaining: 18.4s
9:	learn: 0.3966292	total: 171ms	remaining: 16.9s
10:	learn: 0.3794097	total: 174ms	remaining: 15.6s
11:	learn: 0.3618032	total: 177ms	remaining: 14.5s
12:	learn: 0.3463553	total: 180ms	remaining: 13.7s
13:	learn: 0.3329080	total: 183ms	remaining: 12.9s
14:	learn: 0.3197497	total: 186ms	remaining: 12.2s
15:	learn: 0.3103963	total: 189ms	remaining: 11.6s
16:	learn: 0.3006998	total: 192ms	remaining: 11.1s
17:	learn: 0.2916867	total: 195ms	remaining: 10.7s
18:	learn: 0.2814795	total: 198ms	remaining: 10.2s
19:	learn

Gradient Boost

In [30]:
model = GradientBoostingClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.91      0.93      1493
           1       0.93      0.97      0.95      1824

    accuracy                           0.94      3317
   macro avg       0.94      0.94      0.94      3317
weighted avg       0.94      0.94      0.94      3317

Accuracy: 0.9424178474525173
Precision: 0.9424178474525173
Recall: 0.9424178474525173
F1-Score: 0.9424178474525173
AUC Score: 0.93931659146191
MSE: 0.05758215254748267
G-Mean 0.9388023263048234
Kappa: 0.8830876449139702
MCC: 0.884229538954065
Confusion Matrix:
 [[1356  137]
 [  54 1770]]


SVM

In [31]:
model = SVC ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.91      0.94      1493
           1       0.93      0.98      0.95      1824

    accuracy                           0.95      3317
   macro avg       0.95      0.94      0.95      3317
weighted avg       0.95      0.95      0.95      3317

Accuracy: 0.9463370515526078
Precision: 0.9463370515526078
Recall: 0.9463370515526078
F1-Score: 0.9463370515526078
AUC Score: 0.9430017347034699
MSE: 0.05366294844739222
G-Mean 0.9424092145516326
Kappa: 0.8909851012146945
MCC: 0.8924027981255249
Confusion Matrix:
 [[1358  135]
 [  43 1781]]


KNN

In [33]:
X_train = np.array(X_train)
X_test = np.array(X_test)
model = KNeighborsClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.91      0.93      1493
           1       0.93      0.96      0.94      1824

    accuracy                           0.94      3317
   macro avg       0.94      0.93      0.93      3317
weighted avg       0.94      0.94      0.94      3317

Accuracy: 0.9357853482062104
Precision: 0.9357853482062104
Recall: 0.9357853482062104
F1-Score: 0.9357853482062104
AUC Score: 0.9334682098330219
MSE: 0.06421465179378957
G-Mean 0.9331793570436018
Kappa: 0.8698439039109962
MCC: 0.8703355749506172
Confusion Matrix:
 [[1359  134]
 [  79 1745]]


XGBoost

In [ ]:
model = XGBClassifier(
    learning_rate=0.1,
    n_estimators=100,
    max_depth=3,
    objective='multi:softprob',  
    num_class=5,  
    use_label_encoder=False
)
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

: 