Importing libraries

In [25]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import math
from sklearn.metrics import confusion_matrix, roc_auc_score, mean_squared_error, cohen_kappa_score, matthews_corrcoef
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from imblearn.metrics import geometric_mean_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier



Reading dataset

In [26]:
df = pd.read_csv('UNB.csv')
print (df.Type.value_counts())
df.head()

Type
Defacement    7930
benign        7781
phishing      7586
malware       6712
spam          6698
Name: count, dtype: int64


Querylength  domain_token_count  path_token_count  avgdomaintokenlen  \
0            0                   4                 5                5.5   
1            0                   4                 5                5.5   
2            0                   4                 5                5.5   
3            0                   4                12                5.5   
4            0                   4                 6                5.5   

   longdomaintokenlen  avgpathtokenlen  tld  charcompvowels  charcompace  \
0                  14         4.400000    4               8            3   
1                  14         6.000000    4              12            4   
2                  14         5.800000    4              12            5   
3                  14         5.500000    4              32           16   
4                  14         7.333334    4              18           11   

   ldl_url  ...  SymbolCount_FileName  SymbolCount_Extension  \
0        0  ...                     1                      0   
1        0  ...                     0                      0   
2        0  ...                     0                      0   
3        0  ...                     0                      0   
4        0  ...                     0                      0   

   SymbolCount_Afterpath  Entropy_URL  Entropy_Domain  Entropy_DirectoryName  \
0                     -1     0.726298        0.784493               0.894886   
1                     -1     0.688635        0.784493               0.814725   
2                     -1     0.695049        0.784493               0.814725   
3                     -1     0.640130        0.784493               0.814725   
4                     -1     0.681307        0.784493               0.814725   

   Entropy_Filename  Entropy_Extension  Entropy_Afterpath        Type  
0          0.850608                NaN               -1.0  Defacement  
1          0.859793                0.0               -1.0  Defacement  
2          0.801880                0.0               -1.0  Defacement  
3          0.663210                0.0               -1.0  Defacement  
4          0.804526                0.0               -1.0  Defacement  

[5 rows x 80 columns]

Data pre-processing

In [27]:
Label = LabelEncoder()
df['Type'] = Label.fit_transform(df['Type'])
print (df.Type.value_counts())
df.head()

Type
0    7930
1    7781
3    7586
2    6712
4    6698
Name: count, dtype: int64


Querylength  domain_token_count  path_token_count  avgdomaintokenlen  \
0            0                   4                 5                5.5   
1            0                   4                 5                5.5   
2            0                   4                 5                5.5   
3            0                   4                12                5.5   
4            0                   4                 6                5.5   

   longdomaintokenlen  avgpathtokenlen  tld  charcompvowels  charcompace  \
0                  14         4.400000    4               8            3   
1                  14         6.000000    4              12            4   
2                  14         5.800000    4              12            5   
3                  14         5.500000    4              32           16   
4                  14         7.333334    4              18           11   

   ldl_url  ...  SymbolCount_FileName  SymbolCount_Extension  \
0        0  ...                     1                      0   
1        0  ...                     0                      0   
2        0  ...                     0                      0   
3        0  ...                     0                      0   
4        0  ...                     0                      0   

   SymbolCount_Afterpath  Entropy_URL  Entropy_Domain  Entropy_DirectoryName  \
0                     -1     0.726298        0.784493               0.894886   
1                     -1     0.688635        0.784493               0.814725   
2                     -1     0.695049        0.784493               0.814725   
3                     -1     0.640130        0.784493               0.814725   
4                     -1     0.681307        0.784493               0.814725   

   Entropy_Filename  Entropy_Extension  Entropy_Afterpath  Type  
0          0.850608                NaN               -1.0     0  
1          0.859793                0.0               -1.0     0  
2          0.801880                0.0               -1.0     0  
3          0.663210                0.0               -1.0     0  
4          0.804526                0.0               -1.0     0  

[5 rows x 80 columns]

Data Cleaning

In [28]:
df = df.replace([np.inf, -np.inf], np.nan)
df.fillna(0, inplace=True)
print(df.max())
print(df.min())
df.head()

Querylength              1385.000000
domain_token_count         19.000000
path_token_count           68.000000
avgdomaintokenlen          29.500000
longdomaintokenlen         63.000000
                            ...     
Entropy_DirectoryName       0.962479
Entropy_Filename            1.000000
Entropy_Extension           1.000000
Entropy_Afterpath           1.000000
Type                        4.000000
Length: 80, dtype: float64
Querylength              0.0
domain_token_count       2.0
path_token_count         0.0
avgdomaintokenlen        1.5
longdomaintokenlen       2.0
                        ... 
Entropy_DirectoryName   -1.0
Entropy_Filename        -1.0
Entropy_Extension       -1.0
Entropy_Afterpath       -1.0
Type                     0.0
Length: 80, dtype: float64


Querylength  domain_token_count  path_token_count  avgdomaintokenlen  \
0            0                   4                 5                5.5   
1            0                   4                 5                5.5   
2            0                   4                 5                5.5   
3            0                   4                12                5.5   
4            0                   4                 6                5.5   

   longdomaintokenlen  avgpathtokenlen  tld  charcompvowels  charcompace  \
0                  14         4.400000    4               8            3   
1                  14         6.000000    4              12            4   
2                  14         5.800000    4              12            5   
3                  14         5.500000    4              32           16   
4                  14         7.333334    4              18           11   

   ldl_url  ...  SymbolCount_FileName  SymbolCount_Extension  \
0        0  ...                     1                      0   
1        0  ...                     0                      0   
2        0  ...                     0                      0   
3        0  ...                     0                      0   
4        0  ...                     0                      0   

   SymbolCount_Afterpath  Entropy_URL  Entropy_Domain  Entropy_DirectoryName  \
0                     -1     0.726298        0.784493               0.894886   
1                     -1     0.688635        0.784493               0.814725   
2                     -1     0.695049        0.784493               0.814725   
3                     -1     0.640130        0.784493               0.814725   
4                     -1     0.681307        0.784493               0.814725   

   Entropy_Filename  Entropy_Extension  Entropy_Afterpath  Type  
0          0.850608                0.0               -1.0     0  
1          0.859793                0.0               -1.0     0  
2          0.801880                0.0               -1.0     0  
3          0.663210                0.0               -1.0     0  
4          0.804526                0.0               -1.0     0  

[5 rows x 80 columns]

In [29]:
input = df.drop (['Type'], axis='columns')
target = df.Type
print(target.head())
input.head()

0    0
1    0
2    0
3    0
4    0
Name: Type, dtype: int32


Querylength  domain_token_count  path_token_count  avgdomaintokenlen  \
0            0                   4                 5                5.5   
1            0                   4                 5                5.5   
2            0                   4                 5                5.5   
3            0                   4                12                5.5   
4            0                   4                 6                5.5   

   longdomaintokenlen  avgpathtokenlen  tld  charcompvowels  charcompace  \
0                  14         4.400000    4               8            3   
1                  14         6.000000    4              12            4   
2                  14         5.800000    4              12            5   
3                  14         5.500000    4              32           16   
4                  14         7.333334    4              18           11   

   ldl_url  ...  SymbolCount_Directoryname  SymbolCount_FileName  \
0        0  ...                          2                     1   
1        0  ...                          3                     0   
2        0  ...                          3                     0   
3        0  ...                          3                     0   
4        0  ...                          3                     0   

   SymbolCount_Extension  SymbolCount_Afterpath  Entropy_URL  Entropy_Domain  \
0                      0                     -1     0.726298        0.784493   
1                      0                     -1     0.688635        0.784493   
2                      0                     -1     0.695049        0.784493   
3                      0                     -1     0.640130        0.784493   
4                      0                     -1     0.681307        0.784493   

   Entropy_DirectoryName  Entropy_Filename  Entropy_Extension  \
0               0.894886          0.850608                0.0   
1               0.814725          0.859793                0.0   
2               0.814725          0.801880                0.0   
3               0.814725          0.663210                0.0   
4               0.814725          0.804526                0.0   

   Entropy_Afterpath  
0               -1.0  
1               -1.0  
2               -1.0  
3               -1.0  
4               -1.0  

[5 rows x 79 columns]

Data splitting

In [30]:
X_train, X_test, y_train, y_test = train_test_split(input, target, test_size=0.3)
print (len (X_test))
print (len (X_train))

11013
25694


In [31]:
def report (y_test, y_pred):
    report = classification_report(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    # auc_score = roc_auc_score(y_test, y_pred, multi_class='ovo')
    mse = mean_squared_error(y_test, y_pred)
    kappa = cohen_kappa_score(y_test, y_pred)
    mcc = matthews_corrcoef(y_test, y_pred)
    g_mean = geometric_mean_score(y_test, y_pred)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='micro')
    recall = recall_score(y_test, y_pred, average='micro')
    f1 = f1_score(y_test, y_pred, average='micro')

    print("Classification Report:\n", report)
    print("Accuracy:", accuracy)
    print("Precision:", precision)
    print("Recall:", recall)
    print("F1-Score:", f1)
    # print("AUC Score:", auc_score)
    print("MSE:", mse)
    print("G-Mean", g_mean)
    print("Kappa:", kappa)
    print("MCC:", mcc)
    print("Confusion Matrix:\n", conf_matrix)


Logistic Regression

In [32]:
model = LogisticRegression ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.74      0.70      0.72      2379
           1       0.76      0.82      0.79      2334
           2       0.61      0.46      0.52      2018
           3       0.67      0.82      0.74      2290
           4       0.76      0.73      0.75      1992

    accuracy                           0.71     11013
   macro avg       0.71      0.71      0.70     11013
weighted avg       0.71      0.71      0.71     11013

Accuracy: 0.7141559974575502
Precision: 0.7141559974575502
Recall: 0.7141559974575502
F1-Score: 0.7141559974575503
MSE: 1.3208934895123945
G-Mean 0.6932227236073315
Kappa: 0.6416090333122388
MCC: 0.6435548506250164
Confusion Matrix:
 [[1677  115  193  251  143]
 [  88 1921  131  161   33]
 [ 177  387  925  348  181]
 [  89   93  128 1886   94]
 [ 223   12  138  163 1456]]


C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Decision Tree

In [33]:
model = DecisionTreeClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.97      0.96      2379
           1       0.96      0.96      0.96      2334
           2       0.95      0.97      0.96      2018
           3       0.92      0.89      0.90      2290
           4       0.97      0.97      0.97      1992

    accuracy                           0.95     11013
   macro avg       0.95      0.95      0.95     11013
weighted avg       0.95      0.95      0.95     11013

Accuracy: 0.9511486425133933
Precision: 0.9511486425133933
Recall: 0.9511486425133933
F1-Score: 0.9511486425133933
MSE: 0.2071188595296468
G-Mean 0.9513304752088385
Kappa: 0.9388531811171951
MCC: 0.9389055926215958
Confusion Matrix:
 [[2319   13    7   36    4]
 [  14 2231   21   63    5]
 [   6   12 1952   45    3]
 [  88   60   65 2035   42]
 [  15    0    3   36 1938]]


Naive Bayes

In [34]:
model = GaussianNB ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.56      0.75      0.64      2379
           1       0.61      0.85      0.71      2334
           2       0.56      0.48      0.52      2018
           3       0.63      0.47      0.54      2290
           4       0.79      0.47      0.59      1992

    accuracy                           0.61     11013
   macro avg       0.63      0.60      0.60     11013
weighted avg       0.63      0.61      0.60     11013

Accuracy: 0.611549986379733
Precision: 0.611549986379733
Recall: 0.611549986379733
F1-Score: 0.611549986379733
MSE: 1.9070189775719604
G-Mean 0.5824423120091815
Kappa: 0.5116193846627493
MCC: 0.5184045021825324
Confusion Matrix:
 [[1776  225  142  158   78]
 [ 181 1979  117   37   20]
 [ 400  447  974  132   65]
 [ 371  529  227 1075   88]
 [ 421   61  280  299  931]]


Random Forest

In [35]:
model = RandomForestClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.98      0.98      2379
           1       0.97      0.98      0.98      2334
           2       0.99      0.97      0.98      2018
           3       0.94      0.96      0.95      2290
           4       0.99      0.98      0.98      1992

    accuracy                           0.97     11013
   macro avg       0.98      0.97      0.97     11013
weighted avg       0.97      0.97      0.97     11013

Accuracy: 0.974484699900118
Precision: 0.974484699900118
Recall: 0.974484699900118
F1-Score: 0.974484699900118
MSE: 0.10306001997639154
G-Mean 0.9743589114939306
Kappa: 0.9680547869292535
MCC: 0.9680776686534601
Confusion Matrix:
 [[2340   11    1   26    1]
 [   4 2289    4   34    3]
 [   4   13 1963   38    0]
 [  32   38    8 2195   17]
 [   8    0    0   39 1945]]


LightBoost

In [36]:
model = LGBMClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.012778 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 9506
[LightGBM] [Info] Number of data points in the train set: 25694, number of used features: 77
[LightGBM] [Info] Start training from score -1.532279
[LightGBM] [Info] Start training from score -1.551193
[LightGBM] [Info] Start training from score -1.699972
[LightGBM] [Info] Start training from score -1.579306
[LightGBM] [Info] Start training from score -1.697419
Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.99      0.99      2379
           1       0.98      0.99      0.99      2334
           2       0.99      0.98      0.99      2018
           3       0.97      0.96      0.96      2290
           4       0.99      0.99      0.99      1992

    accuracy                           0.98     11013
   macro avg       0.98      0.98 

CatBoost

In [37]:
model = CatBoostClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Learning rate set to 0.093374
0:	learn: 1.4490092	total: 54.3ms	remaining: 54.2s
1:	learn: 1.3330428	total: 90ms	remaining: 44.9s
2:	learn: 1.2436038	total: 123ms	remaining: 40.9s
3:	learn: 1.1673617	total: 154ms	remaining: 38.3s
4:	learn: 1.1017660	total: 186ms	remaining: 37s
5:	learn: 1.0476028	total: 218ms	remaining: 36.1s
6:	learn: 0.9960638	total: 248ms	remaining: 35.1s
7:	learn: 0.9555712	total: 278ms	remaining: 34.5s
8:	learn: 0.9179318	total: 313ms	remaining: 34.5s
9:	learn: 0.8836933	total: 344ms	remaining: 34s
10:	learn: 0.8495863	total: 380ms	remaining: 34.2s
11:	learn: 0.8180510	total: 414ms	remaining: 34.1s
12:	learn: 0.7905917	total: 448ms	remaining: 34s
13:	learn: 0.7669958	total: 481ms	remaining: 33.9s
14:	learn: 0.7405565	total: 516ms	remaining: 33.9s
15:	learn: 0.7205922	total: 546ms	remaining: 33.6s
16:	learn: 0.6992341	total: 580ms	remaining: 33.5s
17:	learn: 0.6831992	total: 610ms	remaining: 33.3s
18:	learn: 0.6656201	total: 642ms	remaining: 33.1s
19:	learn: 0.6501

C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


Gradient Boost

In [38]:
model = GradientBoostingClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.95      0.96      2379
           1       0.94      0.96      0.95      2334
           2       0.95      0.93      0.94      2018
           3       0.90      0.92      0.91      2290
           4       0.98      0.97      0.97      1992

    accuracy                           0.94     11013
   macro avg       0.95      0.94      0.94     11013
weighted avg       0.94      0.94      0.94     11013

Accuracy: 0.9437936983564877
Precision: 0.9437936983564877
Recall: 0.9437936983564877
F1-Score: 0.9437936983564877
MSE: 0.21147734495596113
G-Mean 0.9435684196268028
Kappa: 0.929627931388852
MCC: 0.9296672863044627
Confusion Matrix:
 [[2267   31   12   65    4]
 [  11 2241   41   37    4]
 [  17   37 1867   94    3]
 [  50   74   47 2096   23]
 [  16    1    7   45 1923]]


SVM

In [39]:
model = SVC ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.76      0.71      0.73      2379
           1       0.74      0.84      0.78      2334
           2       0.68      0.47      0.55      2018
           3       0.64      0.88      0.74      2290
           4       0.85      0.67      0.75      1992

    accuracy                           0.72     11013
   macro avg       0.73      0.71      0.71     11013
weighted avg       0.73      0.72      0.72     11013

Accuracy: 0.7207845273767366
Precision: 0.7207845273767366
Recall: 0.7207845273767366
F1-Score: 0.7207845273767366
MSE: 1.2364478343775538
G-Mean 0.6964930339294263
Kappa: 0.6494092227876573
MCC: 0.6543202212423569
Confusion Matrix:
 [[1699   93  104  422   61]
 [ 122 1953   80  148   31]
 [ 225  415  944  332  102]
 [  53  100   86 2014   37]
 [ 151   91  183  239 1328]]


XGBoost

In [ ]:
model = XGBClassifier(
    learning_rate=0.1,
    n_estimators=100,
    max_depth=3,
    objective='multi:softprob',  
    num_class=5,  
    use_label_encoder=False
)
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

: 

KNN

In [ ]:
model = KNeighborsClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)