Importing libraries

In [15]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import math
from sklearn.metrics import confusion_matrix, roc_auc_score, mean_squared_error, cohen_kappa_score, matthews_corrcoef
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from sklearn.preprocessing import label_binarize
from imblearn.metrics import geometric_mean_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier



Reading dataset

In [16]:
df = pd.read_csv('UNB.csv')
print (df.Type.value_counts())
df.head()

Type
Defacement    7930
benign        7781
phishing      7586
malware       6712
spam          6698
Name: count, dtype: int64


Querylength  domain_token_count  path_token_count  avgdomaintokenlen  \
0            0                   4                 5                5.5   
1            0                   4                 5                5.5   
2            0                   4                 5                5.5   
3            0                   4                12                5.5   
4            0                   4                 6                5.5   

   longdomaintokenlen  avgpathtokenlen  tld  charcompvowels  charcompace  \
0                  14         4.400000    4               8            3   
1                  14         6.000000    4              12            4   
2                  14         5.800000    4              12            5   
3                  14         5.500000    4              32           16   
4                  14         7.333334    4              18           11   

   ldl_url  ...  SymbolCount_FileName  SymbolCount_Extension  \
0        0  ...                     1                      0   
1        0  ...                     0                      0   
2        0  ...                     0                      0   
3        0  ...                     0                      0   
4        0  ...                     0                      0   

   SymbolCount_Afterpath  Entropy_URL  Entropy_Domain  Entropy_DirectoryName  \
0                     -1     0.726298        0.784493               0.894886   
1                     -1     0.688635        0.784493               0.814725   
2                     -1     0.695049        0.784493               0.814725   
3                     -1     0.640130        0.784493               0.814725   
4                     -1     0.681307        0.784493               0.814725   

   Entropy_Filename  Entropy_Extension  Entropy_Afterpath        Type  
0          0.850608                NaN               -1.0  Defacement  
1          0.859793                0.0               -1.0  Defacement  
2          0.801880                0.0               -1.0  Defacement  
3          0.663210                0.0               -1.0  Defacement  
4          0.804526                0.0               -1.0  Defacement  

[5 rows x 80 columns]

Data pre-processing

In [17]:
Label = LabelEncoder()
df['Type'] = Label.fit_transform(df['Type'])
print (df.Type.value_counts())
df.head()

Type
0    7930
1    7781
3    7586
2    6712
4    6698
Name: count, dtype: int64


Querylength  domain_token_count  path_token_count  avgdomaintokenlen  \
0            0                   4                 5                5.5   
1            0                   4                 5                5.5   
2            0                   4                 5                5.5   
3            0                   4                12                5.5   
4            0                   4                 6                5.5   

   longdomaintokenlen  avgpathtokenlen  tld  charcompvowels  charcompace  \
0                  14         4.400000    4               8            3   
1                  14         6.000000    4              12            4   
2                  14         5.800000    4              12            5   
3                  14         5.500000    4              32           16   
4                  14         7.333334    4              18           11   

   ldl_url  ...  SymbolCount_FileName  SymbolCount_Extension  \
0        0  ...                     1                      0   
1        0  ...                     0                      0   
2        0  ...                     0                      0   
3        0  ...                     0                      0   
4        0  ...                     0                      0   

   SymbolCount_Afterpath  Entropy_URL  Entropy_Domain  Entropy_DirectoryName  \
0                     -1     0.726298        0.784493               0.894886   
1                     -1     0.688635        0.784493               0.814725   
2                     -1     0.695049        0.784493               0.814725   
3                     -1     0.640130        0.784493               0.814725   
4                     -1     0.681307        0.784493               0.814725   

   Entropy_Filename  Entropy_Extension  Entropy_Afterpath  Type  
0          0.850608                NaN               -1.0     0  
1          0.859793                0.0               -1.0     0  
2          0.801880                0.0               -1.0     0  
3          0.663210                0.0               -1.0     0  
4          0.804526                0.0               -1.0     0  

[5 rows x 80 columns]

Data Cleaning

In [18]:
df = df.replace([np.inf, -np.inf], np.nan)
df.fillna(0, inplace=True)
print(df.max())
print(df.min())
df.head()

Querylength              1385.000000
domain_token_count         19.000000
path_token_count           68.000000
avgdomaintokenlen          29.500000
longdomaintokenlen         63.000000
                            ...     
Entropy_DirectoryName       0.962479
Entropy_Filename            1.000000
Entropy_Extension           1.000000
Entropy_Afterpath           1.000000
Type                        4.000000
Length: 80, dtype: float64
Querylength              0.0
domain_token_count       2.0
path_token_count         0.0
avgdomaintokenlen        1.5
longdomaintokenlen       2.0
                        ... 
Entropy_DirectoryName   -1.0
Entropy_Filename        -1.0
Entropy_Extension       -1.0
Entropy_Afterpath       -1.0
Type                     0.0
Length: 80, dtype: float64


Querylength  domain_token_count  path_token_count  avgdomaintokenlen  \
0            0                   4                 5                5.5   
1            0                   4                 5                5.5   
2            0                   4                 5                5.5   
3            0                   4                12                5.5   
4            0                   4                 6                5.5   

   longdomaintokenlen  avgpathtokenlen  tld  charcompvowels  charcompace  \
0                  14         4.400000    4               8            3   
1                  14         6.000000    4              12            4   
2                  14         5.800000    4              12            5   
3                  14         5.500000    4              32           16   
4                  14         7.333334    4              18           11   

   ldl_url  ...  SymbolCount_FileName  SymbolCount_Extension  \
0        0  ...                     1                      0   
1        0  ...                     0                      0   
2        0  ...                     0                      0   
3        0  ...                     0                      0   
4        0  ...                     0                      0   

   SymbolCount_Afterpath  Entropy_URL  Entropy_Domain  Entropy_DirectoryName  \
0                     -1     0.726298        0.784493               0.894886   
1                     -1     0.688635        0.784493               0.814725   
2                     -1     0.695049        0.784493               0.814725   
3                     -1     0.640130        0.784493               0.814725   
4                     -1     0.681307        0.784493               0.814725   

   Entropy_Filename  Entropy_Extension  Entropy_Afterpath  Type  
0          0.850608                0.0               -1.0     0  
1          0.859793                0.0               -1.0     0  
2          0.801880                0.0               -1.0     0  
3          0.663210                0.0               -1.0     0  
4          0.804526                0.0               -1.0     0  

[5 rows x 80 columns]

In [19]:
input = df.drop (['Type'], axis='columns')
target = df.Type
print(target.head())
input.head()

0    0
1    0
2    0
3    0
4    0
Name: Type, dtype: int32


Querylength  domain_token_count  path_token_count  avgdomaintokenlen  \
0            0                   4                 5                5.5   
1            0                   4                 5                5.5   
2            0                   4                 5                5.5   
3            0                   4                12                5.5   
4            0                   4                 6                5.5   

   longdomaintokenlen  avgpathtokenlen  tld  charcompvowels  charcompace  \
0                  14         4.400000    4               8            3   
1                  14         6.000000    4              12            4   
2                  14         5.800000    4              12            5   
3                  14         5.500000    4              32           16   
4                  14         7.333334    4              18           11   

   ldl_url  ...  SymbolCount_Directoryname  SymbolCount_FileName  \
0        0  ...                          2                     1   
1        0  ...                          3                     0   
2        0  ...                          3                     0   
3        0  ...                          3                     0   
4        0  ...                          3                     0   

   SymbolCount_Extension  SymbolCount_Afterpath  Entropy_URL  Entropy_Domain  \
0                      0                     -1     0.726298        0.784493   
1                      0                     -1     0.688635        0.784493   
2                      0                     -1     0.695049        0.784493   
3                      0                     -1     0.640130        0.784493   
4                      0                     -1     0.681307        0.784493   

   Entropy_DirectoryName  Entropy_Filename  Entropy_Extension  \
0               0.894886          0.850608                0.0   
1               0.814725          0.859793                0.0   
2               0.814725          0.801880                0.0   
3               0.814725          0.663210                0.0   
4               0.814725          0.804526                0.0   

   Entropy_Afterpath  
0               -1.0  
1               -1.0  
2               -1.0  
3               -1.0  
4               -1.0  

[5 rows x 79 columns]

Data splitting

In [20]:
X_train, X_test, y_train, y_test = train_test_split(input, target, test_size=0.3)
print (len (X_test))
print (len (X_train))

11013
25694


In [21]:
def report (y_test, y_pred):
    n_classes = 5
    y_true_binary = label_binarize(y_test, classes=range(n_classes))
    y_pred_binary = label_binarize(y_pred, classes=range(n_classes))
    auc_score = roc_auc_score(y_true_binary, y_pred_binary, average='macro')

    report = classification_report(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    
    mse = mean_squared_error(y_test, y_pred)
    kappa = cohen_kappa_score(y_test, y_pred)
    mcc = matthews_corrcoef(y_test, y_pred)
    g_mean = geometric_mean_score(y_test, y_pred)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='micro')
    recall = recall_score(y_test, y_pred, average='micro')
    f1 = f1_score(y_test, y_pred, average='micro')

    print("Classification Report:\n", report)
    print("Accuracy:", accuracy)
    print("Precision:", precision)
    print("Recall:", recall)
    print("F1-Score:", f1)
    print("AUC Score:", auc_score)
    print("MSE:", mse)
    print("G-Mean", g_mean)
    print("Kappa:", kappa)
    print("MCC:", mcc)
    print("Confusion Matrix:\n", conf_matrix)


Logistic Regression

In [22]:
model = LogisticRegression ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.74      0.68      0.71      2447
           1       0.76      0.81      0.78      2329
           2       0.61      0.47      0.53      2000
           3       0.65      0.83      0.73      2249
           4       0.77      0.70      0.73      1988

    accuracy                           0.70     11013
   macro avg       0.70      0.70      0.70     11013
weighted avg       0.70      0.70      0.70     11013

Accuracy: 0.7045310088077726
Precision: 0.7045310088077726
Recall: 0.7045310088077726
F1-Score: 0.7045310088077726
AUC Score: 0.8124880014118601
MSE: 1.4157813493144467
G-Mean 0.6854958136537801
Kappa: 0.6295438578551211
MCC: 0.6319148614928083
Confusion Matrix:
 [[1662  110  191  312  172]
 [  93 1890  150  175   21]
 [ 173  386  939  347  155]
 [  79  105  115 1868   82]
 [ 235   12  148  193 1400]]


C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Decision Tree

In [23]:
model = DecisionTreeClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.97      0.97      2447
           1       0.97      0.96      0.96      2329
           2       0.94      0.97      0.95      2000
           3       0.91      0.89      0.90      2249
           4       0.97      0.96      0.97      1988

    accuracy                           0.95     11013
   macro avg       0.95      0.95      0.95     11013
weighted avg       0.95      0.95      0.95     11013

Accuracy: 0.9496050122582402
Precision: 0.9496050122582402
Recall: 0.9496050122582402
F1-Score: 0.9496050122582402
AUC Score: 0.9686572855809679
MSE: 0.20648324707164262
G-Mean 0.9494769889272456
Kappa: 0.9369052572237377
MCC: 0.9369316536475767
Confusion Matrix:
 [[2370    9   12   46   10]
 [  11 2230   23   60    5]
 [   4    9 1937   46    4]
 [  63   58   77 2008   43]
 [  13    3    8   51 1913]]


Naive Bayes

In [24]:
model = GaussianNB ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.57      0.74      0.64      2447
           1       0.60      0.86      0.71      2329
           2       0.57      0.47      0.51      2000
           3       0.62      0.47      0.53      2249
           4       0.78      0.45      0.57      1988

    accuracy                           0.61     11013
   macro avg       0.63      0.60      0.59     11013
weighted avg       0.62      0.61      0.60     11013

Accuracy: 0.6082811223099973
Precision: 0.6082811223099973
Recall: 0.6082811223099973
F1-Score: 0.6082811223099973
AUC Score: 0.749273140868964
MSE: 2.0078089530554797
G-Mean 0.5749198005565888
Kappa: 0.5067805873160671
MCC: 0.5141686439305088
Confusion Matrix:
 [[1810  228  133  181   95]
 [ 165 2005   90   44   25]
 [ 411  450  938  142   59]
 [ 362  582  184 1053   68]
 [ 441   78  301  275  893]]


Random Forest

In [25]:
model = RandomForestClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.98      0.98      2447
           1       0.97      0.98      0.98      2329
           2       0.99      0.97      0.98      2000
           3       0.93      0.96      0.94      2249
           4       0.99      0.97      0.98      1988

    accuracy                           0.97     11013
   macro avg       0.97      0.97      0.97     11013
weighted avg       0.97      0.97      0.97     11013

Accuracy: 0.9726686643058204
Precision: 0.9726686643058204
Recall: 0.9726686643058204
F1-Score: 0.9726686643058204
AUC Score: 0.982631506612844
MSE: 0.10868973031871425
G-Mean 0.9721002334241898
Kappa: 0.9657677648174013
MCC: 0.9658297128148019
Confusion Matrix:
 [[2405    5    3   33    1]
 [   1 2292    2   32    2]
 [   6   10 1932   46    6]
 [  22   54    7 2159    7]
 [   6    4    0   54 1924]]


LightBoost

In [26]:
model = LGBMClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003655 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 9473
[LightGBM] [Info] Number of data points in the train set: 25694, number of used features: 77
[LightGBM] [Info] Start training from score -1.544605
[LightGBM] [Info] Start training from score -1.550275
[LightGBM] [Info] Start training from score -1.696145
[LightGBM] [Info] Start training from score -1.571594
[LightGBM] [Info] Start training from score -1.696570
Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.99      0.99      2447
           1       0.98      0.99      0.98      2329
           2       0.99      0.98      0.98      2000
           3       0.96      0.97      0.96      2249
           4       1.00      0.98      0.99      1988

    accuracy            

CatBoost

In [27]:
model = CatBoostClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Learning rate set to 0.093374
0:	learn: 1.4525153	total: 197ms	remaining: 3m 16s
1:	learn: 1.3352738	total: 227ms	remaining: 1m 53s
2:	learn: 1.2452993	total: 256ms	remaining: 1m 24s
3:	learn: 1.1631612	total: 288ms	remaining: 1m 11s
4:	learn: 1.0998518	total: 316ms	remaining: 1m 2s
5:	learn: 1.0440622	total: 347ms	remaining: 57.5s
6:	learn: 0.9928031	total: 377ms	remaining: 53.4s
7:	learn: 0.9482635	total: 406ms	remaining: 50.3s
8:	learn: 0.9112252	total: 435ms	remaining: 47.9s
9:	learn: 0.8752613	total: 468ms	remaining: 46.3s
10:	learn: 0.8420252	total: 498ms	remaining: 44.8s
11:	learn: 0.8129721	total: 527ms	remaining: 43.3s
12:	learn: 0.7856194	total: 557ms	remaining: 42.3s
13:	learn: 0.7625663	total: 587ms	remaining: 41.4s
14:	learn: 0.7406705	total: 616ms	remaining: 40.4s
15:	learn: 0.7206156	total: 644ms	remaining: 39.6s
16:	learn: 0.6985321	total: 674ms	remaining: 39s
17:	learn: 0.6795818	total: 705ms	remaining: 38.4s
18:	learn: 0.6626376	total: 732ms	remaining: 37.8s
19:	learn

C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


Gradient Boost

In [28]:
model = GradientBoostingClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.95      0.96      2447
           1       0.94      0.97      0.95      2329
           2       0.94      0.91      0.93      2000
           3       0.88      0.91      0.89      2249
           4       0.99      0.96      0.97      1988

    accuracy                           0.94     11013
   macro avg       0.94      0.94      0.94     11013
weighted avg       0.94      0.94      0.94     11013

Accuracy: 0.9407064378461818
Precision: 0.9407064378461818
Recall: 0.9407064378461818
F1-Score: 0.9407064378461818
AUC Score: 0.9625692219097267
MSE: 0.21302097521111413
G-Mean 0.9396979895117621
Kappa: 0.9257323916332834
MCC: 0.9258430423422653
Confusion Matrix:
 [[2333   29    8   77    0]
 [   5 2254   31   38    1]
 [  14   39 1820  124    3]
 [  45   76   66 2047   15]
 [  15    5    9   53 1906]]


SVM

In [29]:
model = SVC ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.77      0.70      0.74      2447
           1       0.73      0.85      0.79      2329
           2       0.64      0.46      0.54      2000
           3       0.62      0.88      0.73      2249
           4       0.86      0.63      0.73      1988

    accuracy                           0.71     11013
   macro avg       0.72      0.70      0.70     11013
weighted avg       0.72      0.71      0.71     11013

Accuracy: 0.7127939707618269
Precision: 0.7127939707618269
Recall: 0.7127939707618269
F1-Score: 0.712793970761827
AUC Score: 0.816109999484657
MSE: 1.2716789249069282
G-Mean 0.686257109725591
Kappa: 0.6393601807230631
MCC: 0.6448719093537617
Confusion Matrix:
 [[1724  106  105  459   53]
 [ 106 1988   77  129   29]
 [ 218  419  921  344   98]
 [  49  111   99 1969   21]
 [ 146  111  230  253 1248]]


In [33]:
print(np.isnan(X_train).any())
print(np.isnan(X_test).any())

Querylength              False
domain_token_count       False
path_token_count         False
avgdomaintokenlen        False
longdomaintokenlen       False
                         ...  
Entropy_Domain           False
Entropy_DirectoryName    False
Entropy_Filename         False
Entropy_Extension        False
Entropy_Afterpath        False
Length: 79, dtype: bool
Querylength              False
domain_token_count       False
path_token_count         False
avgdomaintokenlen        False
longdomaintokenlen       False
                         ...  
Entropy_Domain           False
Entropy_DirectoryName    False
Entropy_Filename         False
Entropy_Extension        False
Entropy_Afterpath        False
Length: 79, dtype: bool


KNN

In [34]:
X_train = np.array(X_train)
X_test = np.array(X_test)
model = KNeighborsClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.94      0.93      2447
           1       0.91      0.93      0.92      2329
           2       0.91      0.93      0.92      2000
           3       0.90      0.85      0.87      2249
           4       0.94      0.93      0.93      1988

    accuracy                           0.91     11013
   macro avg       0.92      0.91      0.91     11013
weighted avg       0.91      0.91      0.91     11013

Accuracy: 0.9148279306274403
Precision: 0.9148279306274403
Recall: 0.9148279306274403
F1-Score: 0.9148279306274403
AUC Score: 0.9468085561916586
MSE: 0.4084264051575411
G-Mean 0.9143466278706603
Kappa: 0.8933438257084584
MCC: 0.8934471047896967
Confusion Matrix:
 [[2288   37   34   70   18]
 [  28 2174   55   41   31]
 [  29   36 1864   54   17]
 [ 116   93   76 1908   56]
 [  38   36   18   55 1841]]


XGBoost

In [ ]:
model = XGBClassifier(
    learning_rate=0.1,
    n_estimators=100,
    max_depth=3,
    objective='multi:softprob',  
    num_class=5,  
    use_label_encoder=False
)
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

: 