Importing libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import math
from sklearn.metrics import confusion_matrix, roc_auc_score, mean_squared_error, cohen_kappa_score, matthews_corrcoef
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from sklearn.preprocessing import label_binarize
from imblearn.metrics import geometric_mean_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier



Reading dataset

In [2]:
df = pd.read_csv('UNB.csv')
print (df.Type.value_counts())
df.head()

Type
Defacement    7930
benign        7781
phishing      7586
malware       6712
spam          6698
Name: count, dtype: int64


Querylength  domain_token_count  path_token_count  avgdomaintokenlen  \
0            0                   4                 5                5.5   
1            0                   4                 5                5.5   
2            0                   4                 5                5.5   
3            0                   4                12                5.5   
4            0                   4                 6                5.5   

   longdomaintokenlen  avgpathtokenlen  tld  charcompvowels  charcompace  \
0                  14         4.400000    4               8            3   
1                  14         6.000000    4              12            4   
2                  14         5.800000    4              12            5   
3                  14         5.500000    4              32           16   
4                  14         7.333334    4              18           11   

   ldl_url  ...  SymbolCount_FileName  SymbolCount_Extension  \
0        0  ...                     1                      0   
1        0  ...                     0                      0   
2        0  ...                     0                      0   
3        0  ...                     0                      0   
4        0  ...                     0                      0   

   SymbolCount_Afterpath  Entropy_URL  Entropy_Domain  Entropy_DirectoryName  \
0                     -1     0.726298        0.784493               0.894886   
1                     -1     0.688635        0.784493               0.814725   
2                     -1     0.695049        0.784493               0.814725   
3                     -1     0.640130        0.784493               0.814725   
4                     -1     0.681307        0.784493               0.814725   

   Entropy_Filename  Entropy_Extension  Entropy_Afterpath        Type  
0          0.850608                NaN               -1.0  Defacement  
1          0.859793                0.0               -1.0  Defacement  
2          0.801880                0.0               -1.0  Defacement  
3          0.663210                0.0               -1.0  Defacement  
4          0.804526                0.0               -1.0  Defacement  

[5 rows x 80 columns]

Data pre-processing

In [3]:
Label = LabelEncoder()
df['Type'] = Label.fit_transform(df['Type'])
print (df.Type.value_counts())
df.head()

Type
0    7930
1    7781
3    7586
2    6712
4    6698
Name: count, dtype: int64


Querylength  domain_token_count  path_token_count  avgdomaintokenlen  \
0            0                   4                 5                5.5   
1            0                   4                 5                5.5   
2            0                   4                 5                5.5   
3            0                   4                12                5.5   
4            0                   4                 6                5.5   

   longdomaintokenlen  avgpathtokenlen  tld  charcompvowels  charcompace  \
0                  14         4.400000    4               8            3   
1                  14         6.000000    4              12            4   
2                  14         5.800000    4              12            5   
3                  14         5.500000    4              32           16   
4                  14         7.333334    4              18           11   

   ldl_url  ...  SymbolCount_FileName  SymbolCount_Extension  \
0        0  ...                     1                      0   
1        0  ...                     0                      0   
2        0  ...                     0                      0   
3        0  ...                     0                      0   
4        0  ...                     0                      0   

   SymbolCount_Afterpath  Entropy_URL  Entropy_Domain  Entropy_DirectoryName  \
0                     -1     0.726298        0.784493               0.894886   
1                     -1     0.688635        0.784493               0.814725   
2                     -1     0.695049        0.784493               0.814725   
3                     -1     0.640130        0.784493               0.814725   
4                     -1     0.681307        0.784493               0.814725   

   Entropy_Filename  Entropy_Extension  Entropy_Afterpath  Type  
0          0.850608                NaN               -1.0     0  
1          0.859793                0.0               -1.0     0  
2          0.801880                0.0               -1.0     0  
3          0.663210                0.0               -1.0     0  
4          0.804526                0.0               -1.0     0  

[5 rows x 80 columns]

Data Cleaning

In [4]:
df = df.replace([np.inf, -np.inf], np.nan)
df.fillna(0, inplace=True)
print(df.max())
print(df.min())
df.head()

Querylength              1385.000000
domain_token_count         19.000000
path_token_count           68.000000
avgdomaintokenlen          29.500000
longdomaintokenlen         63.000000
                            ...     
Entropy_DirectoryName       0.962479
Entropy_Filename            1.000000
Entropy_Extension           1.000000
Entropy_Afterpath           1.000000
Type                        4.000000
Length: 80, dtype: float64
Querylength              0.0
domain_token_count       2.0
path_token_count         0.0
avgdomaintokenlen        1.5
longdomaintokenlen       2.0
                        ... 
Entropy_DirectoryName   -1.0
Entropy_Filename        -1.0
Entropy_Extension       -1.0
Entropy_Afterpath       -1.0
Type                     0.0
Length: 80, dtype: float64


Querylength  domain_token_count  path_token_count  avgdomaintokenlen  \
0            0                   4                 5                5.5   
1            0                   4                 5                5.5   
2            0                   4                 5                5.5   
3            0                   4                12                5.5   
4            0                   4                 6                5.5   

   longdomaintokenlen  avgpathtokenlen  tld  charcompvowels  charcompace  \
0                  14         4.400000    4               8            3   
1                  14         6.000000    4              12            4   
2                  14         5.800000    4              12            5   
3                  14         5.500000    4              32           16   
4                  14         7.333334    4              18           11   

   ldl_url  ...  SymbolCount_FileName  SymbolCount_Extension  \
0        0  ...                     1                      0   
1        0  ...                     0                      0   
2        0  ...                     0                      0   
3        0  ...                     0                      0   
4        0  ...                     0                      0   

   SymbolCount_Afterpath  Entropy_URL  Entropy_Domain  Entropy_DirectoryName  \
0                     -1     0.726298        0.784493               0.894886   
1                     -1     0.688635        0.784493               0.814725   
2                     -1     0.695049        0.784493               0.814725   
3                     -1     0.640130        0.784493               0.814725   
4                     -1     0.681307        0.784493               0.814725   

   Entropy_Filename  Entropy_Extension  Entropy_Afterpath  Type  
0          0.850608                0.0               -1.0     0  
1          0.859793                0.0               -1.0     0  
2          0.801880                0.0               -1.0     0  
3          0.663210                0.0               -1.0     0  
4          0.804526                0.0               -1.0     0  

[5 rows x 80 columns]

In [5]:
input = df.drop (['Type'], axis='columns')
target = df.Type
print(target.head())
input.head()

0    0
1    0
2    0
3    0
4    0
Name: Type, dtype: int32


Querylength  domain_token_count  path_token_count  avgdomaintokenlen  \
0            0                   4                 5                5.5   
1            0                   4                 5                5.5   
2            0                   4                 5                5.5   
3            0                   4                12                5.5   
4            0                   4                 6                5.5   

   longdomaintokenlen  avgpathtokenlen  tld  charcompvowels  charcompace  \
0                  14         4.400000    4               8            3   
1                  14         6.000000    4              12            4   
2                  14         5.800000    4              12            5   
3                  14         5.500000    4              32           16   
4                  14         7.333334    4              18           11   

   ldl_url  ...  SymbolCount_Directoryname  SymbolCount_FileName  \
0        0  ...                          2                     1   
1        0  ...                          3                     0   
2        0  ...                          3                     0   
3        0  ...                          3                     0   
4        0  ...                          3                     0   

   SymbolCount_Extension  SymbolCount_Afterpath  Entropy_URL  Entropy_Domain  \
0                      0                     -1     0.726298        0.784493   
1                      0                     -1     0.688635        0.784493   
2                      0                     -1     0.695049        0.784493   
3                      0                     -1     0.640130        0.784493   
4                      0                     -1     0.681307        0.784493   

   Entropy_DirectoryName  Entropy_Filename  Entropy_Extension  \
0               0.894886          0.850608                0.0   
1               0.814725          0.859793                0.0   
2               0.814725          0.801880                0.0   
3               0.814725          0.663210                0.0   
4               0.814725          0.804526                0.0   

   Entropy_Afterpath  
0               -1.0  
1               -1.0  
2               -1.0  
3               -1.0  
4               -1.0  

[5 rows x 79 columns]

Data splitting

In [6]:
X_train, X_test, y_train, y_test = train_test_split(input, target, test_size=0.2)
print (len (X_test))
print (len (X_train))

7342
29365


In [7]:
y_test.head()

11843    1
7859     0
7528     0
2072     0
16481    2
Name: Type, dtype: int32

In [8]:
def report (y_test, y_pred):
    n_classes = 5
    y_true_binary = label_binarize(y_test, classes=range(n_classes))
    y_pred_binary = label_binarize(y_pred, classes=range(n_classes))
    auc_score = roc_auc_score(y_true_binary, y_pred_binary, average='macro')

    report = classification_report(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    
    mse = mean_squared_error(y_test, y_pred)
    kappa = cohen_kappa_score(y_test, y_pred)
    mcc = matthews_corrcoef(y_test, y_pred)
    g_mean = geometric_mean_score(y_test, y_pred)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='micro')
    recall = recall_score(y_test, y_pred, average='micro')
    f1 = f1_score(y_test, y_pred, average='micro')

    print("Classification Report:\n", report)
    print("Accuracy:", accuracy)
    print("Precision:", precision)
    print("Recall:", recall)
    print("F1-Score:", f1)
    print("AUC Score:", auc_score)
    print("MSE:", mse)
    print("G-Mean", g_mean)
    print("Kappa:", kappa)
    print("MCC:", mcc)
    print("Confusion Matrix:\n", conf_matrix)


Logistic Regression

In [9]:
model = LogisticRegression ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.76      0.71      0.74      1634
           1       0.75      0.83      0.79      1471
           2       0.60      0.48      0.53      1364
           3       0.64      0.82      0.72      1474
           4       0.80      0.70      0.75      1399

    accuracy                           0.71      7342
   macro avg       0.71      0.71      0.70      7342
weighted avg       0.71      0.71      0.71      7342

Accuracy: 0.7101607191500954
Precision: 0.7101607191500954
Recall: 0.7101607191500954
F1-Score: 0.7101607191500954
AUC Score: 0.8170812638024648
MSE: 1.336284391174067
G-Mean 0.693754612797505
Kappa: 0.6371272037655885
MCC: 0.639436216269504
Confusion Matrix:
 [[1161   55  125  209   84]
 [  47 1215  104   97    8]
 [ 109  263  650  231  111]
 [  51   77   96 1203   47]
 [ 153   14  105  142  985]]


C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Decision Tree

In [10]:
model = DecisionTreeClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.97      0.97      1634
           1       0.96      0.98      0.97      1471
           2       0.96      0.97      0.97      1364
           3       0.92      0.89      0.91      1474
           4       0.97      0.97      0.97      1399

    accuracy                           0.96      7342
   macro avg       0.96      0.96      0.96      7342
weighted avg       0.96      0.96      0.96      7342

Accuracy: 0.9561427403977117
Precision: 0.9561427403977117
Recall: 0.9561427403977117
F1-Score: 0.9561427403977117
AUC Score: 0.972578800110275
MSE: 0.19531462816671208
G-Mean 0.9555873422105737
Kappa: 0.945122855797927
MCC: 0.9451630723944014
Confusion Matrix:
 [[1590    7    0   30    7]
 [   4 1435    6   24    2]
 [   2    6 1326   25    5]
 [  42   41   47 1316   28]
 [  10    5    3   28 1353]]


Naive Bayes

In [11]:
model = GaussianNB ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.59      0.77      0.67      1634
           1       0.60      0.87      0.71      1471
           2       0.57      0.48      0.52      1364
           3       0.63      0.46      0.53      1474
           4       0.78      0.45      0.57      1399

    accuracy                           0.61      7342
   macro avg       0.63      0.61      0.60      7342
weighted avg       0.63      0.61      0.60      7342

Accuracy: 0.6134568237537456
Precision: 0.6134568237537456
Recall: 0.6134568237537456
F1-Score: 0.6134568237537456
AUC Score: 0.7546435964511993
MSE: 1.9511032416235359
G-Mean 0.5818956483243609
Kappa: 0.51467945513543
MCC: 0.5225085509457716
Confusion Matrix:
 [[1266  130   89   95   54]
 [ 111 1277   47   20   16]
 [ 248  310  659  101   46]
 [ 222  370  150  672   60]
 [ 305   57  221  186  630]]


Random Forest

In [12]:
model = RandomForestClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.98      0.98      1634
           1       0.98      0.99      0.98      1471
           2       0.99      0.97      0.98      1364
           3       0.93      0.97      0.95      1474
           4       0.99      0.97      0.98      1399

    accuracy                           0.98      7342
   macro avg       0.98      0.98      0.98      7342
weighted avg       0.98      0.98      0.98      7342

Accuracy: 0.9754835194769818
Precision: 0.9754835194769818
Recall: 0.9754835194769818
F1-Score: 0.9754835194769818
AUC Score: 0.9845698521710389
MSE: 0.09983655679651321
G-Mean 0.9752491509347937
Kappa: 0.969321790245645
MCC: 0.9693842661042986
Confusion Matrix:
 [[1601    2    1   26    4]
 [   3 1453    2   12    1]
 [   0    5 1325   31    3]
 [   9   27    5 1426    7]
 [   4    2    0   36 1357]]


LightBoost

In [13]:
model = LGBMClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004588 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 9560
[LightGBM] [Info] Number of data points in the train set: 29365, number of used features: 77
[LightGBM] [Info] Start training from score -1.539889
[LightGBM] [Info] Start training from score -1.537668
[LightGBM] [Info] Start training from score -1.703081
[LightGBM] [Info] Start training from score -1.569549
[LightGBM] [Info] Start training from score -1.712285
Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.99      0.99      1634
           1       0.98      0.99      0.99      1471
           2       0.99      0.98      0.99      1364
           3       0.96      0.97      0.96      1474
           4       0.99      0.98      0.99      1399

    accuracy            

CatBoost

In [14]:
model = CatBoostClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Learning rate set to 0.094012
0:	learn: 1.4480707	total: 204ms	remaining: 3m 23s
1:	learn: 1.3331653	total: 256ms	remaining: 2m 7s
2:	learn: 1.2461824	total: 318ms	remaining: 1m 45s
3:	learn: 1.1652605	total: 385ms	remaining: 1m 35s
4:	learn: 1.1045794	total: 438ms	remaining: 1m 27s
5:	learn: 1.0487509	total: 498ms	remaining: 1m 22s
6:	learn: 0.9973399	total: 550ms	remaining: 1m 18s
7:	learn: 0.9528253	total: 631ms	remaining: 1m 18s
8:	learn: 0.9155241	total: 701ms	remaining: 1m 17s
9:	learn: 0.8794186	total: 771ms	remaining: 1m 16s
10:	learn: 0.8474570	total: 845ms	remaining: 1m 15s
11:	learn: 0.8184687	total: 993ms	remaining: 1m 21s
12:	learn: 0.7924025	total: 1.06s	remaining: 1m 20s
13:	learn: 0.7680729	total: 1.12s	remaining: 1m 18s
14:	learn: 0.7415581	total: 1.17s	remaining: 1m 16s
15:	learn: 0.7187373	total: 1.22s	remaining: 1m 14s
16:	learn: 0.7017209	total: 1.28s	remaining: 1m 13s
17:	learn: 0.6808505	total: 1.32s	remaining: 1m 11s
18:	learn: 0.6630428	total: 1.36s	remaining: 

C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


Gradient Boost

In [15]:
model = GradientBoostingClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.95      0.96      1634
           1       0.93      0.97      0.95      1471
           2       0.93      0.89      0.91      1364
           3       0.87      0.90      0.89      1474
           4       0.98      0.96      0.97      1399

    accuracy                           0.94      7342
   macro avg       0.94      0.94      0.94      7342
weighted avg       0.94      0.94      0.94      7342

Accuracy: 0.9368019613184418
Precision: 0.9368019613184418
Recall: 0.9368019613184418
F1-Score: 0.9368019613184418
AUC Score: 0.9601038400788744
MSE: 0.21983110868973033
G-Mean 0.9354627610564997
Kappa: 0.9209142839632235
MCC: 0.9210319738188137
Confusion Matrix:
 [[1558   13   11   51    1]
 [   5 1433   17   16    0]
 [  12   36 1219   92    5]
 [  22   50   52 1331   19]
 [  15    1   12   34 1337]]


SVM

In [16]:
model = SVC ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.78      0.71      0.74      1634
           1       0.72      0.88      0.79      1471
           2       0.65      0.47      0.55      1364
           3       0.62      0.87      0.73      1474
           4       0.87      0.62      0.73      1399

    accuracy                           0.72      7342
   macro avg       0.73      0.71      0.71      7342
weighted avg       0.73      0.72      0.71      7342

Accuracy: 0.7160174339417053
Precision: 0.7160174339417053
Recall: 0.7160174339417053
F1-Score: 0.7160174339417053
AUC Score: 0.8201987593801165
MSE: 1.285753200762735
G-Mean 0.6934851790069259
Kappa: 0.6442539384090373
MCC: 0.6500616584698077
Confusion Matrix:
 [[1168   50   72  301   43]
 [  61 1288   39   65   18]
 [ 152  278  644  232   58]
 [  32   78   66 1288   10]
 [  93   91  168  178  869]]


KNN

In [17]:
X_train = np.array(X_train)
X_test = np.array(X_test)
model = KNeighborsClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.95      0.93      1634
           1       0.91      0.94      0.93      1471
           2       0.92      0.93      0.92      1364
           3       0.90      0.86      0.88      1474
           4       0.96      0.92      0.94      1399

    accuracy                           0.92      7342
   macro avg       0.92      0.92      0.92      7342
weighted avg       0.92      0.92      0.92      7342

Accuracy: 0.9207300463089076
Precision: 0.9207300463089076
Recall: 0.9207300463089076
F1-Score: 0.9207300463089076
AUC Score: 0.9500875680601837
MSE: 0.36257150640152547
G-Mean 0.9194866901098296
Kappa: 0.9007727178267791
MCC: 0.9009489370866588
Confusion Matrix:
 [[1560   14   10   45    5]
 [  33 1382   35   16    5]
 [  18   41 1262   36    7]
 [  74   56   44 1267   33]
 [  33   19   15   43 1289]]


In [18]:
X_train = np.array(X_train)
X_test = np.array(X_test)
model = KNeighborsClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.95      0.93      1634
           1       0.91      0.94      0.93      1471
           2       0.92      0.93      0.92      1364
           3       0.90      0.86      0.88      1474
           4       0.96      0.92      0.94      1399

    accuracy                           0.92      7342
   macro avg       0.92      0.92      0.92      7342
weighted avg       0.92      0.92      0.92      7342

Accuracy: 0.9207300463089076
Precision: 0.9207300463089076
Recall: 0.9207300463089076
F1-Score: 0.9207300463089076
AUC Score: 0.9500875680601837
MSE: 0.36257150640152547
G-Mean 0.9194866901098296
Kappa: 0.9007727178267791
MCC: 0.9009489370866588
Confusion Matrix:
 [[1560   14   10   45    5]
 [  33 1382   35   16    5]
 [  18   41 1262   36    7]
 [  74   56   44 1267   33]
 [  33   19   15   43 1289]]


Deep Learning

In [19]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from keras.utils import to_categorical
from numpy import argmax

ANN

In [20]:
num_classes = 5
model = Sequential()
model.add(Dense(128, activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(64, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

y_pred = model.predict(X_test)
y_pred2= argmax(y_pred, axis=1)
report(y_test, y_pred2)



Epoch 1/10


735/735 [==============================] - 3s 2ms/step - loss: 0.9955 - accuracy: 0.7007 - val_loss: 0.5957 - val_accuracy: 0.7967
Epoch 2/10
735/735 [==============================] - 1s 2ms/step - loss: 0.5466 - accuracy: 0.8107 - val_loss: 0.5107 - val_accuracy: 0.8308
Epoch 3/10
735/735 [==============================] - 2s 2ms/step - loss: 0.4355 - accuracy: 0.8455 - val_loss: 0.4441 - val_accuracy: 0.8371
Epoch 4/10
735/735 [==============================] - 2s 3ms/step - loss: 0.3861 - accuracy: 0.8640 - val_loss: 0.3976 - val_accuracy: 0.8624
Epoch 5/10
735/735 [==============================] - 2s 2ms/step - loss: 0.3563 - accuracy: 0.8747 - val_loss: 0.4791 - val_accuracy: 0.8406
Epoch 6/10
735/735 [==============================] - 1s 2ms/step - loss: 0.3407 - accuracy: 0.8797 - val_loss: 0.3445 - val_accuracy: 0.8840
Epoch 7/10
735/735 [==============================] - 1s 2ms/step - loss: 0.3068 - accuracy: 0.8941 - val_loss: 0.3387 - val_accuracy: 0.8842
Ep

CNN

In [21]:
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten

In [22]:
model = Sequential()
model.add(Conv1D(64, kernel_size=3, activation='relu', input_shape=(X_train.shape[1], 1)))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(num_classes, activation='softmax')) 

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

y_pred = model.predict (X_test)
y_pred2= argmax(y_pred, axis=1)
report(y_test, y_pred2)


Epoch 1/10
735/735 [==============================] - 6s 6ms/step - loss: 1.0496 - accuracy: 0.6600 - val_loss: 0.7276 - val_accuracy: 0.7558
Epoch 2/10
735/735 [==============================] - 4s 5ms/step - loss: 0.5781 - accuracy: 0.7904 - val_loss: 0.5371 - val_accuracy: 0.7960
Epoch 3/10
735/735 [==============================] - 4s 5ms/step - loss: 0.4739 - accuracy: 0.8301 - val_loss: 0.5009 - val_accuracy: 0.8151
Epoch 4/10
735/735 [==============================] - 3s 4ms/step - loss: 0.4113 - accuracy: 0.8532 - val_loss: 0.3925 - val_accuracy: 0.8605
Epoch 5/10
735/735 [==============================] - 3s 4ms/step - loss: 0.3874 - accuracy: 0.8623 - val_loss: 0.4012 - val_accuracy: 0.8527
Epoch 6/10
735/735 [==============================] - 3s 5ms/step - loss: 0.3485 - accuracy: 0.8794 - val_loss: 0.4233 - val_accuracy: 0.8520
Epoch 7/10
735/735 [==============================] - 3s 5ms/step - loss: 0.3236 - accuracy: 0.8843 - val_loss: 0.3844 - val_accuracy: 0.8631
Epoch

RNN

In [23]:
from tensorflow.keras.layers import SimpleRNN

In [24]:
model = Sequential()
model.add(SimpleRNN(64, activation='relu', input_shape=(X_train.shape[1], 1)))
model.add(Dense(128, activation='relu'))
model.add(Dense(num_classes, activation='softmax')) 

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

y_pred = model.predict (X_test)
y_pred2= argmax(y_pred, axis=1)
report(y_test, y_pred2)

Epoch 1/10
735/735 [==============================] - 8s 9ms/step - loss: 0.9534 - accuracy: 0.6400 - val_loss: 0.7250 - val_accuracy: 0.7456
Epoch 2/10
735/735 [==============================] - 6s 9ms/step - loss: 0.6930 - accuracy: 0.7487 - val_loss: 0.6537 - val_accuracy: 0.7730
Epoch 3/10
735/735 [==============================] - 6s 8ms/step - loss: 0.6001 - accuracy: 0.7825 - val_loss: 0.6092 - val_accuracy: 0.7911
Epoch 4/10
735/735 [==============================] - 6s 8ms/step - loss: 0.5760 - accuracy: 0.7909 - val_loss: 0.5725 - val_accuracy: 0.7986
Epoch 5/10
735/735 [==============================] - 6s 8ms/step - loss: 0.5272 - accuracy: 0.8088 - val_loss: 0.5305 - val_accuracy: 0.8226
Epoch 6/10
735/735 [==============================] - 6s 8ms/step - loss: 0.4977 - accuracy: 0.8193 - val_loss: 0.5224 - val_accuracy: 0.8207
Epoch 7/10
735/735 [==============================] - 6s 8ms/step - loss: 0.4725 - accuracy: 0.8285 - val_loss: 0.4831 - val_accuracy: 0.8345
Epoch 

LSTM

In [25]:
from tensorflow.keras.layers import LSTM

In [26]:
model = Sequential()
model.add(LSTM(64, activation='relu', input_shape=(X_train.shape[1], 1)))
model.add(Dense(128, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

y_pred = model.predict (X_test)
y_pred2= argmax(y_pred, axis=1)
report(y_test, y_pred2)

Epoch 1/10
735/735 [==============================] - 16s 20ms/step - loss: 4629368.5000 - accuracy: 0.2262 - val_loss: 613880.2500 - val_accuracy: 0.1655
Epoch 2/10
735/735 [==============================] - 15s 21ms/step - loss: 1299607.3750 - accuracy: 0.1909 - val_loss: 18637.9727 - val_accuracy: 0.2443
Epoch 3/10
735/735 [==============================] - 17s 22ms/step - loss: 208470.8125 - accuracy: 0.2365 - val_loss: 82140.3906 - val_accuracy: 0.2682
Epoch 4/10
735/735 [==============================] - 16s 22ms/step - loss: 54728.4453 - accuracy: 0.2329 - val_loss: 3289.6211 - val_accuracy: 0.1323
Epoch 5/10
735/735 [==============================] - 15s 21ms/step - loss: 6524.7974 - accuracy: 0.2218 - val_loss: 5706.5894 - val_accuracy: 0.2326
Epoch 6/10
735/735 [==============================] - 15s 21ms/step - loss: 8423.2373 - accuracy: 0.2241 - val_loss: 10057.7051 - val_accuracy: 0.2488
Epoch 7/10
735/735 [==============================] - 17s 24ms/step - loss: 14726.8955

C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1471