Importing libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import math
from sklearn.metrics import confusion_matrix, roc_auc_score, mean_squared_error, cohen_kappa_score, matthews_corrcoef
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from sklearn.preprocessing import label_binarize
from imblearn.metrics import geometric_mean_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier



Reading dataset

In [2]:
df = pd.read_csv('UNB.csv')
print (df.Type.value_counts())
df.head()

Type
Defacement    7930
benign        7781
phishing      7586
malware       6712
spam          6698
Name: count, dtype: int64


Querylength  domain_token_count  path_token_count  avgdomaintokenlen  \
0            0                   4                 5                5.5   
1            0                   4                 5                5.5   
2            0                   4                 5                5.5   
3            0                   4                12                5.5   
4            0                   4                 6                5.5   

   longdomaintokenlen  avgpathtokenlen  tld  charcompvowels  charcompace  \
0                  14         4.400000    4               8            3   
1                  14         6.000000    4              12            4   
2                  14         5.800000    4              12            5   
3                  14         5.500000    4              32           16   
4                  14         7.333334    4              18           11   

   ldl_url  ...  SymbolCount_FileName  SymbolCount_Extension  \
0        0  ...                     1                      0   
1        0  ...                     0                      0   
2        0  ...                     0                      0   
3        0  ...                     0                      0   
4        0  ...                     0                      0   

   SymbolCount_Afterpath  Entropy_URL  Entropy_Domain  Entropy_DirectoryName  \
0                     -1     0.726298        0.784493               0.894886   
1                     -1     0.688635        0.784493               0.814725   
2                     -1     0.695049        0.784493               0.814725   
3                     -1     0.640130        0.784493               0.814725   
4                     -1     0.681307        0.784493               0.814725   

   Entropy_Filename  Entropy_Extension  Entropy_Afterpath        Type  
0          0.850608                NaN               -1.0  Defacement  
1          0.859793                0.0               -1.0  Defacement  
2          0.801880                0.0               -1.0  Defacement  
3          0.663210                0.0               -1.0  Defacement  
4          0.804526                0.0               -1.0  Defacement  

[5 rows x 80 columns]

Data pre-processing

In [3]:
Label = LabelEncoder()
df['Type'] = Label.fit_transform(df['Type'])
print (df.Type.value_counts())
df.head()

Type
0    7930
1    7781
3    7586
2    6712
4    6698
Name: count, dtype: int64


Querylength  domain_token_count  path_token_count  avgdomaintokenlen  \
0            0                   4                 5                5.5   
1            0                   4                 5                5.5   
2            0                   4                 5                5.5   
3            0                   4                12                5.5   
4            0                   4                 6                5.5   

   longdomaintokenlen  avgpathtokenlen  tld  charcompvowels  charcompace  \
0                  14         4.400000    4               8            3   
1                  14         6.000000    4              12            4   
2                  14         5.800000    4              12            5   
3                  14         5.500000    4              32           16   
4                  14         7.333334    4              18           11   

   ldl_url  ...  SymbolCount_FileName  SymbolCount_Extension  \
0        0  ...                     1                      0   
1        0  ...                     0                      0   
2        0  ...                     0                      0   
3        0  ...                     0                      0   
4        0  ...                     0                      0   

   SymbolCount_Afterpath  Entropy_URL  Entropy_Domain  Entropy_DirectoryName  \
0                     -1     0.726298        0.784493               0.894886   
1                     -1     0.688635        0.784493               0.814725   
2                     -1     0.695049        0.784493               0.814725   
3                     -1     0.640130        0.784493               0.814725   
4                     -1     0.681307        0.784493               0.814725   

   Entropy_Filename  Entropy_Extension  Entropy_Afterpath  Type  
0          0.850608                NaN               -1.0     0  
1          0.859793                0.0               -1.0     0  
2          0.801880                0.0               -1.0     0  
3          0.663210                0.0               -1.0     0  
4          0.804526                0.0               -1.0     0  

[5 rows x 80 columns]

Data Cleaning

In [4]:
df = df.replace([np.inf, -np.inf], np.nan)
df.fillna(0, inplace=True)
print(df.max())
print(df.min())
df.head()

Querylength              1385.000000
domain_token_count         19.000000
path_token_count           68.000000
avgdomaintokenlen          29.500000
longdomaintokenlen         63.000000
                            ...     
Entropy_DirectoryName       0.962479
Entropy_Filename            1.000000
Entropy_Extension           1.000000
Entropy_Afterpath           1.000000
Type                        4.000000
Length: 80, dtype: float64
Querylength              0.0
domain_token_count       2.0
path_token_count         0.0
avgdomaintokenlen        1.5
longdomaintokenlen       2.0
                        ... 
Entropy_DirectoryName   -1.0
Entropy_Filename        -1.0
Entropy_Extension       -1.0
Entropy_Afterpath       -1.0
Type                     0.0
Length: 80, dtype: float64


Querylength  domain_token_count  path_token_count  avgdomaintokenlen  \
0            0                   4                 5                5.5   
1            0                   4                 5                5.5   
2            0                   4                 5                5.5   
3            0                   4                12                5.5   
4            0                   4                 6                5.5   

   longdomaintokenlen  avgpathtokenlen  tld  charcompvowels  charcompace  \
0                  14         4.400000    4               8            3   
1                  14         6.000000    4              12            4   
2                  14         5.800000    4              12            5   
3                  14         5.500000    4              32           16   
4                  14         7.333334    4              18           11   

   ldl_url  ...  SymbolCount_FileName  SymbolCount_Extension  \
0        0  ...                     1                      0   
1        0  ...                     0                      0   
2        0  ...                     0                      0   
3        0  ...                     0                      0   
4        0  ...                     0                      0   

   SymbolCount_Afterpath  Entropy_URL  Entropy_Domain  Entropy_DirectoryName  \
0                     -1     0.726298        0.784493               0.894886   
1                     -1     0.688635        0.784493               0.814725   
2                     -1     0.695049        0.784493               0.814725   
3                     -1     0.640130        0.784493               0.814725   
4                     -1     0.681307        0.784493               0.814725   

   Entropy_Filename  Entropy_Extension  Entropy_Afterpath  Type  
0          0.850608                0.0               -1.0     0  
1          0.859793                0.0               -1.0     0  
2          0.801880                0.0               -1.0     0  
3          0.663210                0.0               -1.0     0  
4          0.804526                0.0               -1.0     0  

[5 rows x 80 columns]

In [5]:
input = df.drop (['Type'], axis='columns')
target = df.Type
print(target.head())
input.head()

0    0
1    0
2    0
3    0
4    0
Name: Type, dtype: int32


Querylength  domain_token_count  path_token_count  avgdomaintokenlen  \
0            0                   4                 5                5.5   
1            0                   4                 5                5.5   
2            0                   4                 5                5.5   
3            0                   4                12                5.5   
4            0                   4                 6                5.5   

   longdomaintokenlen  avgpathtokenlen  tld  charcompvowels  charcompace  \
0                  14         4.400000    4               8            3   
1                  14         6.000000    4              12            4   
2                  14         5.800000    4              12            5   
3                  14         5.500000    4              32           16   
4                  14         7.333334    4              18           11   

   ldl_url  ...  SymbolCount_Directoryname  SymbolCount_FileName  \
0        0  ...                          2                     1   
1        0  ...                          3                     0   
2        0  ...                          3                     0   
3        0  ...                          3                     0   
4        0  ...                          3                     0   

   SymbolCount_Extension  SymbolCount_Afterpath  Entropy_URL  Entropy_Domain  \
0                      0                     -1     0.726298        0.784493   
1                      0                     -1     0.688635        0.784493   
2                      0                     -1     0.695049        0.784493   
3                      0                     -1     0.640130        0.784493   
4                      0                     -1     0.681307        0.784493   

   Entropy_DirectoryName  Entropy_Filename  Entropy_Extension  \
0               0.894886          0.850608                0.0   
1               0.814725          0.859793                0.0   
2               0.814725          0.801880                0.0   
3               0.814725          0.663210                0.0   
4               0.814725          0.804526                0.0   

   Entropy_Afterpath  
0               -1.0  
1               -1.0  
2               -1.0  
3               -1.0  
4               -1.0  

[5 rows x 79 columns]

Data splitting

In [6]:
X_train, X_test, y_train, y_test = train_test_split(input, target, test_size=0.3)
print (len (X_test))
print (len (X_train))

11013
25694


In [36]:
def report (y_test, y_pred):
    n_classes = 5
    y_true_binary = label_binarize(y_test, classes=range(n_classes))
    y_pred_binary = label_binarize(y_pred, classes=range(n_classes))
    auc_score = roc_auc_score(y_true_binary, y_pred_binary, average='macro')

    report = classification_report(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    
    mse = mean_squared_error(y_test, y_pred)
    kappa = cohen_kappa_score(y_test, y_pred)
    mcc = matthews_corrcoef(y_test, y_pred)
    g_mean = geometric_mean_score(y_test, y_pred)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='micro')
    recall = recall_score(y_test, y_pred, average='micro')
    f1 = f1_score(y_test, y_pred, average='micro')

    print("Classification Report:\n", report)
    print("Accuracy:", accuracy)
    print("Precision:", precision)
    print("Recall:", recall)
    print("F1-Score:", f1)
    print("AUC Score:", auc_score)
    print("MSE:", mse)
    print("G-Mean", g_mean)
    print("Kappa:", kappa)
    print("MCC:", mcc)
    print("Confusion Matrix:\n", conf_matrix)


Logistic Regression

In [8]:
model = LogisticRegression ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.74      0.68      0.71      2385
           1       0.73      0.81      0.77      2341
           2       0.65      0.44      0.53      2056
           3       0.62      0.83      0.71      2225
           4       0.76      0.72      0.74      2006

    accuracy                           0.70     11013
   macro avg       0.70      0.70      0.69     11013
weighted avg       0.70      0.70      0.69     11013

Accuracy: 0.6998093162625988
Precision: 0.6998093162625988
Recall: 0.6998093162625988
F1-Score: 0.6998093162625988
AUC Score: 0.8101080905612589
MSE: 1.4255879415236539
G-Mean 0.6795110647044935
Kappa: 0.6238272697756462
MCC: 0.6272536853159331
Confusion Matrix:
 [[1628  117  140  337  163]
 [  86 1887  155  192   21]
 [ 156  420  911  374  195]
 [  96  120   82 1838   89]
 [ 224   28  108  203 1443]]


C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Decision Tree

In [9]:
model = DecisionTreeClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.97      0.96      2385
           1       0.97      0.96      0.97      2341
           2       0.95      0.97      0.96      2056
           3       0.91      0.88      0.90      2225
           4       0.96      0.97      0.97      2006

    accuracy                           0.95     11013
   macro avg       0.95      0.95      0.95     11013
weighted avg       0.95      0.95      0.95     11013

Accuracy: 0.9493326069190956
Precision: 0.9493326069190956
Recall: 0.9493326069190956
F1-Score: 0.9493326069190956
AUC Score: 0.9684832588068447
MSE: 0.22836647598292928
G-Mean 0.9490129782164913
Kappa: 0.9365968382702132
MCC: 0.936644026724209
Confusion Matrix:
 [[2303   11    4   52   15]
 [   9 2255   23   50    4]
 [   7    7 1985   49    8]
 [  86   51   79 1962   47]
 [  12    4    8   32 1950]]


Naive Bayes

In [10]:
model = GaussianNB ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.59      0.73      0.65      2385
           1       0.60      0.86      0.71      2341
           2       0.57      0.50      0.53      2056
           3       0.60      0.47      0.53      2225
           4       0.79      0.45      0.57      2006

    accuracy                           0.61     11013
   macro avg       0.63      0.60      0.60     11013
weighted avg       0.63      0.61      0.60     11013

Accuracy: 0.6120947970580224
Precision: 0.6120947970580224
Recall: 0.6120947970580224
F1-Score: 0.6120947970580224
AUC Score: 0.7525143777493921
MSE: 1.8775992009443385
G-Mean 0.5814982647499101
Kappa: 0.5123162507306309
MCC: 0.5188787588784038
Confusion Matrix:
 [[1747  230  147  189   72]
 [ 157 2023  104   43   14]
 [ 359  449 1021  152   75]
 [ 306  571  209 1056   83]
 [ 406   77  321  308  894]]


Random Forest

In [11]:
model = RandomForestClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.98      0.98      2385
           1       0.97      0.99      0.98      2341
           2       0.99      0.97      0.98      2056
           3       0.93      0.96      0.94      2225
           4       0.99      0.98      0.98      2006

    accuracy                           0.97     11013
   macro avg       0.97      0.97      0.97     11013
weighted avg       0.97      0.97      0.97     11013

Accuracy: 0.9725778625261056
Precision: 0.9725778625261056
Recall: 0.9725778625261056
F1-Score: 0.9725778625261056
AUC Score: 0.9827320428728681
MSE: 0.12013075456278943
G-Mean 0.9723116159687658
Kappa: 0.9656767611260259
MCC: 0.9657236136792727
Confusion Matrix:
 [[2329    5    2   48    1]
 [   2 2306    4   26    3]
 [   1   12 1988   52    3]
 [  28   43   11 2132   11]
 [   9    1    2   38 1956]]


LightBoost

In [12]:
model = LGBMClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.011838 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 9537
[LightGBM] [Info] Number of data points in the train set: 25694, number of used features: 77
[LightGBM] [Info] Start training from score -1.533361
[LightGBM] [Info] Start training from score -1.552478
[LightGBM] [Info] Start training from score -1.708101
[LightGBM] [Info] Start training from score -1.567107
[LightGBM] [Info] Start training from score -1.700399
Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.99      0.99      2385
           1       0.98      0.99      0.98      2341
           2       0.99      0.98      0.98      2056
           3       0.96      0.97      0.96      2225
           4       1.00      0.99      0.99      2006

    accuracy                           0.98     11013
   macro avg       0.98      0.98 

CatBoost

In [13]:
model = CatBoostClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Learning rate set to 0.093374
0:	learn: 1.4496640	total: 230ms	remaining: 3m 50s
1:	learn: 1.3312025	total: 263ms	remaining: 2m 11s
2:	learn: 1.2362471	total: 292ms	remaining: 1m 37s
3:	learn: 1.1573317	total: 323ms	remaining: 1m 20s
4:	learn: 1.0973395	total: 354ms	remaining: 1m 10s
5:	learn: 1.0394446	total: 385ms	remaining: 1m 3s
6:	learn: 0.9868368	total: 413ms	remaining: 58.6s
7:	learn: 0.9401814	total: 446ms	remaining: 55.3s
8:	learn: 0.8988001	total: 479ms	remaining: 52.7s
9:	learn: 0.8681614	total: 510ms	remaining: 50.5s
10:	learn: 0.8353458	total: 539ms	remaining: 48.5s
11:	learn: 0.8039242	total: 571ms	remaining: 47s
12:	learn: 0.7780393	total: 602ms	remaining: 45.7s
13:	learn: 0.7514129	total: 632ms	remaining: 44.5s
14:	learn: 0.7258830	total: 663ms	remaining: 43.5s
15:	learn: 0.7025497	total: 693ms	remaining: 42.6s
16:	learn: 0.6815433	total: 725ms	remaining: 41.9s
17:	learn: 0.6645577	total: 756ms	remaining: 41.2s
18:	learn: 0.6492137	total: 783ms	remaining: 40.4s
19:	lear

C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


Gradient Boost

In [14]:
model = GradientBoostingClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.96      0.96      2385
           1       0.95      0.96      0.95      2341
           2       0.93      0.91      0.92      2056
           3       0.89      0.91      0.90      2225
           4       0.99      0.96      0.97      2006

    accuracy                           0.94     11013
   macro avg       0.94      0.94      0.94     11013
weighted avg       0.94      0.94      0.94     11013

Accuracy: 0.9407972396258967
Precision: 0.9407972396258967
Recall: 0.9407972396258967
F1-Score: 0.9407972396258967
AUC Score: 0.9627639351365737
MSE: 0.2245528012349042
G-Mean 0.9400776185367125
Kappa: 0.9258933496002129
MCC: 0.9259346952703237
Confusion Matrix:
 [[2284   23   10   66    2]
 [   5 2245   51   36    4]
 [  17   41 1879  115    4]
 [  59   63   62 2023   18]
 [  21    3   10   42 1930]]


SVM

In [15]:
model = SVC ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.76      0.69      0.72      2385
           1       0.73      0.86      0.79      2341
           2       0.68      0.46      0.55      2056
           3       0.61      0.88      0.72      2225
           4       0.85      0.62      0.72      2006

    accuracy                           0.71     11013
   macro avg       0.72      0.70      0.70     11013
weighted avg       0.72      0.71      0.70     11013

Accuracy: 0.709615908471806
Precision: 0.709615908471806
Recall: 0.709615908471806
F1-Score: 0.709615908471806
AUC Score: 0.8149622459879083
MSE: 1.2855715972033053
G-Mean 0.6845789889130138
Kappa: 0.635688750591457
MCC: 0.6418390168750747
Confusion Matrix:
 [[1653  101   90  476   65]
 [ 116 2010   81  112   22]
 [ 219  423  951  354  109]
 [  60  104   77 1952   32]
 [ 136  119  209  293 1249]]


In [16]:
print(np.isnan(X_train).any())
print(np.isnan(X_test).any())

Querylength              False
domain_token_count       False
path_token_count         False
avgdomaintokenlen        False
longdomaintokenlen       False
                         ...  
Entropy_Domain           False
Entropy_DirectoryName    False
Entropy_Filename         False
Entropy_Extension        False
Entropy_Afterpath        False
Length: 79, dtype: bool
Querylength              False
domain_token_count       False
path_token_count         False
avgdomaintokenlen        False
longdomaintokenlen       False
                         ...  
Entropy_Domain           False
Entropy_DirectoryName    False
Entropy_Filename         False
Entropy_Extension        False
Entropy_Afterpath        False
Length: 79, dtype: bool


KNN

In [17]:
X_train = np.array(X_train)
X_test = np.array(X_test)
model = KNeighborsClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.95      0.93      2385
           1       0.92      0.94      0.93      2341
           2       0.94      0.93      0.93      2056
           3       0.89      0.86      0.87      2225
           4       0.95      0.92      0.93      2006

    accuracy                           0.92     11013
   macro avg       0.92      0.92      0.92     11013
weighted avg       0.92      0.92      0.92     11013

Accuracy: 0.919731226732044
Precision: 0.919731226732044
Recall: 0.919731226732044
F1-Score: 0.919731226732044
AUC Score: 0.9495390976585639
MSE: 0.4136021066012894
G-Mean 0.9186643544015407
Kappa: 0.8995044908228856
MCC: 0.8996331792139772
Confusion Matrix:
 [[2270   24   13   73    5]
 [  32 2192   43   39   35]
 [  25   34 1915   66   16]
 [ 119   99   58 1910   39]
 [  60   32   16   56 1842]]


In [18]:
X_train = np.array(X_train)
X_test = np.array(X_test)
model = KNeighborsClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.95      0.93      2385
           1       0.92      0.94      0.93      2341
           2       0.94      0.93      0.93      2056
           3       0.89      0.86      0.87      2225
           4       0.95      0.92      0.93      2006

    accuracy                           0.92     11013
   macro avg       0.92      0.92      0.92     11013
weighted avg       0.92      0.92      0.92     11013

Accuracy: 0.919731226732044
Precision: 0.919731226732044
Recall: 0.919731226732044
F1-Score: 0.919731226732044
AUC Score: 0.9495390976585639
MSE: 0.4136021066012894
G-Mean 0.9186643544015407
Kappa: 0.8995044908228856
MCC: 0.8996331792139772
Confusion Matrix:
 [[2270   24   13   73    5]
 [  32 2192   43   39   35]
 [  25   34 1915   66   16]
 [ 119   99   58 1910   39]
 [  60   32   16   56 1842]]


Deep Learning

In [29]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from keras.utils import to_categorical

ANN

In [45]:
num_classes = 5
model = Sequential()
model.add(Dense(128, activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(64, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

y_pred = model.predict(X_test)
report(y_test, y_pred)


Epoch 1/10
643/643 [==============================] - 2s 2ms/step - loss: 0.9879 - accuracy: 0.7050 - val_loss: 0.6887 - val_accuracy: 0.7733
Epoch 2/10
643/643 [==============================] - 1s 1ms/step - loss: 0.5574 - accuracy: 0.8049 - val_loss: 0.5135 - val_accuracy: 0.8268
Epoch 3/10
643/643 [==============================] - 1s 1ms/step - loss: 0.4779 - accuracy: 0.8396 - val_loss: 0.4320 - val_accuracy: 0.8521
Epoch 4/10
643/643 [==============================] - 1s 1ms/step - loss: 0.4005 - accuracy: 0.8588 - val_loss: 0.4918 - val_accuracy: 0.8260
Epoch 5/10
643/643 [==============================] - 1s 1ms/step - loss: 0.4159 - accuracy: 0.8620 - val_loss: 0.4211 - val_accuracy: 0.8515
Epoch 6/10
643/643 [==============================] - 1s 1ms/step - loss: 0.3454 - accuracy: 0.8792 - val_loss: 0.3445 - val_accuracy: 0.8887
Epoch 7/10
643/643 [==============================] - 1s 1ms/step - loss: 0.3199 - accuracy: 0.8886 - val_loss: 0.3616 - val_accuracy: 0.8739
Epoch 

ValueError: Multioutput target data is not supported with label binarization

CNN

In [46]:
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten

In [47]:
model = Sequential()
model.add(Conv1D(64, kernel_size=3, activation='relu', input_shape=(X_train.shape[1], 1)))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(num_classes, activation='softmax')) 

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

y_pred = model.predict (X_test)
y_pred_binary = (y_pred > 0.5).astype(int)
report (y_test, y_pred_binary)

Epoch 1/10


ValueError: in user code:

    File "C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\engine\training.py", line 1401, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\engine\training.py", line 1384, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\engine\training.py", line 1373, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\engine\training.py", line 1151, in train_step
        loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\engine\training.py", line 1209, in compute_loss
        return self.compiled_loss(
    File "C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\engine\compile_utils.py", line 277, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\losses.py", line 143, in __call__
        losses = call_fn(y_true, y_pred)
    File "C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\losses.py", line 270, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\losses.py", line 2221, in categorical_crossentropy
        return backend.categorical_crossentropy(
    File "C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\backend.py", line 5573, in categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)

    ValueError: Shapes (None, 1) and (None, 5) are incompatible


RNN

In [ ]:
from tensorflow.keras.layers import SimpleRNN

In [ ]:
model = Sequential()
model.add(SimpleRNN(64, activation='relu', input_shape=(X_train.shape[1], 1)))
model.add(Dense(128, activation='relu'))
model.add(Dense(num_classes, activation='softmax')) 

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

y_pred = model.predict (X_test)
y_pred_binary = (y_pred > 0.5).astype(int)
report (y_test, y_pred_binary)

Epoch 1/10
643/643 [==============================] - 6s 8ms/step - loss: -46626757670862848.0000 - accuracy: 0.2109 - val_loss: -0.1792 - val_accuracy: 0.2146
Epoch 2/10
643/643 [==============================] - 5s 7ms/step - loss: -0.5313 - accuracy: 0.2110 - val_loss: -0.9121 - val_accuracy: 0.2146
Epoch 3/10
643/643 [==============================] - 4s 7ms/step - loss: -1.2069 - accuracy: 0.2110 - val_loss: -1.5651 - val_accuracy: 0.2146
Epoch 4/10
643/643 [==============================] - 5s 7ms/step - loss: -1.8222 - accuracy: 0.2110 - val_loss: -2.1743 - val_accuracy: 0.2146
Epoch 5/10
643/643 [==============================] - 5s 8ms/step - loss: -2.4053 - accuracy: 0.2110 - val_loss: -2.7626 - val_accuracy: 0.2146
Epoch 6/10
643/643 [==============================] - 5s 7ms/step - loss: -2.9744 - accuracy: 0.2110 - val_loss: -3.3417 - val_accuracy: 0.2146
Epoch 7/10
643/643 [==============================] - 4s 7ms/step - loss: -3.5394 - accuracy: 0.2110 - val_loss: -3.9208

C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1471

LSTM

In [ ]:
from tensorflow.keras.layers import LSTM

In [ ]:
model = Sequential()
model.add(LSTM(64, activation='relu', input_shape=(X_train.shape[1], 1)))
model.add(Dense(128, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

y_pred = model.predict (X_test)
y_pred_binary = (y_pred > 0.5).astype(int)
report (y_test, y_pred_binary)

Epoch 1/10
643/643 [==============================] - 14s 19ms/step - loss: 943736922046464.0000 - accuracy: 0.2110 - val_loss: -0.2034 - val_accuracy: 0.2146
Epoch 2/10
643/643 [==============================] - 12s 18ms/step - loss: -0.5742 - accuracy: 0.2110 - val_loss: -0.9676 - val_accuracy: 0.2146
Epoch 3/10
643/643 [==============================] - 11s 17ms/step - loss: -1.2684 - accuracy: 0.2110 - val_loss: -1.6320 - val_accuracy: 0.2146
Epoch 4/10
643/643 [==============================] - 11s 17ms/step - loss: -1.8890 - accuracy: 0.2110 - val_loss: -2.2442 - val_accuracy: 0.2146
Epoch 5/10
643/643 [==============================] - 12s 18ms/step - loss: -2.4743 - accuracy: 0.2110 - val_loss: -2.8330 - val_accuracy: 0.2146
Epoch 6/10
643/643 [==============================] - 12s 18ms/step - loss: -3.0438 - accuracy: 0.2110 - val_loss: -3.4132 - val_accuracy: 0.2146
Epoch 7/10
643/643 [==============================] - 12s 19ms/step - loss: -3.6090 - accuracy: 0.2110 - val_lo

C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1471