Importing libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import math
from sklearn.metrics import confusion_matrix, roc_auc_score, mean_squared_error, cohen_kappa_score, matthews_corrcoef
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from sklearn.preprocessing import label_binarize
from imblearn.metrics import geometric_mean_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier



Reading dataset

In [2]:
df = pd.read_csv('UNB.csv')
print (df.Type.value_counts())
df.head()

Type
Defacement    7930
benign        7781
phishing      7586
malware       6712
spam          6698
Name: count, dtype: int64


Querylength  domain_token_count  path_token_count  avgdomaintokenlen  \
0            0                   4                 5                5.5   
1            0                   4                 5                5.5   
2            0                   4                 5                5.5   
3            0                   4                12                5.5   
4            0                   4                 6                5.5   

   longdomaintokenlen  avgpathtokenlen  tld  charcompvowels  charcompace  \
0                  14         4.400000    4               8            3   
1                  14         6.000000    4              12            4   
2                  14         5.800000    4              12            5   
3                  14         5.500000    4              32           16   
4                  14         7.333334    4              18           11   

   ldl_url  ...  SymbolCount_FileName  SymbolCount_Extension  \
0        0  ...                     1                      0   
1        0  ...                     0                      0   
2        0  ...                     0                      0   
3        0  ...                     0                      0   
4        0  ...                     0                      0   

   SymbolCount_Afterpath  Entropy_URL  Entropy_Domain  Entropy_DirectoryName  \
0                     -1     0.726298        0.784493               0.894886   
1                     -1     0.688635        0.784493               0.814725   
2                     -1     0.695049        0.784493               0.814725   
3                     -1     0.640130        0.784493               0.814725   
4                     -1     0.681307        0.784493               0.814725   

   Entropy_Filename  Entropy_Extension  Entropy_Afterpath        Type  
0          0.850608                NaN               -1.0  Defacement  
1          0.859793                0.0               -1.0  Defacement  
2          0.801880                0.0               -1.0  Defacement  
3          0.663210                0.0               -1.0  Defacement  
4          0.804526                0.0               -1.0  Defacement  

[5 rows x 80 columns]

Data pre-processing

In [3]:
Label = LabelEncoder()
df['Type'] = Label.fit_transform(df['Type'])
print (df.Type.value_counts())
df.head()

Type
0    7930
1    7781
3    7586
2    6712
4    6698
Name: count, dtype: int64


Querylength  domain_token_count  path_token_count  avgdomaintokenlen  \
0            0                   4                 5                5.5   
1            0                   4                 5                5.5   
2            0                   4                 5                5.5   
3            0                   4                12                5.5   
4            0                   4                 6                5.5   

   longdomaintokenlen  avgpathtokenlen  tld  charcompvowels  charcompace  \
0                  14         4.400000    4               8            3   
1                  14         6.000000    4              12            4   
2                  14         5.800000    4              12            5   
3                  14         5.500000    4              32           16   
4                  14         7.333334    4              18           11   

   ldl_url  ...  SymbolCount_FileName  SymbolCount_Extension  \
0        0  ...                     1                      0   
1        0  ...                     0                      0   
2        0  ...                     0                      0   
3        0  ...                     0                      0   
4        0  ...                     0                      0   

   SymbolCount_Afterpath  Entropy_URL  Entropy_Domain  Entropy_DirectoryName  \
0                     -1     0.726298        0.784493               0.894886   
1                     -1     0.688635        0.784493               0.814725   
2                     -1     0.695049        0.784493               0.814725   
3                     -1     0.640130        0.784493               0.814725   
4                     -1     0.681307        0.784493               0.814725   

   Entropy_Filename  Entropy_Extension  Entropy_Afterpath  Type  
0          0.850608                NaN               -1.0     0  
1          0.859793                0.0               -1.0     0  
2          0.801880                0.0               -1.0     0  
3          0.663210                0.0               -1.0     0  
4          0.804526                0.0               -1.0     0  

[5 rows x 80 columns]

Data Cleaning

In [4]:
df = df.replace([np.inf, -np.inf], np.nan)
df.fillna(0, inplace=True)
print(df.max())
print(df.min())
df.head()

Querylength              1385.000000
domain_token_count         19.000000
path_token_count           68.000000
avgdomaintokenlen          29.500000
longdomaintokenlen         63.000000
                            ...     
Entropy_DirectoryName       0.962479
Entropy_Filename            1.000000
Entropy_Extension           1.000000
Entropy_Afterpath           1.000000
Type                        4.000000
Length: 80, dtype: float64
Querylength              0.0
domain_token_count       2.0
path_token_count         0.0
avgdomaintokenlen        1.5
longdomaintokenlen       2.0
                        ... 
Entropy_DirectoryName   -1.0
Entropy_Filename        -1.0
Entropy_Extension       -1.0
Entropy_Afterpath       -1.0
Type                     0.0
Length: 80, dtype: float64


Querylength  domain_token_count  path_token_count  avgdomaintokenlen  \
0            0                   4                 5                5.5   
1            0                   4                 5                5.5   
2            0                   4                 5                5.5   
3            0                   4                12                5.5   
4            0                   4                 6                5.5   

   longdomaintokenlen  avgpathtokenlen  tld  charcompvowels  charcompace  \
0                  14         4.400000    4               8            3   
1                  14         6.000000    4              12            4   
2                  14         5.800000    4              12            5   
3                  14         5.500000    4              32           16   
4                  14         7.333334    4              18           11   

   ldl_url  ...  SymbolCount_FileName  SymbolCount_Extension  \
0        0  ...                     1                      0   
1        0  ...                     0                      0   
2        0  ...                     0                      0   
3        0  ...                     0                      0   
4        0  ...                     0                      0   

   SymbolCount_Afterpath  Entropy_URL  Entropy_Domain  Entropy_DirectoryName  \
0                     -1     0.726298        0.784493               0.894886   
1                     -1     0.688635        0.784493               0.814725   
2                     -1     0.695049        0.784493               0.814725   
3                     -1     0.640130        0.784493               0.814725   
4                     -1     0.681307        0.784493               0.814725   

   Entropy_Filename  Entropy_Extension  Entropy_Afterpath  Type  
0          0.850608                0.0               -1.0     0  
1          0.859793                0.0               -1.0     0  
2          0.801880                0.0               -1.0     0  
3          0.663210                0.0               -1.0     0  
4          0.804526                0.0               -1.0     0  

[5 rows x 80 columns]

In [5]:
input = df.drop (['Type'], axis='columns')
target = df.Type
print(target.head())
input.head()

0    0
1    0
2    0
3    0
4    0
Name: Type, dtype: int32


Querylength  domain_token_count  path_token_count  avgdomaintokenlen  \
0            0                   4                 5                5.5   
1            0                   4                 5                5.5   
2            0                   4                 5                5.5   
3            0                   4                12                5.5   
4            0                   4                 6                5.5   

   longdomaintokenlen  avgpathtokenlen  tld  charcompvowels  charcompace  \
0                  14         4.400000    4               8            3   
1                  14         6.000000    4              12            4   
2                  14         5.800000    4              12            5   
3                  14         5.500000    4              32           16   
4                  14         7.333334    4              18           11   

   ldl_url  ...  SymbolCount_Directoryname  SymbolCount_FileName  \
0        0  ...                          2                     1   
1        0  ...                          3                     0   
2        0  ...                          3                     0   
3        0  ...                          3                     0   
4        0  ...                          3                     0   

   SymbolCount_Extension  SymbolCount_Afterpath  Entropy_URL  Entropy_Domain  \
0                      0                     -1     0.726298        0.784493   
1                      0                     -1     0.688635        0.784493   
2                      0                     -1     0.695049        0.784493   
3                      0                     -1     0.640130        0.784493   
4                      0                     -1     0.681307        0.784493   

   Entropy_DirectoryName  Entropy_Filename  Entropy_Extension  \
0               0.894886          0.850608                0.0   
1               0.814725          0.859793                0.0   
2               0.814725          0.801880                0.0   
3               0.814725          0.663210                0.0   
4               0.814725          0.804526                0.0   

   Entropy_Afterpath  
0               -1.0  
1               -1.0  
2               -1.0  
3               -1.0  
4               -1.0  

[5 rows x 79 columns]

Data splitting

In [6]:
X_train, X_test, y_train, y_test = train_test_split(input, target, test_size=0.3)
print (len (X_test))
print (len (X_train))

11013
25694


In [7]:
y_test.head()

30564    4
23446    3
12615    1
25225    3
12152    1
Name: Type, dtype: int32

In [8]:
def report (y_test, y_pred):
    n_classes = 5
    y_true_binary = label_binarize(y_test, classes=range(n_classes))
    y_pred_binary = label_binarize(y_pred, classes=range(n_classes))
    auc_score = roc_auc_score(y_true_binary, y_pred_binary, average='macro')

    report = classification_report(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    
    mse = mean_squared_error(y_test, y_pred)
    kappa = cohen_kappa_score(y_test, y_pred)
    mcc = matthews_corrcoef(y_test, y_pred)
    g_mean = geometric_mean_score(y_test, y_pred)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='micro')
    recall = recall_score(y_test, y_pred, average='micro')
    f1 = f1_score(y_test, y_pred, average='micro')

    print("Classification Report:\n", report)
    print("Accuracy:", accuracy)
    print("Precision:", precision)
    print("Recall:", recall)
    print("F1-Score:", f1)
    print("AUC Score:", auc_score)
    print("MSE:", mse)
    print("G-Mean", g_mean)
    print("Kappa:", kappa)
    print("MCC:", mcc)
    print("Confusion Matrix:\n", conf_matrix)


Logistic Regression

In [9]:
model = LogisticRegression ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.76      0.71      0.73      2425
           1       0.76      0.83      0.79      2316
           2       0.63      0.48      0.55      2015
           3       0.65      0.82      0.72      2253
           4       0.77      0.72      0.75      2004

    accuracy                           0.72     11013
   macro avg       0.72      0.71      0.71     11013
weighted avg       0.72      0.72      0.71     11013

Accuracy: 0.7162444383909925
Precision: 0.7162444383909925
Recall: 0.7162444383909925
F1-Score: 0.7162444383909925
AUC Score: 0.8199403511105373
MSE: 1.3272496140924361
G-Mean 0.6985020278834934
Kappa: 0.6443188153107908
MCC: 0.6464751406653328
Confusion Matrix:
 [[1715   94  188  284  144]
 [  69 1914  139  178   16]
 [ 160  384  972  333  166]
 [  91  117  110 1839   96]
 [ 219   12  132  193 1448]]


C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Decision Tree

In [10]:
model = DecisionTreeClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.96      0.96      2425
           1       0.96      0.97      0.96      2316
           2       0.95      0.97      0.96      2015
           3       0.90      0.88      0.89      2253
           4       0.97      0.96      0.96      2004

    accuracy                           0.95     11013
   macro avg       0.95      0.95      0.95     11013
weighted avg       0.95      0.95      0.95     11013

Accuracy: 0.9462453464087897
Precision: 0.9462453464087897
Recall: 0.9462453464087897
F1-Score: 0.9462453464087897
AUC Score: 0.9665284225881157
MSE: 0.24861527285934804
G-Mean 0.9458829746668872
Kappa: 0.9327067377919428
MCC: 0.9327468685348479
Confusion Matrix:
 [[2334    6    3   71   11]
 [  12 2244   18   42    0]
 [   9   11 1947   43    5]
 [  87   70   77 1977   42]
 [  17    6    9   53 1919]]


Naive Bayes

In [11]:
model = GaussianNB ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.58      0.74      0.65      2425
           1       0.59      0.86      0.70      2316
           2       0.56      0.47      0.51      2015
           3       0.64      0.47      0.54      2253
           4       0.77      0.45      0.57      2004

    accuracy                           0.61     11013
   macro avg       0.63      0.60      0.60     11013
weighted avg       0.62      0.61      0.60     11013

Accuracy: 0.6101879596840099
Precision: 0.6101879596840099
Recall: 0.6101879596840099
F1-Score: 0.6101879596840099
AUC Score: 0.7510806038423127
MSE: 1.9440661036956324
G-Mean 0.5783724906246823
Kappa: 0.5096975057109288
MCC: 0.516832570866194
Confusion Matrix:
 [[1804  224  137  158  102]
 [ 175 1991   93   35   22]
 [ 374  484  950  139   68]
 [ 322  570  210 1065   86]
 [ 432   78  305  279  910]]


Random Forest

In [12]:
model = RandomForestClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.98      0.98      2425
           1       0.97      0.99      0.98      2316
           2       0.99      0.97      0.98      2015
           3       0.93      0.96      0.94      2253
           4       0.99      0.97      0.98      2004

    accuracy                           0.97     11013
   macro avg       0.97      0.97      0.97     11013
weighted avg       0.97      0.97      0.97     11013

Accuracy: 0.9713066376100972
Precision: 0.9713066376100972
Recall: 0.9713066376100972
F1-Score: 0.9713066376100972
AUC Score: 0.9818827649987988
MSE: 0.13366021974030692
G-Mean 0.9709385383689425
Kappa: 0.9640729415580289
MCC: 0.9641275283489683
Confusion Matrix:
 [[2366    7    1   49    2]
 [   1 2286    4   23    2]
 [   3    9 1955   47    1]
 [  26   49   10 2156   12]
 [  18    0    3   49 1934]]


LightBoost

In [13]:
model = LGBMClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003269 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 9482
[LightGBM] [Info] Number of data points in the train set: 25694, number of used features: 77
[LightGBM] [Info] Start training from score -1.540601
[LightGBM] [Info] Start training from score -1.547893
[LightGBM] [Info] Start training from score -1.699333
[LightGBM] [Info] Start training from score -1.572344
[LightGBM] [Info] Start training from score -1.699972
Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.99      0.99      2425
           1       0.98      0.99      0.98      2316
           2       0.99      0.98      0.98      2015
           3       0.96      0.97      0.97      2253
           4       0.99      0.98      0.99      2004

    accuracy            

CatBoost

In [14]:
model = CatBoostClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Learning rate set to 0.093374
0:	learn: 1.4543872	total: 180ms	remaining: 2m 59s
1:	learn: 1.3379495	total: 215ms	remaining: 1m 47s
2:	learn: 1.2406783	total: 247ms	remaining: 1m 22s
3:	learn: 1.1662975	total: 282ms	remaining: 1m 10s
4:	learn: 1.1034544	total: 310ms	remaining: 1m 1s
5:	learn: 1.0466662	total: 341ms	remaining: 56.5s
6:	learn: 0.9940360	total: 374ms	remaining: 53.1s
7:	learn: 0.9515253	total: 405ms	remaining: 50.3s
8:	learn: 0.9150069	total: 433ms	remaining: 47.6s
9:	learn: 0.8797709	total: 460ms	remaining: 45.6s
10:	learn: 0.8468248	total: 492ms	remaining: 44.2s
11:	learn: 0.8159972	total: 521ms	remaining: 42.9s
12:	learn: 0.7883470	total: 551ms	remaining: 41.8s
13:	learn: 0.7657435	total: 579ms	remaining: 40.7s
14:	learn: 0.7405281	total: 609ms	remaining: 40s
15:	learn: 0.7180637	total: 639ms	remaining: 39.3s
16:	learn: 0.6971964	total: 669ms	remaining: 38.7s
17:	learn: 0.6784587	total: 698ms	remaining: 38.1s
18:	learn: 0.6610281	total: 726ms	remaining: 37.5s
19:	learn

C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


Gradient Boost

In [15]:
model = GradientBoostingClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.95      0.96      2425
           1       0.95      0.97      0.96      2316
           2       0.94      0.92      0.93      2015
           3       0.88      0.91      0.90      2253
           4       0.99      0.96      0.97      2004

    accuracy                           0.94     11013
   macro avg       0.94      0.94      0.94     11013
weighted avg       0.94      0.94      0.94     11013

Accuracy: 0.9422500681013348
Precision: 0.9422500681013348
Recall: 0.9422500681013348
F1-Score: 0.9422500681013348
AUC Score: 0.9636770928047687
MSE: 0.22627803504948696
G-Mean 0.9416288533996897
Kappa: 0.9276926598924178
MCC: 0.9277644375751458
Confusion Matrix:
 [[2310   16   11   85    3]
 [   5 2235   44   31    1]
 [  15   32 1859  106    3]
 [  45   75   58 2058   17]
 [  19    5   11   54 1915]]


SVM

In [16]:
model = SVC ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.76      0.71      0.73      2425
           1       0.73      0.86      0.79      2316
           2       0.68      0.46      0.55      2015
           3       0.62      0.88      0.73      2253
           4       0.86      0.64      0.73      2004

    accuracy                           0.72     11013
   macro avg       0.73      0.71      0.71     11013
weighted avg       0.73      0.72      0.71     11013

Accuracy: 0.7176064650867157
Precision: 0.7176064650867157
Recall: 0.7176064650867157
F1-Score: 0.7176064650867157
AUC Score: 0.8194367419543734
MSE: 1.271134114228639
G-Mean 0.6916467220981669
Kappa: 0.6454816877132834
MCC: 0.6516110016017815
Confusion Matrix:
 [[1714   80   83  496   52]
 [ 114 1993   68  115   26]
 [ 220  417  932  350   96]
 [  54  106   82 1983   28]
 [ 140  118  199  266 1281]]


KNN

In [17]:
X_train = np.array(X_train)
X_test = np.array(X_test)
model = KNeighborsClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.95      0.93      2425
           1       0.93      0.93      0.93      2316
           2       0.93      0.94      0.93      2015
           3       0.91      0.86      0.88      2253
           4       0.95      0.93      0.94      2004

    accuracy                           0.92     11013
   macro avg       0.92      0.92      0.92     11013
weighted avg       0.92      0.92      0.92     11013

Accuracy: 0.9224552801234904
Precision: 0.9224552801234904
Recall: 0.9224552801234904
F1-Score: 0.9224552801234904
AUC Score: 0.9514913433912356
MSE: 0.3868155815853991
G-Mean 0.9219299967642602
Kappa: 0.9029051546645267
MCC: 0.9030362736433604
Confusion Matrix:
 [[2305   23   13   65   19]
 [  41 2156   63   31   25]
 [  28   34 1899   39   15]
 [ 116   87   66 1945   39]
 [  47   27   10   66 1854]]


In [18]:
X_train = np.array(X_train)
X_test = np.array(X_test)
model = KNeighborsClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.95      0.93      2425
           1       0.93      0.93      0.93      2316
           2       0.93      0.94      0.93      2015
           3       0.91      0.86      0.88      2253
           4       0.95      0.93      0.94      2004

    accuracy                           0.92     11013
   macro avg       0.92      0.92      0.92     11013
weighted avg       0.92      0.92      0.92     11013

Accuracy: 0.9224552801234904
Precision: 0.9224552801234904
Recall: 0.9224552801234904
F1-Score: 0.9224552801234904
AUC Score: 0.9514913433912356
MSE: 0.3868155815853991
G-Mean 0.9219299967642602
Kappa: 0.9029051546645267
MCC: 0.9030362736433604
Confusion Matrix:
 [[2305   23   13   65   19]
 [  41 2156   63   31   25]
 [  28   34 1899   39   15]
 [ 116   87   66 1945   39]
 [  47   27   10   66 1854]]


Deep Learning

In [19]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from keras.utils import to_categorical
from numpy import argmax

ANN

In [31]:
num_classes = 5
model = Sequential()
model.add(Dense(128, activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(64, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

y_pred = model.predict(X_test)
y_pred2= argmax(y_pred, axis=1)
report(y_test, y_pred2)

Epoch 1/10
643/643 [==============================] - 2s 2ms/step - loss: 0.9512 - accuracy: 0.6840 - val_loss: 0.6003 - val_accuracy: 0.7727
Epoch 2/10
643/643 [==============================] - 1s 1ms/step - loss: 0.5718 - accuracy: 0.7969 - val_loss: 0.4963 - val_accuracy: 0.8188
Epoch 3/10
643/643 [==============================] - 1s 1ms/step - loss: 0.4877 - accuracy: 0.8312 - val_loss: 0.4316 - val_accuracy: 0.8418
Epoch 4/10
643/643 [==============================] - 1s 2ms/step - loss: 0.4118 - accuracy: 0.8566 - val_loss: 0.3489 - val_accuracy: 0.8831
Epoch 5/10
643/643 [==============================] - 1s 2ms/step - loss: 0.3874 - accuracy: 0.8662 - val_loss: 0.4654 - val_accuracy: 0.8268
Epoch 6/10
643/643 [==============================] - 1s 2ms/step - loss: 0.3789 - accuracy: 0.8711 - val_loss: 0.4596 - val_accuracy: 0.8424
Epoch 7/10
643/643 [==============================] - 1s 2ms/step - loss: 0.3473 - accuracy: 0.8811 - val_loss: 0.3405 - val_accuracy: 0.8797
Epoch 

CNN

In [21]:
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten

In [26]:
model = Sequential()
model.add(Conv1D(64, kernel_size=3, activation='relu', input_shape=(X_train.shape[1], 1)))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(num_classes, activation='softmax')) 

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

y_pred = model.predict (X_test)
y_pred2= argmax(y_pred, axis=1)
report(y_test, y_pred2)

Epoch 1/10
643/643 [==============================] - 3s 4ms/step - loss: 1.0375 - accuracy: 0.6584 - val_loss: 0.6982 - val_accuracy: 0.7410
Epoch 2/10
643/643 [==============================] - 2s 4ms/step - loss: 0.6214 - accuracy: 0.7746 - val_loss: 0.5254 - val_accuracy: 0.8046
Epoch 3/10
643/643 [==============================] - 2s 4ms/step - loss: 0.4830 - accuracy: 0.8280 - val_loss: 0.4227 - val_accuracy: 0.8490
Epoch 4/10
643/643 [==============================] - 2s 4ms/step - loss: 0.4264 - accuracy: 0.8521 - val_loss: 0.4409 - val_accuracy: 0.8362
Epoch 5/10
643/643 [==============================] - 2s 4ms/step - loss: 0.3899 - accuracy: 0.8607 - val_loss: 0.3623 - val_accuracy: 0.8745
Epoch 6/10
643/643 [==============================] - 2s 4ms/step - loss: 0.3590 - accuracy: 0.8748 - val_loss: 0.4050 - val_accuracy: 0.8474
Epoch 7/10
643/643 [==============================] - 2s 4ms/step - loss: 0.3428 - accuracy: 0.8789 - val_loss: 0.3135 - val_accuracy: 0.8930
Epoch 

RNN

In [27]:
from tensorflow.keras.layers import SimpleRNN

In [28]:
model = Sequential()
model.add(SimpleRNN(64, activation='relu', input_shape=(X_train.shape[1], 1)))
model.add(Dense(128, activation='relu'))
model.add(Dense(num_classes, activation='softmax')) 

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

y_pred = model.predict (X_test)
y_pred2= argmax(y_pred, axis=1)
report(y_test, y_pred2)

Epoch 1/10
643/643 [==============================] - 6s 7ms/step - loss: 1.0522 - accuracy: 0.5928 - val_loss: 0.8676 - val_accuracy: 0.6871
Epoch 2/10
643/643 [==============================] - 4s 7ms/step - loss: 0.7220 - accuracy: 0.7369 - val_loss: 0.6535 - val_accuracy: 0.7786
Epoch 3/10
643/643 [==============================] - 4s 7ms/step - loss: 0.6204 - accuracy: 0.7757 - val_loss: 0.6378 - val_accuracy: 0.7716
Epoch 4/10
643/643 [==============================] - 4s 7ms/step - loss: 0.5735 - accuracy: 0.7958 - val_loss: 0.5122 - val_accuracy: 0.8278
Epoch 5/10
643/643 [==============================] - 5s 7ms/step - loss: 0.5325 - accuracy: 0.8077 - val_loss: 0.4868 - val_accuracy: 0.8400
Epoch 6/10
643/643 [==============================] - 4s 7ms/step - loss: 0.5108 - accuracy: 0.8173 - val_loss: 0.5120 - val_accuracy: 0.8208
Epoch 7/10
643/643 [==============================] - 4s 7ms/step - loss: 0.4856 - accuracy: 0.8257 - val_loss: 0.5272 - val_accuracy: 0.8161
Epoch 

LSTM

In [29]:
from tensorflow.keras.layers import LSTM

In [30]:
model = Sequential()
model.add(LSTM(64, activation='relu', input_shape=(X_train.shape[1], 1)))
model.add(Dense(128, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

y_pred = model.predict (X_test)
y_pred2= argmax(y_pred, axis=1)
report(y_test, y_pred2)

Epoch 1/10
643/643 [==============================] - 13s 18ms/step - loss: 36.6609 - accuracy: 0.3325 - val_loss: 1.4408 - val_accuracy: 0.3839
Epoch 2/10
643/643 [==============================] - 11s 17ms/step - loss: 1.4164 - accuracy: 0.3628 - val_loss: 1.3896 - val_accuracy: 0.3779
Epoch 3/10
643/643 [==============================] - 11s 16ms/step - loss: 1.3817 - accuracy: 0.3757 - val_loss: 1.3665 - val_accuracy: 0.4112
Epoch 4/10
643/643 [==============================] - 11s 17ms/step - loss: 1.3632 - accuracy: 0.4018 - val_loss: 1.3534 - val_accuracy: 0.4337
Epoch 5/10
643/643 [==============================] - 11s 17ms/step - loss: 1.3517 - accuracy: 0.4270 - val_loss: 1.3404 - val_accuracy: 0.4297
Epoch 6/10
643/643 [==============================] - 11s 17ms/step - loss: 1.3430 - accuracy: 0.4405 - val_loss: 1.3340 - val_accuracy: 0.4606
Epoch 7/10
643/643 [==============================] - 11s 17ms/step - loss: 1.3351 - accuracy: 0.4487 - val_loss: 1.3247 - val_accuracy