Importing libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import math
from sklearn.metrics import confusion_matrix, roc_auc_score, mean_squared_error, cohen_kappa_score, matthews_corrcoef
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from sklearn.preprocessing import label_binarize
from imblearn.metrics import geometric_mean_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier



Reading dataset

In [2]:
df = pd.read_csv('Mendely_48.csv')
print (df.CLASS_LABEL.value_counts())
df.head()

CLASS_LABEL
1    5000
0    5000
Name: count, dtype: int64


NumDots  SubdomainLevel  PathLevel  UrlLength  NumDash  NumDashInHostname  \
0        3               1          5         72        0                  0   
1        3               1          3        144        0                  0   
2        3               1          2         58        0                  0   
3        3               1          6         79        1                  0   
4        3               0          4         46        0                  0   

   AtSymbol  TildeSymbol  NumUnderscore  NumPercent  ...  IframeOrFrame  \
0         0            0              0           0  ...              0   
1         0            0              2           0  ...              0   
2         0            0              0           0  ...              0   
3         0            0              0           0  ...              0   
4         0            0              0           0  ...              1   

   MissingTitle  ImagesOnlyInForm  SubdomainLevelRT  UrlLengthRT  \
0             0                 1                 1            0   
1             0                 0                 1           -1   
2             0                 0                 1            0   
3             0                 0                 1           -1   
4             0                 0                 1            1   

   PctExtResourceUrlsRT  AbnormalExtFormActionR  ExtMetaScriptLinkRT  \
0                     1                       1                   -1   
1                     1                       1                    1   
2                    -1                       1                   -1   
3                     1                       1                    1   
4                    -1                       0                   -1   

   PctExtNullSelfRedirectHyperlinksRT  CLASS_LABEL  
0                                   1            1  
1                                   1            1  
2                                   0            1  
3                                  -1            1  
4                                  -1            1  

[5 rows x 49 columns]

Data pre-processing

In [3]:
Label = LabelEncoder()
df['CLASS_LABEL'] = Label.fit_transform(df['CLASS_LABEL'])
print (df.CLASS_LABEL.value_counts())
df.head()

CLASS_LABEL
1    5000
0    5000
Name: count, dtype: int64


NumDots  SubdomainLevel  PathLevel  UrlLength  NumDash  NumDashInHostname  \
0        3               1          5         72        0                  0   
1        3               1          3        144        0                  0   
2        3               1          2         58        0                  0   
3        3               1          6         79        1                  0   
4        3               0          4         46        0                  0   

   AtSymbol  TildeSymbol  NumUnderscore  NumPercent  ...  IframeOrFrame  \
0         0            0              0           0  ...              0   
1         0            0              2           0  ...              0   
2         0            0              0           0  ...              0   
3         0            0              0           0  ...              0   
4         0            0              0           0  ...              1   

   MissingTitle  ImagesOnlyInForm  SubdomainLevelRT  UrlLengthRT  \
0             0                 1                 1            0   
1             0                 0                 1           -1   
2             0                 0                 1            0   
3             0                 0                 1           -1   
4             0                 0                 1            1   

   PctExtResourceUrlsRT  AbnormalExtFormActionR  ExtMetaScriptLinkRT  \
0                     1                       1                   -1   
1                     1                       1                    1   
2                    -1                       1                   -1   
3                     1                       1                    1   
4                    -1                       0                   -1   

   PctExtNullSelfRedirectHyperlinksRT  CLASS_LABEL  
0                                   1            1  
1                                   1            1  
2                                   0            1  
3                                  -1            1  
4                                  -1            1  

[5 rows x 49 columns]

Data Cleaning

In [4]:
# df = df.replace([np.inf, -np.inf], np.nan)
# df.fillna(0, inplace=True)
# print(df.max())
# print(df.min())
# df.head()

In [5]:
input = df.drop (['CLASS_LABEL'], axis='columns')
target = df.CLASS_LABEL
print(target.head())
input.head()

0    1
1    1
2    1
3    1
4    1
Name: CLASS_LABEL, dtype: int64


NumDots  SubdomainLevel  PathLevel  UrlLength  NumDash  NumDashInHostname  \
0        3               1          5         72        0                  0   
1        3               1          3        144        0                  0   
2        3               1          2         58        0                  0   
3        3               1          6         79        1                  0   
4        3               0          4         46        0                  0   

   AtSymbol  TildeSymbol  NumUnderscore  NumPercent  ...  SubmitInfoToEmail  \
0         0            0              0           0  ...                  0   
1         0            0              2           0  ...                  0   
2         0            0              0           0  ...                  0   
3         0            0              0           0  ...                  1   
4         0            0              0           0  ...                  0   

   IframeOrFrame  MissingTitle  ImagesOnlyInForm  SubdomainLevelRT  \
0              0             0                 1                 1   
1              0             0                 0                 1   
2              0             0                 0                 1   
3              0             0                 0                 1   
4              1             0                 0                 1   

   UrlLengthRT  PctExtResourceUrlsRT  AbnormalExtFormActionR  \
0            0                     1                       1   
1           -1                     1                       1   
2            0                    -1                       1   
3           -1                     1                       1   
4            1                    -1                       0   

   ExtMetaScriptLinkRT  PctExtNullSelfRedirectHyperlinksRT  
0                   -1                                   1  
1                    1                                   1  
2                   -1                                   0  
3                    1                                  -1  
4                   -1                                  -1  

[5 rows x 48 columns]

Data splitting

In [6]:
X_train, X_test, y_train, y_test = train_test_split(input, target, test_size=0.2)
print (len (X_test))
print (len (X_train))

2000
8000


In [7]:
def report (y_test, y_pred):
    n_classes = 2
    y_true_binary = label_binarize(y_test, classes=range(n_classes))
    y_pred_binary = label_binarize(y_pred, classes=range(n_classes))
    auc_score = roc_auc_score(y_true_binary, y_pred_binary, average='macro')

    report = classification_report(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    
    mse = mean_squared_error(y_test, y_pred)
    kappa = cohen_kappa_score(y_test, y_pred)
    mcc = matthews_corrcoef(y_test, y_pred)
    g_mean = geometric_mean_score(y_test, y_pred)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='micro')
    recall = recall_score(y_test, y_pred, average='micro')
    f1 = f1_score(y_test, y_pred, average='micro')

    print("Classification Report:\n", report)
    print("Accuracy:", accuracy)
    print("Precision:", precision)
    print("Recall:", recall)
    print("F1-Score:", f1)
    print("AUC Score:", auc_score)
    print("MSE:", mse)
    print("G-Mean", g_mean)
    print("Kappa:", kappa)
    print("MCC:", mcc)
    print("Confusion Matrix:\n", conf_matrix)


Logistic Regression

In [8]:
model = LogisticRegression ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.94      0.91      0.92       965
           1       0.92      0.94      0.93      1035

    accuracy                           0.93      2000
   macro avg       0.93      0.93      0.93      2000
weighted avg       0.93      0.93      0.93      2000

Accuracy: 0.9275
Precision: 0.9275
Recall: 0.9275
F1-Score: 0.9275
AUC Score: 0.9269379990488348
MSE: 0.0725
G-Mean 0.926798910967843
Kappa: 0.8546846657246224
MCC: 0.8549977266721391
Confusion Matrix:
 [[879  86]
 [ 59 976]]


C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Decision Tree

In [9]:
model = DecisionTreeClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.96      0.96       965
           1       0.97      0.97      0.97      1035

    accuracy                           0.96      2000
   macro avg       0.96      0.96      0.96      2000
weighted avg       0.96      0.96      0.96      2000

Accuracy: 0.9645
Precision: 0.9645
Recall: 0.9645
F1-Score: 0.9645
AUC Score: 0.9644739806262672
MSE: 0.0355
G-Mean 0.9644736941180101
Kappa: 0.9289154093371111
MCC: 0.9289158749025515
Confusion Matrix:
 [[930  35]
 [ 36 999]]


Naive Bayes

In [10]:
model = GaussianNB ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.77      0.95      0.85       965
           1       0.94      0.74      0.83      1035

    accuracy                           0.84      2000
   macro avg       0.86      0.84      0.84      2000
weighted avg       0.86      0.84      0.84      2000

Accuracy: 0.841
Precision: 0.841
Recall: 0.841
F1-Score: 0.841
AUC Score: 0.8445896222873019
MSE: 0.159
G-Mean 0.8383393977731673
Kappa: 0.684001848291076
MCC: 0.7003241802287492
Confusion Matrix:
 [[914  51]
 [267 768]]


Random Forest

In [11]:
model = RandomForestClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.98      0.98       965
           1       0.98      0.98      0.98      1035

    accuracy                           0.98      2000
   macro avg       0.98      0.98      0.98      2000
weighted avg       0.98      0.98      0.98      2000

Accuracy: 0.9825
Precision: 0.9825
Recall: 0.9825
F1-Score: 0.9825
AUC Score: 0.9824610147430602
MSE: 0.0175
G-Mean 0.9824603833213199
Kappa: 0.9649558443638985
MCC: 0.9649563280603306
Confusion Matrix:
 [[ 947   18]
 [  17 1018]]


LightBoost

In [12]:
model = LGBMClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

[LightGBM] [Info] Number of positive: 3965, number of negative: 4035
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010879 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1508
[LightGBM] [Info] Number of data points in the train set: 8000, number of used features: 44
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.495625 -> initscore=-0.017500
[LightGBM] [Info] Start training from score -0.017500
Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.98      0.98       965
           1       0.98      0.99      0.99      1035

    accuracy                           0.98      2000
   macro avg       0.99      0.98      0.98      2000
weighted avg       0.99      0.98      0.98      2000

Accuracy: 0.985
Precision: 0.985
Recall: 0.985
F1-Score: 0.985
AUC Score: 0.984946559535430

CatBoost

In [13]:
model = CatBoostClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Learning rate set to 0.025035
0:	learn: 0.6532927	total: 155ms	remaining: 2m 35s
1:	learn: 0.6196353	total: 165ms	remaining: 1m 22s
2:	learn: 0.5854114	total: 187ms	remaining: 1m 2s
3:	learn: 0.5511028	total: 205ms	remaining: 51.1s
4:	learn: 0.5227179	total: 222ms	remaining: 44.2s
5:	learn: 0.4955749	total: 235ms	remaining: 39s
6:	learn: 0.4700847	total: 248ms	remaining: 35.2s
7:	learn: 0.4457968	total: 260ms	remaining: 32.2s
8:	learn: 0.4261674	total: 270ms	remaining: 29.7s
9:	learn: 0.4069228	total: 284ms	remaining: 28.1s
10:	learn: 0.3888188	total: 295ms	remaining: 26.5s
11:	learn: 0.3715027	total: 308ms	remaining: 25.3s
12:	learn: 0.3548817	total: 315ms	remaining: 24s
13:	learn: 0.3399243	total: 328ms	remaining: 23.1s
14:	learn: 0.3265163	total: 338ms	remaining: 22.2s
15:	learn: 0.3140544	total: 350ms	remaining: 21.5s
16:	learn: 0.3008583	total: 361ms	remaining: 20.9s
17:	learn: 0.2902494	total: 372ms	remaining: 20.3s
18:	learn: 0.2802740	total: 383ms	remaining: 19.8s
19:	learn: 0.

Gradient Boost

In [14]:
model = GradientBoostingClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.97      0.97       965
           1       0.97      0.98      0.98      1035

    accuracy                           0.97      2000
   macro avg       0.98      0.97      0.97      2000
weighted avg       0.98      0.97      0.97      2000

Accuracy: 0.975
Precision: 0.975
Recall: 0.975
F1-Score: 0.975
AUC Score: 0.9748992515831895
MSE: 0.025
G-Mean 0.9748950019486252
Kappa: 0.9499316567114111
MCC: 0.9499392770454224
Confusion Matrix:
 [[ 938   27]
 [  23 1012]]


SVM

In [15]:
model = SVC ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.81      0.85       965
           1       0.84      0.91      0.87      1035

    accuracy                           0.86      2000
   macro avg       0.87      0.86      0.86      2000
weighted avg       0.86      0.86      0.86      2000

Accuracy: 0.8615
Precision: 0.8615
Recall: 0.8615
F1-Score: 0.8615
AUC Score: 0.8596655903481765
MSE: 0.1385
G-Mean 0.8580663963103814
Kappa: 0.7217338891958411
MCC: 0.72504317618695
Confusion Matrix:
 [[779 186]
 [ 91 944]]


KNN

In [16]:
X_train = np.array(X_train)
X_test = np.array(X_test)
model = KNeighborsClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.83      0.86       965
           1       0.85      0.90      0.87      1035

    accuracy                           0.87      2000
   macro avg       0.87      0.86      0.86      2000
weighted avg       0.87      0.87      0.87      2000

Accuracy: 0.8655
Precision: 0.8655
Recall: 0.8655
F1-Score: 0.8655
AUC Score: 0.8641610973442467
MSE: 0.1345
G-Mean 0.8633139672114244
Kappa: 0.7300362293387392
MCC: 0.7316921752658001
Confusion Matrix:
 [[797 168]
 [101 934]]


Deep Learning

In [17]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

ANN

In [18]:
model = Sequential()
model.add(Dense(128, activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(64, activation='relu'))
model.add(Dense(1, activation='sigmoid'))  # Adjust for multiclass

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

y_pred = model.predict (X_test)
y_pred_binary = (y_pred > 0.5).astype(int)
report (y_test, y_pred_binary)



Epoch 1/10


200/200 [==============================] - 3s 5ms/step - loss: 0.3826 - accuracy: 0.8411 - val_loss: 0.3462 - val_accuracy: 0.8469
Epoch 2/10
200/200 [==============================] - 1s 3ms/step - loss: 0.2211 - accuracy: 0.9164 - val_loss: 0.2178 - val_accuracy: 0.9119
Epoch 3/10
200/200 [==============================] - 1s 3ms/step - loss: 0.1796 - accuracy: 0.9375 - val_loss: 0.1914 - val_accuracy: 0.9131
Epoch 4/10
200/200 [==============================] - 1s 3ms/step - loss: 0.1736 - accuracy: 0.9397 - val_loss: 0.1965 - val_accuracy: 0.9300
Epoch 5/10
200/200 [==============================] - 1s 3ms/step - loss: 0.1601 - accuracy: 0.9420 - val_loss: 0.1542 - val_accuracy: 0.9362
Epoch 6/10
200/200 [==============================] - 1s 3ms/step - loss: 0.1847 - accuracy: 0.9359 - val_loss: 0.2689 - val_accuracy: 0.8994
Epoch 7/10
200/200 [==============================] - 1s 4ms/step - loss: 0.1593 - accuracy: 0.9434 - val_loss: 0.1644 - val_accuracy: 0.9406
Ep

C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


CNN

In [19]:
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten

In [20]:
model = Sequential()
model.add(Conv1D(64, kernel_size=3, activation='relu', input_shape=(X_train.shape[1], 1)))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation='sigmoid'))  # Adjust for multiclass

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

y_pred = model.predict (X_test)
y_pred_binary = (y_pred > 0.5).astype(int)
report (y_test, y_pred_binary)


Epoch 1/10
200/200 [==============================] - 2s 5ms/step - loss: 0.3784 - accuracy: 0.8509 - val_loss: 0.2487 - val_accuracy: 0.9081
Epoch 2/10
200/200 [==============================] - 1s 4ms/step - loss: 0.2282 - accuracy: 0.9172 - val_loss: 0.2059 - val_accuracy: 0.9294
Epoch 3/10
200/200 [==============================] - 1s 4ms/step - loss: 0.1911 - accuracy: 0.9367 - val_loss: 0.1690 - val_accuracy: 0.9362
Epoch 4/10
200/200 [==============================] - 1s 4ms/step - loss: 0.1744 - accuracy: 0.9391 - val_loss: 0.1436 - val_accuracy: 0.9419
Epoch 5/10
200/200 [==============================] - 1s 4ms/step - loss: 0.1493 - accuracy: 0.9494 - val_loss: 0.1487 - val_accuracy: 0.9431
Epoch 6/10
200/200 [==============================] - 1s 4ms/step - loss: 0.1430 - accuracy: 0.9498 - val_loss: 0.1461 - val_accuracy: 0.9356
Epoch 7/10
200/200 [==============================] - 1s 4ms/step - loss: 0.1536 - accuracy: 0.9425 - val_loss: 0.2039 - val_accuracy: 0.9250
Epoch

C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


RNN

In [21]:
from tensorflow.keras.layers import SimpleRNN

In [22]:
model = Sequential()
model.add(SimpleRNN(64, activation='relu', input_shape=(X_train.shape[1], 1)))
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation='sigmoid'))  # Adjust for multiclass

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

y_pred = model.predict (X_test)
y_pred_binary = (y_pred > 0.5).astype(int)
report (y_test, y_pred_binary)

Epoch 1/10
200/200 [==============================] - 4s 11ms/step - loss: 0.4313 - accuracy: 0.8033 - val_loss: 0.3577 - val_accuracy: 0.8531
Epoch 2/10
200/200 [==============================] - 2s 9ms/step - loss: 0.3059 - accuracy: 0.8703 - val_loss: 0.2907 - val_accuracy: 0.8744
Epoch 3/10
200/200 [==============================] - 2s 9ms/step - loss: 0.2730 - accuracy: 0.8881 - val_loss: 0.2688 - val_accuracy: 0.8850
Epoch 4/10
200/200 [==============================] - 2s 9ms/step - loss: 0.2454 - accuracy: 0.9034 - val_loss: 0.2713 - val_accuracy: 0.8744
Epoch 5/10
200/200 [==============================] - 2s 9ms/step - loss: 0.2454 - accuracy: 0.9045 - val_loss: 0.2339 - val_accuracy: 0.9013
Epoch 6/10
200/200 [==============================] - 2s 9ms/step - loss: 0.2200 - accuracy: 0.9170 - val_loss: 0.2222 - val_accuracy: 0.9069
Epoch 7/10
200/200 [==============================] - 2s 9ms/step - loss: 0.2116 - accuracy: 0.9241 - val_loss: 0.2160 - val_accuracy: 0.9150
Epoch

C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


LSTM

In [23]:
from tensorflow.keras.layers import LSTM

In [24]:
model = Sequential()
model.add(LSTM(64, activation='relu', input_shape=(X_train.shape[1], 1)))
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation='sigmoid'))  # Adjust for multiclass

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

y_pred = model.predict (X_test)
y_pred_binary = (y_pred > 0.5).astype(int)
report (y_test, y_pred_binary)

Epoch 1/10
200/200 [==============================] - 6s 16ms/step - loss: 17.8827 - accuracy: 0.7138 - val_loss: 0.5650 - val_accuracy: 0.7400
Epoch 2/10
200/200 [==============================] - 3s 14ms/step - loss: 0.5284 - accuracy: 0.7572 - val_loss: 0.5034 - val_accuracy: 0.7581
Epoch 3/10
200/200 [==============================] - 3s 14ms/step - loss: 0.4733 - accuracy: 0.7822 - val_loss: 0.4564 - val_accuracy: 0.7950
Epoch 4/10
200/200 [==============================] - 3s 14ms/step - loss: 0.4379 - accuracy: 0.8158 - val_loss: 0.4258 - val_accuracy: 0.8219
Epoch 5/10
200/200 [==============================] - 3s 13ms/step - loss: 0.4183 - accuracy: 0.8270 - val_loss: 0.4095 - val_accuracy: 0.8406
Epoch 6/10
200/200 [==============================] - 3s 15ms/step - loss: 0.4029 - accuracy: 0.8298 - val_loss: 0.3931 - val_accuracy: 0.8450
Epoch 7/10
200/200 [==============================] - 3s 14ms/step - loss: 0.3857 - accuracy: 0.8370 - val_loss: 0.4002 - val_accuracy: 0.839

C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
