Importing libraries

In [4]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import math
from sklearn.metrics import confusion_matrix, roc_auc_score, mean_squared_error, cohen_kappa_score, matthews_corrcoef
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from imblearn.metrics import geometric_mean_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier


Reading dataset

In [5]:
df = pd.read_csv('kaggle_2.csv')
print (df.status.value_counts())
df.head()

status
legitimate    5715
phishing      5715
Name: count, dtype: int64


url  length_url  \
0              http://www.crestonwood.com/router.php          37   
1  http://shadetreetechnology.com/V4/validation/a...          77   
2  https://support-appleld.com.secureupdate.duila...         126   
3                                 http://rgipt.ac.in          18   
4  http://www.iracing.com/tracks/gateway-motorspo...          55   

   length_hostname  ip  nb_dots  nb_hyphens  nb_at  nb_qm  nb_and  nb_or  ...  \
0               19   0        3           0      0      0       0      0  ...   
1               23   1        1           0      0      0       0      0  ...   
2               50   1        4           1      0      1       2      0  ...   
3               11   0        2           0      0      0       0      0  ...   
4               15   0        2           2      0      0       0      0  ...   

   domain_in_title  domain_with_copyright  whois_registered_domain  \
0                0                      1                        0   
1                1                      0                        0   
2                1                      0                        0   
3                1                      0                        0   
4                0                      1                        0   

   domain_registration_length  domain_age  web_traffic  dns_record  \
0                          45          -1            0           1   
1                          77        5767            0           0   
2                          14        4004      5828815           0   
3                          62          -1       107721           0   
4                         224        8175         8725           0   

   google_index  page_rank      status  
0             1          4  legitimate  
1             1          2    phishing  
2             1          0    phishing  
3             0          3  legitimate  
4             0          6  legitimate  

[5 rows x 89 columns]

data pre-processing

In [6]:
df = df.drop(['url'], axis='columns')
Label = LabelEncoder()
df['status'] = Label.fit_transform(df['status'])
print (df.status.value_counts())
df.head()

status
0    5715
1    5715
Name: count, dtype: int64


length_url  length_hostname  ip  nb_dots  nb_hyphens  nb_at  nb_qm  nb_and  \
0          37               19   0        3           0      0      0       0   
1          77               23   1        1           0      0      0       0   
2         126               50   1        4           1      0      1       2   
3          18               11   0        2           0      0      0       0   
4          55               15   0        2           2      0      0       0   

   nb_or  nb_eq  ...  domain_in_title  domain_with_copyright  \
0      0      0  ...                0                      1   
1      0      0  ...                1                      0   
2      0      3  ...                1                      0   
3      0      0  ...                1                      0   
4      0      0  ...                0                      1   

   whois_registered_domain  domain_registration_length  domain_age  \
0                        0                          45          -1   
1                        0                          77        5767   
2                        0                          14        4004   
3                        0                          62          -1   
4                        0                         224        8175   

   web_traffic  dns_record  google_index  page_rank  status  
0            0           1             1          4       0  
1            0           0             1          2       1  
2      5828815           0             1          0       1  
3       107721           0             0          3       0  
4         8725           0             0          6       0  

[5 rows x 88 columns]

In [7]:
input = df.drop (['status'], axis='columns')
target = df.status
print(target.head())
input.head()

0    0
1    1
2    1
3    0
4    0
Name: status, dtype: int32


length_url  length_hostname  ip  nb_dots  nb_hyphens  nb_at  nb_qm  nb_and  \
0          37               19   0        3           0      0      0       0   
1          77               23   1        1           0      0      0       0   
2         126               50   1        4           1      0      1       2   
3          18               11   0        2           0      0      0       0   
4          55               15   0        2           2      0      0       0   

   nb_or  nb_eq  ...  empty_title  domain_in_title  domain_with_copyright  \
0      0      0  ...            0                0                      1   
1      0      0  ...            0                1                      0   
2      0      3  ...            0                1                      0   
3      0      0  ...            0                1                      0   
4      0      0  ...            0                0                      1   

   whois_registered_domain  domain_registration_length  domain_age  \
0                        0                          45          -1   
1                        0                          77        5767   
2                        0                          14        4004   
3                        0                          62          -1   
4                        0                         224        8175   

   web_traffic  dns_record  google_index  page_rank  
0            0           1             1          4  
1            0           0             1          2  
2      5828815           0             1          0  
3       107721           0             0          3  
4         8725           0             0          6  

[5 rows x 87 columns]

Data splitting

In [8]:
X_train, X_test, y_train, y_test = train_test_split(input, target, test_size=0.3)
print (len (X_test))
print (len (X_train))

3429
8001


In [9]:
def report (y_test, y_pred):
    report = classification_report(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    auc_score = roc_auc_score(y_test, y_pred, multi_class='ovo')
    mse = mean_squared_error(y_test, y_pred)
    kappa = cohen_kappa_score(y_test, y_pred)
    mcc = matthews_corrcoef(y_test, y_pred)
    g_mean = geometric_mean_score(y_test, y_pred)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='micro')
    recall = recall_score(y_test, y_pred, average='micro')
    f1 = f1_score(y_test, y_pred, average='micro')

    print("Classification Report:\n", report)
    print("Accuracy:", accuracy)
    print("Precision:", precision)
    print("Recall:", recall)
    print("F1-Score:", f1)
    print("AUC Score:", auc_score)
    print("MSE:", mse)
    print("G-Mean", g_mean)
    print("Kappa:", kappa)
    print("MCC:", mcc)
    print("Confusion Matrix:\n", conf_matrix)


Logistic Regression

In [7]:
model = LogisticRegression ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.79      0.77      0.78      1728
           1       0.77      0.79      0.78      1701

    accuracy                           0.78      3429
   macro avg       0.78      0.78      0.78      3429
weighted avg       0.78      0.78      0.78      3429

Accuracy: 0.7809857101195684
Precision: 0.7809857101195684
Recall: 0.7809857101195684
F1-Score: 0.7809857101195684
AUC Score: 0.7810800631981186
MSE: 0.21901428988043162
G-Mean 0.7809881411697129
Kappa: 0.5620388015153255
MCC: 0.5622500376441574
Confusion Matrix:
 [[1329  399]
 [ 352 1349]]


C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Decision Tree

In [8]:
model = DecisionTreeClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.94      0.93      0.94      1728
           1       0.93      0.94      0.94      1701

    accuracy                           0.94      3429
   macro avg       0.94      0.94      0.94      3429
weighted avg       0.94      0.94      0.94      3429

Accuracy: 0.9364246135899679
Precision: 0.9364246135899679
Recall: 0.9364246135899679
F1-Score: 0.9364246135899679
AUC Score: 0.9364390432098766
MSE: 0.06357538641003208
G-Mean 0.9364372500949226
Kappa: 0.8728460153580483
MCC: 0.872855517940913
Confusion Matrix:
 [[1615  113]
 [ 105 1596]]


Naive Bayes

In [9]:
model = GaussianNB ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.59      0.70      1728
           1       0.68      0.88      0.77      1701

    accuracy                           0.74      3429
   macro avg       0.76      0.74      0.73      3429
weighted avg       0.76      0.74      0.73      3429

Accuracy: 0.7381160688247302
Precision: 0.7381160688247302
Recall: 0.7381160688247302
F1-Score: 0.7381160688247301
AUC Score: 0.7392618312757202
MSE: 0.26188393117526976
G-Mean 0.7247995323811389
Kappa: 0.47741415178203206
MCC: 0.49956347099459997
Confusion Matrix:
 [[1026  702]
 [ 196 1505]]


KNN

In [10]:
X_train = np.array(X_train)
X_test = np.array(X_test)
model = KNeighborsClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.81      0.82      1728
           1       0.81      0.84      0.83      1701

    accuracy                           0.82      3429
   macro avg       0.82      0.82      0.82      3429
weighted avg       0.82      0.82      0.82      3429

Accuracy: 0.8241469816272966
Precision: 0.8241469816272966
Recall: 0.8241469816272966
F1-Score: 0.8241469816272966
AUC Score: 0.8242486037624926
MSE: 0.17585301837270342
G-Mean 0.8241475569824259
Kappa: 0.6483512951321765
MCC: 0.6486161585810514
Confusion Matrix:
 [[1402  326]
 [ 277 1424]]


Random Forest

In [11]:
model = RandomForestClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.97      0.97      1728
           1       0.97      0.97      0.97      1701

    accuracy                           0.97      3429
   macro avg       0.97      0.97      0.97      3429
weighted avg       0.97      0.97      0.97      3429

Accuracy: 0.9667541557305337
Precision: 0.9667541557305337
Recall: 0.9667541557305337
F1-Score: 0.9667541557305337
AUC Score: 0.9667475014697237
MSE: 0.033245844269466314
G-Mean 0.9667471320976067
Kappa: 0.9335035778914783
MCC: 0.9335042131248126
Confusion Matrix:
 [[1672   56]
 [  58 1643]]


SVM

In [12]:
model = SVC ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.75      0.33      0.46      1728
           1       0.57      0.89      0.69      1701

    accuracy                           0.61      3429
   macro avg       0.66      0.61      0.57      3429
weighted avg       0.66      0.61      0.57      3429

Accuracy: 0.6062992125984252
Precision: 0.6062992125984252
Recall: 0.6062992125984252
F1-Score: 0.6062992125984252
AUC Score: 0.6085207231040564
MSE: 0.3937007874015748
G-Mean 0.5391651867187541
Kappa: 0.21607088968752575
MCC: 0.2625123331866507
Confusion Matrix:
 [[ 564 1164]
 [ 186 1515]]


Light Boost

In [13]:
model = LGBMClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

[LightGBM] [Info] Number of positive: 4014, number of negative: 3987
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001789 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4818
[LightGBM] [Info] Number of data points in the train set: 8001, number of used features: 72
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.501687 -> initscore=0.006749
[LightGBM] [Info] Start training from score 0.006749
Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.97      0.97      1728
           1       0.97      0.97      0.97      1701

    accuracy                           0.97      3429
   macro avg       0.97      0.97      0.97      3429
weighted avg       0.97      0.97      0.97      3429

Accuracy: 0.9687955672207641
Precision: 0.9687955672207641
Recall: 0.9687955672207641
F1-Scor

Cat Boost

In [14]:
model = CatBoostClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Learning rate set to 0.025037
0:	learn: 0.6534968	total: 150ms	remaining: 2m 29s
1:	learn: 0.6203327	total: 155ms	remaining: 1m 17s
2:	learn: 0.5920987	total: 161ms	remaining: 53.6s
3:	learn: 0.5630204	total: 166ms	remaining: 41.4s
4:	learn: 0.5364898	total: 171ms	remaining: 34.1s
5:	learn: 0.5141459	total: 177ms	remaining: 29.3s
6:	learn: 0.4911047	total: 182ms	remaining: 25.9s
7:	learn: 0.4692787	total: 187ms	remaining: 23.2s
8:	learn: 0.4494379	total: 194ms	remaining: 21.3s
9:	learn: 0.4299626	total: 200ms	remaining: 19.8s
10:	learn: 0.4125620	total: 206ms	remaining: 18.5s
11:	learn: 0.3965035	total: 212ms	remaining: 17.5s
12:	learn: 0.3820164	total: 217ms	remaining: 16.5s
13:	learn: 0.3685792	total: 223ms	remaining: 15.7s
14:	learn: 0.3572684	total: 228ms	remaining: 15s
15:	learn: 0.3446822	total: 233ms	remaining: 14.3s
16:	learn: 0.3345706	total: 237ms	remaining: 13.7s
17:	learn: 0.3231471	total: 243ms	remaining: 13.3s
18:	learn: 0.3144515	total: 248ms	remaining: 12.8s
19:	learn: 

Gradient Boost

In [15]:
model = GradientBoostingClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.96      0.96      1728
           1       0.96      0.95      0.96      1701

    accuracy                           0.96      3429
   macro avg       0.96      0.96      0.96      3429
weighted avg       0.96      0.96      0.96      3429

Accuracy: 0.9559638378536016
Precision: 0.9559638378536016
Recall: 0.9559638378536016
F1-Score: 0.9559638378536016
AUC Score: 0.9559220679012346
MSE: 0.04403616214639837
G-Mean 0.9559073486315552
Kappa: 0.9119153373049593
MCC: 0.9119601809697692
Confusion Matrix:
 [[1661   67]
 [  84 1617]]


Deep Learning

In [3]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

ANN

In [15]:
model = Sequential()
model.add(Dense(128, activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(64, activation='relu'))
model.add(Dense(1, activation='sigmoid'))  # Adjust for multiclass

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=12, batch_size=32, validation_split=0.2)

y_pred = model.predict (X_test)
y_pred_binary = (y_pred > 0.5).astype(int)
report (y_test, y_pred_binary)

Epoch 1/12
200/200 [==============================] - 1s 2ms/step - loss: 7220.6860 - accuracy: 0.6269 - val_loss: 2957.1218 - val_accuracy: 0.6871
Epoch 2/12
200/200 [==============================] - 0s 1ms/step - loss: 3658.8564 - accuracy: 0.6800 - val_loss: 695.5659 - val_accuracy: 0.7102
Epoch 3/12
200/200 [==============================] - 0s 2ms/step - loss: 3265.0300 - accuracy: 0.7078 - val_loss: 340.0854 - val_accuracy: 0.7495
Epoch 4/12
200/200 [==============================] - 0s 2ms/step - loss: 2227.6704 - accuracy: 0.7223 - val_loss: 6955.8003 - val_accuracy: 0.7770
Epoch 5/12
200/200 [==============================] - 0s 2ms/step - loss: 1682.1328 - accuracy: 0.7241 - val_loss: 1063.5768 - val_accuracy: 0.7920
Epoch 6/12
200/200 [==============================] - 0s 1ms/step - loss: 1558.4364 - accuracy: 0.7283 - val_loss: 551.0796 - val_accuracy: 0.7876
Epoch 7/12
200/200 [==============================] - 0s 1ms/step - loss: 1388.4758 - accuracy: 0.7444 - val_loss: 

C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


CNN

In [21]:
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten

In [32]:
model = Sequential()
model.add(Conv1D(64, kernel_size=3, activation='relu', input_shape=(X_train.shape[1], 1)))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation='sigmoid'))  # Adjust for multiclass

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=12, batch_size=32, validation_split=0.2)

y_pred = model.predict (X_test)
y_pred_binary = (y_pred > 0.5).astype(int)
report (y_test, y_pred_binary)

Epoch 1/12
200/200 [==============================] - 2s 5ms/step - loss: 5457.9624 - accuracy: 0.6450 - val_loss: 376.4083 - val_accuracy: 0.7477
Epoch 2/12
200/200 [==============================] - 1s 4ms/step - loss: 2829.5159 - accuracy: 0.7130 - val_loss: 1132.8625 - val_accuracy: 0.7458
Epoch 3/12
200/200 [==============================] - 1s 4ms/step - loss: 1945.8633 - accuracy: 0.7344 - val_loss: 722.4069 - val_accuracy: 0.7564
Epoch 4/12
200/200 [==============================] - 1s 4ms/step - loss: 1388.6194 - accuracy: 0.7505 - val_loss: 1176.2185 - val_accuracy: 0.7552
Epoch 5/12
200/200 [==============================] - 1s 4ms/step - loss: 1131.2872 - accuracy: 0.7431 - val_loss: 323.6787 - val_accuracy: 0.7608
Epoch 6/12
200/200 [==============================] - 1s 4ms/step - loss: 551.7150 - accuracy: 0.7664 - val_loss: 1135.3424 - val_accuracy: 0.7264
Epoch 7/12
200/200 [==============================] - 1s 4ms/step - loss: 669.0313 - accuracy: 0.7791 - val_loss: 18

C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


RNN

In [23]:
from tensorflow.keras.layers import SimpleRNN

In [34]:
model = Sequential()
model.add(SimpleRNN(64, activation='relu', input_shape=(X_train.shape[1], 1)))
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation='sigmoid'))  # Adjust for multiclass

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=12, batch_size=32, validation_split=0.2)

y_pred = model.predict (X_test)
y_pred_binary = (y_pred > 0.5).astype(int)
report (y_test, y_pred_binary)

Epoch 1/12
200/200 [==============================] - 3s 10ms/step - loss: 1098.2946 - accuracy: 0.5666 - val_loss: 112.7338 - val_accuracy: 0.7464
Epoch 2/12
200/200 [==============================] - 2s 9ms/step - loss: 167.2603 - accuracy: 0.6837 - val_loss: 281.2392 - val_accuracy: 0.5809
Epoch 3/12
200/200 [==============================] - 2s 9ms/step - loss: 149.4851 - accuracy: 0.6806 - val_loss: 304.7345 - val_accuracy: 0.7676
Epoch 4/12
200/200 [==============================] - 2s 9ms/step - loss: 99.3640 - accuracy: 0.6675 - val_loss: 46.0650 - val_accuracy: 0.7589
Epoch 5/12
200/200 [==============================] - 2s 10ms/step - loss: 68.3099 - accuracy: 0.6780 - val_loss: 20.2265 - val_accuracy: 0.6758
Epoch 6/12
200/200 [==============================] - 2s 9ms/step - loss: 48.1617 - accuracy: 0.6722 - val_loss: 20.7994 - val_accuracy: 0.7289
Epoch 7/12
200/200 [==============================] - 2s 9ms/step - loss: 34.2355 - accuracy: 0.6966 - val_loss: 4.0268 - val_a

C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


LSTM

In [25]:
from tensorflow.keras.layers import LSTM

In [26]:
model = Sequential()
model.add(LSTM(64, activation='relu', input_shape=(X_train.shape[1], 1)))
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation='sigmoid'))  # Adjust for multiclass

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

y_pred = model.predict (X_test)
y_pred_binary = (y_pred > 0.5).astype(int)
report (y_test, y_pred_binary)

Epoch 1/10
200/200 [==============================] - 5s 17ms/step - loss: 147.2474 - accuracy: 0.6097 - val_loss: 112.6267 - val_accuracy: 0.6471
Epoch 2/10
200/200 [==============================] - 3s 16ms/step - loss: 74.2823 - accuracy: 0.6005 - val_loss: 52.0792 - val_accuracy: 0.5134
Epoch 3/10
200/200 [==============================] - 3s 17ms/step - loss: 77.2799 - accuracy: 0.6111 - val_loss: 41.9811 - val_accuracy: 0.7027
Epoch 4/10
200/200 [==============================] - 3s 16ms/step - loss: 17.0045 - accuracy: 0.6502 - val_loss: 8.7931 - val_accuracy: 0.6327
Epoch 5/10
200/200 [==============================] - 3s 16ms/step - loss: 8.2959 - accuracy: 0.6780 - val_loss: 2.0256 - val_accuracy: 0.7308
Epoch 6/10
200/200 [==============================] - 3s 16ms/step - loss: 4.6490 - accuracy: 0.7373 - val_loss: 3.8810 - val_accuracy: 0.7589
Epoch 7/10
200/200 [==============================] - 3s 16ms/step - loss: 59.5919 - accuracy: 0.7170 - val_loss: 478.2149 - val_accu

C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
