Importing libraries

In [16]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import math
from sklearn.metrics import confusion_matrix, roc_auc_score, mean_squared_error, cohen_kappa_score, matthews_corrcoef
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from imblearn.metrics import geometric_mean_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier


Reading dataset

In [17]:
df = pd.read_csv('kaggle_2.csv')
print (df.status.value_counts())
df.head()

status
legitimate    5715
phishing      5715
Name: count, dtype: int64


url  length_url  \
0              http://www.crestonwood.com/router.php          37   
1  http://shadetreetechnology.com/V4/validation/a...          77   
2  https://support-appleld.com.secureupdate.duila...         126   
3                                 http://rgipt.ac.in          18   
4  http://www.iracing.com/tracks/gateway-motorspo...          55   

   length_hostname  ip  nb_dots  nb_hyphens  nb_at  nb_qm  nb_and  nb_or  ...  \
0               19   0        3           0      0      0       0      0  ...   
1               23   1        1           0      0      0       0      0  ...   
2               50   1        4           1      0      1       2      0  ...   
3               11   0        2           0      0      0       0      0  ...   
4               15   0        2           2      0      0       0      0  ...   

   domain_in_title  domain_with_copyright  whois_registered_domain  \
0                0                      1                        0   
1                1                      0                        0   
2                1                      0                        0   
3                1                      0                        0   
4                0                      1                        0   

   domain_registration_length  domain_age  web_traffic  dns_record  \
0                          45          -1            0           1   
1                          77        5767            0           0   
2                          14        4004      5828815           0   
3                          62          -1       107721           0   
4                         224        8175         8725           0   

   google_index  page_rank      status  
0             1          4  legitimate  
1             1          2    phishing  
2             1          0    phishing  
3             0          3  legitimate  
4             0          6  legitimate  

[5 rows x 89 columns]

data pre-processing

In [18]:
df = df.drop(['url'], axis='columns')
Label = LabelEncoder()
df['status'] = Label.fit_transform(df['status'])
print (df.status.value_counts())
df.head()

status
0    5715
1    5715
Name: count, dtype: int64


length_url  length_hostname  ip  nb_dots  nb_hyphens  nb_at  nb_qm  nb_and  \
0          37               19   0        3           0      0      0       0   
1          77               23   1        1           0      0      0       0   
2         126               50   1        4           1      0      1       2   
3          18               11   0        2           0      0      0       0   
4          55               15   0        2           2      0      0       0   

   nb_or  nb_eq  ...  domain_in_title  domain_with_copyright  \
0      0      0  ...                0                      1   
1      0      0  ...                1                      0   
2      0      3  ...                1                      0   
3      0      0  ...                1                      0   
4      0      0  ...                0                      1   

   whois_registered_domain  domain_registration_length  domain_age  \
0                        0                          45          -1   
1                        0                          77        5767   
2                        0                          14        4004   
3                        0                          62          -1   
4                        0                         224        8175   

   web_traffic  dns_record  google_index  page_rank  status  
0            0           1             1          4       0  
1            0           0             1          2       1  
2      5828815           0             1          0       1  
3       107721           0             0          3       0  
4         8725           0             0          6       0  

[5 rows x 88 columns]

In [19]:
input = df.drop (['status'], axis='columns')
target = df.status
print(target.head())
input.head()

0    0
1    1
2    1
3    0
4    0
Name: status, dtype: int32


length_url  length_hostname  ip  nb_dots  nb_hyphens  nb_at  nb_qm  nb_and  \
0          37               19   0        3           0      0      0       0   
1          77               23   1        1           0      0      0       0   
2         126               50   1        4           1      0      1       2   
3          18               11   0        2           0      0      0       0   
4          55               15   0        2           2      0      0       0   

   nb_or  nb_eq  ...  empty_title  domain_in_title  domain_with_copyright  \
0      0      0  ...            0                0                      1   
1      0      0  ...            0                1                      0   
2      0      3  ...            0                1                      0   
3      0      0  ...            0                1                      0   
4      0      0  ...            0                0                      1   

   whois_registered_domain  domain_registration_length  domain_age  \
0                        0                          45          -1   
1                        0                          77        5767   
2                        0                          14        4004   
3                        0                          62          -1   
4                        0                         224        8175   

   web_traffic  dns_record  google_index  page_rank  
0            0           1             1          4  
1            0           0             1          2  
2      5828815           0             1          0  
3       107721           0             0          3  
4         8725           0             0          6  

[5 rows x 87 columns]

Data splitting

In [20]:
X_train, X_test, y_train, y_test = train_test_split(input, target, test_size=0.3)
print (len (X_test))
print (len (X_train))

3429
8001


In [21]:
def report (y_test, y_pred):
    report = classification_report(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    auc_score = roc_auc_score(y_test, y_pred, multi_class='ovo')
    mse = mean_squared_error(y_test, y_pred)
    kappa = cohen_kappa_score(y_test, y_pred)
    mcc = matthews_corrcoef(y_test, y_pred)
    g_mean = geometric_mean_score(y_test, y_pred)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='micro')
    recall = recall_score(y_test, y_pred, average='micro')
    f1 = f1_score(y_test, y_pred, average='micro')

    print("Classification Report:\n", report)
    print("Accuracy:", accuracy)
    print("Precision:", precision)
    print("Recall:", recall)
    print("F1-Score:", f1)
    print("AUC Score:", auc_score)
    print("MSE:", mse)
    print("G-Mean", g_mean)
    print("Kappa:", kappa)
    print("MCC:", mcc)
    print("Confusion Matrix:\n", conf_matrix)


Logistic Regression

In [22]:
model = LogisticRegression ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.79      0.75      0.77      1749
           1       0.76      0.79      0.77      1680

    accuracy                           0.77      3429
   macro avg       0.77      0.77      0.77      3429
weighted avg       0.77      0.77      0.77      3429

Accuracy: 0.7719451735199767
Precision: 0.7719451735199767
Recall: 0.7719451735199767
F1-Score: 0.7719451735199767
AUC Score: 0.7723107081597647
MSE: 0.22805482648002334
G-Mean 0.7720970438943857
Kappa: 0.5441230923651764
MCC: 0.5446864862837085
Confusion Matrix:
 [[1319  430]
 [ 352 1328]]


Decision Tree

In [23]:
model = DecisionTreeClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.94      0.94      0.94      1749
           1       0.94      0.94      0.94      1680

    accuracy                           0.94      3429
   macro avg       0.94      0.94      0.94      3429
weighted avg       0.94      0.94      0.94      3429

Accuracy: 0.9393409157188685
Precision: 0.9393409157188685
Recall: 0.9393409157188685
F1-Score: 0.9393409157188685
AUC Score: 0.9393515682430778
MSE: 0.06065908428113152
G-Mean 0.9393514190723108
Kappa: 0.8786412375996545
MCC: 0.8786466215827438
Confusion Matrix:
 [[1642  107]
 [ 101 1579]]


Naive Bayes

In [24]:
model = GaussianNB ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.61      0.71      1749
           1       0.68      0.88      0.77      1680

    accuracy                           0.74      3429
   macro avg       0.76      0.74      0.74      3429
weighted avg       0.76      0.74      0.74      3429

Accuracy: 0.742198891805191
Precision: 0.742198891805191
Recall: 0.742198891805191
F1-Score: 0.7421988918051909
AUC Score: 0.7449476231315852
MSE: 0.257801108194809
G-Mean 0.7323164632350813
Kappa: 0.48711560776383234
MCC: 0.5077171919839525
Confusion Matrix:
 [[1064  685]
 [ 199 1481]]


Random Forest

In [25]:
model = RandomForestClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.96      0.96      1749
           1       0.96      0.96      0.96      1680

    accuracy                           0.96      3429
   macro avg       0.96      0.96      0.96      3429
weighted avg       0.96      0.96      0.96      3429

Accuracy: 0.9606299212598425
Precision: 0.9606299212598425
Recall: 0.9606299212598425
F1-Score: 0.9606299212598425
AUC Score: 0.9605963611859838
MSE: 0.03937007874015748
G-Mean 0.9605949133745599
Kappa: 0.9212251718006484
MCC: 0.921226583319558
Confusion Matrix:
 [[1683   66]
 [  69 1611]]


SVM

In [26]:
model = SVC ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.73      0.32      0.44      1749
           1       0.55      0.88      0.68      1680

    accuracy                           0.59      3429
   macro avg       0.64      0.60      0.56      3429
weighted avg       0.64      0.59      0.56      3429

Accuracy: 0.5925925925925926
Precision: 0.5925925925925926
Recall: 0.5925925925925926
F1-Score: 0.5925925925925926
AUC Score: 0.5982102017479376
MSE: 0.4074074074074074
G-Mean 0.5290738487832367
Kappa: 0.1941747180847171
MCC: 0.23596134253783896
Confusion Matrix:
 [[ 558 1191]
 [ 206 1474]]


Light Boost

In [27]:
model = LGBMClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

[LightGBM] [Info] Number of positive: 4035, number of negative: 3966
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002571 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4834
[LightGBM] [Info] Number of data points in the train set: 8001, number of used features: 72
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.504312 -> initscore=0.017248
[LightGBM] [Info] Start training from score 0.017248
Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.97      0.97      1749
           1       0.97      0.97      0.97      1680

    accuracy                           0.97      3429
   macro avg       0.97      0.97      0.97      3429
weighted avg       0.97      0.97      0.97      3429

Accuracy: 0.9673374161563137
Precision: 0.9673374161563137
Recall: 0.9673374161563137
F1-Score: 0.9673374161563137
AUC Score: 0.967300702442212
MSE: 0.032662

Cat Boost

In [28]:
model = CatBoostClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Learning rate set to 0.025037
0:	learn: 0.6595303	total: 17.1ms	remaining: 17.1s
1:	learn: 0.6253246	total: 23.5ms	remaining: 11.7s
2:	learn: 0.5945843	total: 30.7ms	remaining: 10.2s
3:	learn: 0.5651566	total: 36.8ms	remaining: 9.15s
4:	learn: 0.5409401	total: 43.7ms	remaining: 8.69s
5:	learn: 0.5155954	total: 50.1ms	remaining: 8.3s
6:	learn: 0.4891982	total: 55.8ms	remaining: 7.91s
7:	learn: 0.4684730	total: 62.4ms	remaining: 7.73s
8:	learn: 0.4491289	total: 68ms	remaining: 7.49s
9:	learn: 0.4321990	total: 73.8ms	remaining: 7.31s
10:	learn: 0.4153547	total: 80.4ms	remaining: 7.23s
11:	learn: 0.4011168	total: 86.1ms	remaining: 7.09s
12:	learn: 0.3882270	total: 91.8ms	remaining: 6.97s
13:	learn: 0.3727488	total: 98ms	remaining: 6.9s
14:	learn: 0.3585932	total: 104ms	remaining: 6.8s
15:	learn: 0.3483899	total: 110ms	remaining: 6.75s
16:	learn: 0.3370761	total: 115ms	remaining: 6.68s
17:	learn: 0.3269926	total: 121ms	remaining: 6.6s
18:	learn: 0.3163752	total: 127ms	remaining: 6.56s
19:	l

Gradient Boost

In [29]:
model = GradientBoostingClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.96      0.96      1749
           1       0.96      0.95      0.96      1680

    accuracy                           0.96      3429
   macro avg       0.96      0.96      0.96      3429
weighted avg       0.96      0.96      0.96      3429

Accuracy: 0.9565470982793818
Precision: 0.9565470982793818
Recall: 0.9565470982793818
F1-Score: 0.9565470982793818
AUC Score: 0.9564179531160663
MSE: 0.043452901720618255
G-Mean 0.9563964193369432
Kappa: 0.9130395931870369
MCC: 0.9130957338400465
Confusion Matrix:
 [[1684   65]
 [  84 1596]]
