Importing libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import math
from sklearn.metrics import confusion_matrix, roc_auc_score, mean_squared_error, cohen_kappa_score, matthews_corrcoef
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from imblearn.metrics import geometric_mean_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier


Reading dataset

In [2]:
df = pd.read_csv('kaggle_2.csv')
print (df.status.value_counts())
df.head()

status
legitimate    5715
phishing      5715
Name: count, dtype: int64


url  length_url  \
0              http://www.crestonwood.com/router.php          37   
1  http://shadetreetechnology.com/V4/validation/a...          77   
2  https://support-appleld.com.secureupdate.duila...         126   
3                                 http://rgipt.ac.in          18   
4  http://www.iracing.com/tracks/gateway-motorspo...          55   

   length_hostname  ip  nb_dots  nb_hyphens  nb_at  nb_qm  nb_and  nb_or  ...  \
0               19   0        3           0      0      0       0      0  ...   
1               23   1        1           0      0      0       0      0  ...   
2               50   1        4           1      0      1       2      0  ...   
3               11   0        2           0      0      0       0      0  ...   
4               15   0        2           2      0      0       0      0  ...   

   domain_in_title  domain_with_copyright  whois_registered_domain  \
0                0                      1                        0   
1                1                      0                        0   
2                1                      0                        0   
3                1                      0                        0   
4                0                      1                        0   

   domain_registration_length  domain_age  web_traffic  dns_record  \
0                          45          -1            0           1   
1                          77        5767            0           0   
2                          14        4004      5828815           0   
3                          62          -1       107721           0   
4                         224        8175         8725           0   

   google_index  page_rank      status  
0             1          4  legitimate  
1             1          2    phishing  
2             1          0    phishing  
3             0          3  legitimate  
4             0          6  legitimate  

[5 rows x 89 columns]

data pre-processing

In [3]:
df = df.drop(['url'], axis='columns')
Label = LabelEncoder()
df['status'] = Label.fit_transform(df['status'])
print (df.status.value_counts())
df.head()

status
0    5715
1    5715
Name: count, dtype: int64


length_url  length_hostname  ip  nb_dots  nb_hyphens  nb_at  nb_qm  nb_and  \
0          37               19   0        3           0      0      0       0   
1          77               23   1        1           0      0      0       0   
2         126               50   1        4           1      0      1       2   
3          18               11   0        2           0      0      0       0   
4          55               15   0        2           2      0      0       0   

   nb_or  nb_eq  ...  domain_in_title  domain_with_copyright  \
0      0      0  ...                0                      1   
1      0      0  ...                1                      0   
2      0      3  ...                1                      0   
3      0      0  ...                1                      0   
4      0      0  ...                0                      1   

   whois_registered_domain  domain_registration_length  domain_age  \
0                        0                          45          -1   
1                        0                          77        5767   
2                        0                          14        4004   
3                        0                          62          -1   
4                        0                         224        8175   

   web_traffic  dns_record  google_index  page_rank  status  
0            0           1             1          4       0  
1            0           0             1          2       1  
2      5828815           0             1          0       1  
3       107721           0             0          3       0  
4         8725           0             0          6       0  

[5 rows x 88 columns]

In [4]:
input = df.drop (['status'], axis='columns')
target = df.status
print(target.head())
input.head()

0    0
1    1
2    1
3    0
4    0
Name: status, dtype: int32


length_url  length_hostname  ip  nb_dots  nb_hyphens  nb_at  nb_qm  nb_and  \
0          37               19   0        3           0      0      0       0   
1          77               23   1        1           0      0      0       0   
2         126               50   1        4           1      0      1       2   
3          18               11   0        2           0      0      0       0   
4          55               15   0        2           2      0      0       0   

   nb_or  nb_eq  ...  empty_title  domain_in_title  domain_with_copyright  \
0      0      0  ...            0                0                      1   
1      0      0  ...            0                1                      0   
2      0      3  ...            0                1                      0   
3      0      0  ...            0                1                      0   
4      0      0  ...            0                0                      1   

   whois_registered_domain  domain_registration_length  domain_age  \
0                        0                          45          -1   
1                        0                          77        5767   
2                        0                          14        4004   
3                        0                          62          -1   
4                        0                         224        8175   

   web_traffic  dns_record  google_index  page_rank  
0            0           1             1          4  
1            0           0             1          2  
2      5828815           0             1          0  
3       107721           0             0          3  
4         8725           0             0          6  

[5 rows x 87 columns]

Data splitting

In [5]:
X_train, X_test, y_train, y_test = train_test_split(input, target, test_size=0.2)
print (len (X_test))
print (len (X_train))

2286
9144


In [6]:
def report (y_test, y_pred):
    report = classification_report(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    auc_score = roc_auc_score(y_test, y_pred, multi_class='ovo')
    mse = mean_squared_error(y_test, y_pred)
    kappa = cohen_kappa_score(y_test, y_pred)
    mcc = matthews_corrcoef(y_test, y_pred)
    g_mean = geometric_mean_score(y_test, y_pred)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='micro')
    recall = recall_score(y_test, y_pred, average='micro')
    f1 = f1_score(y_test, y_pred, average='micro')

    print("Classification Report:\n", report)
    print("Accuracy:", accuracy)
    print("Precision:", precision)
    print("Recall:", recall)
    print("F1-Score:", f1)
    print("AUC Score:", auc_score)
    print("MSE:", mse)
    print("G-Mean", g_mean)
    print("Kappa:", kappa)
    print("MCC:", mcc)
    print("Confusion Matrix:\n", conf_matrix)


Logistic Regression

In [7]:
model = LogisticRegression ()
model.fit (X_train, y_train)
print (model.get_params())
y_pred = model.predict (X_test)
report (y_test, y_pred)

{'C': 1.0, 'class_weight': None, 'dual': False, 'fit_intercept': True, 'intercept_scaling': 1, 'l1_ratio': None, 'max_iter': 100, 'multi_class': 'auto', 'n_jobs': None, 'penalty': 'l2', 'random_state': None, 'solver': 'lbfgs', 'tol': 0.0001, 'verbose': 0, 'warm_start': False}
Classification Report:
               precision    recall  f1-score   support

           0       0.78      0.76      0.77      1154
           1       0.76      0.78      0.77      1132

    accuracy                           0.77      2286
   macro avg       0.77      0.77      0.77      2286
weighted avg       0.77      0.77      0.77      2286

Accuracy: 0.773403324584427
Precision: 0.773403324584427
Recall: 0.773403324584427
F1-Score: 0.773403324584427
AUC Score: 0.7735002235273225
MSE: 0.22659667541557305
G-Mean 0.7734346885538574
Kappa: 0.5468715082088661
MCC: 0.547035623878444
Confusion Matrix:
 [[881 273]
 [245 887]]


C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Decision Tree

In [8]:
model = DecisionTreeClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.92      0.94      1154
           1       0.92      0.95      0.94      1132

    accuracy                           0.94      2286
   macro avg       0.94      0.94      0.94      2286
weighted avg       0.94      0.94      0.94      2286

Accuracy: 0.9352580927384077
Precision: 0.9352580927384077
Recall: 0.9352580927384077
F1-Score: 0.9352580927384077
AUC Score: 0.9353699836488233
MSE: 0.0647419072615923
G-Mean 0.9352977232995456
Kappa: 0.8705347166311046
MCC: 0.8707959633513416
Confusion Matrix:
 [[1066   88]
 [  60 1072]]


Naive Bayes

In [9]:
model = GaussianNB ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.63      0.71      1154
           1       0.69      0.86      0.77      1132

    accuracy                           0.74      2286
   macro avg       0.75      0.74      0.74      2286
weighted avg       0.76      0.74      0.74      2286

Accuracy: 0.7414698162729659
Precision: 0.7414698162729659
Recall: 0.7414698162729659
F1-Score: 0.7414698162729659
AUC Score: 0.7425531719445652
MSE: 0.2585301837270341
G-Mean 0.7339707725970226
Kappa: 0.4840343990815912
MCC: 0.497321363962026
Confusion Matrix:
 [[727 427]
 [164 968]]


KNN

In [10]:
X_train = np.array(X_train)
X_test = np.array(X_test)
model = KNeighborsClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.82      0.83      1154
           1       0.82      0.84      0.83      1132

    accuracy                           0.83      2286
   macro avg       0.83      0.83      0.83      2286
weighted avg       0.83      0.83      0.83      2286

Accuracy: 0.8333333333333334
Precision: 0.8333333333333334
Recall: 0.8333333333333334
F1-Score: 0.8333333333333334
AUC Score: 0.8334399936310023
MSE: 0.16666666666666666
G-Mean 0.8333663004096068
Kappa: 0.6667171776309899
MCC: 0.6669318090163201
Confusion Matrix:
 [[949 205]
 [176 956]]


Random Forest

In [11]:
model = RandomForestClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.96      0.97      1154
           1       0.96      0.98      0.97      1132

    accuracy                           0.97      2286
   macro avg       0.97      0.97      0.97      2286
weighted avg       0.97      0.97      0.97      2286

Accuracy: 0.9663167104111986
Precision: 0.9663167104111986
Recall: 0.9663167104111986
F1-Score: 0.9663167104111986
AUC Score: 0.966402006234269
MSE: 0.0336832895888014
G-Mean 0.9663613634049885
Kappa: 0.9326390924558324
MCC: 0.9327965148691263
Confusion Matrix:
 [[1105   49]
 [  28 1104]]


SVM

In [12]:
model = SVC ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.71      0.29      0.41      1154
           1       0.55      0.88      0.68      1132

    accuracy                           0.58      2286
   macro avg       0.63      0.59      0.54      2286
weighted avg       0.63      0.58      0.54      2286

Accuracy: 0.5822397200349956
Precision: 0.5822397200349956
Recall: 0.5822397200349956
F1-Score: 0.5822397200349956
AUC Score: 0.585051380663968
MSE: 0.41776027996500437
G-Mean 0.5068819852727229
Kappa: 0.16913855112176734
MCC: 0.20929507484137233
Confusion Matrix:
 [[338 816]
 [139 993]]


Light Boost

In [13]:
model = LGBMClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

[LightGBM] [Info] Number of positive: 4583, number of negative: 4561
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.013606 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4891
[LightGBM] [Info] Number of data points in the train set: 9144, number of used features: 74
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.501203 -> initscore=0.004812
[LightGBM] [Info] Start training from score 0.004812
Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.97      0.97      1154
           1       0.97      0.98      0.97      1132

    accuracy                           0.97      2286
   macro avg       0.97      0.97      0.97      2286
weighted avg       0.97      0.97      0.97      2286

Accuracy: 0.9724409448818898
Precision: 0.9724409448818898
Recall: 0.9724409448818898
F1-Score: 0.9724409448818898
AUC Score: 0.9725015463191479
MSE: 0.02755

Cat Boost

In [14]:
model = CatBoostClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Learning rate set to 0.026506
0:	learn: 0.6566286	total: 161ms	remaining: 2m 41s
1:	learn: 0.6253991	total: 187ms	remaining: 1m 33s
2:	learn: 0.5944589	total: 205ms	remaining: 1m 8s
3:	learn: 0.5621414	total: 226ms	remaining: 56.3s
4:	learn: 0.5346694	total: 243ms	remaining: 48.4s
5:	learn: 0.5089243	total: 262ms	remaining: 43.4s
6:	learn: 0.4836444	total: 277ms	remaining: 39.3s
7:	learn: 0.4614161	total: 290ms	remaining: 36s
8:	learn: 0.4415573	total: 307ms	remaining: 33.9s
9:	learn: 0.4214909	total: 321ms	remaining: 31.8s
10:	learn: 0.4031077	total: 334ms	remaining: 30.1s
11:	learn: 0.3895153	total: 348ms	remaining: 28.7s
12:	learn: 0.3756334	total: 362ms	remaining: 27.5s
13:	learn: 0.3627144	total: 377ms	remaining: 26.5s
14:	learn: 0.3502041	total: 385ms	remaining: 25.3s
15:	learn: 0.3369802	total: 399ms	remaining: 24.5s
16:	learn: 0.3276677	total: 412ms	remaining: 23.8s
17:	learn: 0.3184710	total: 423ms	remaining: 23.1s
18:	learn: 0.3088853	total: 436ms	remaining: 22.5s
19:	learn: 

Gradient Boost

In [15]:
model = GradientBoostingClassifier ()
model.fit (X_train, y_train)
y_pred = model.predict (X_test)
report (y_test, y_pred)

Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.95      0.96      1154
           1       0.95      0.97      0.96      1132

    accuracy                           0.96      2286
   macro avg       0.96      0.96      0.96      2286
weighted avg       0.96      0.96      0.96      2286

Accuracy: 0.9619422572178478
Precision: 0.9619422572178478
Recall: 0.9619422572178478
F1-Score: 0.9619422572178478
AUC Score: 0.9620103067529748
MSE: 0.03805774278215223
G-Mean 0.9619843199076733
Kappa: 0.9238883594907061
MCC: 0.923990552939443
Confusion Matrix:
 [[1102   52]
 [  35 1097]]


Deep Learning

In [16]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

ANN

In [17]:
model = Sequential()
model.add(Dense(128, activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(64, activation='relu'))
model.add(Dense(1, activation='sigmoid'))  # Adjust for multiclass

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=12, batch_size=32, validation_split=0.2)

y_pred = model.predict (X_test)
y_pred_binary = (y_pred > 0.5).astype(int)
report (y_test, y_pred_binary)



Epoch 1/12


229/229 [==============================] - 2s 3ms/step - loss: 4348.8203 - accuracy: 0.6463 - val_loss: 509.2113 - val_accuracy: 0.7354
Epoch 2/12
229/229 [==============================] - 1s 2ms/step - loss: 2156.7622 - accuracy: 0.7068 - val_loss: 2008.4510 - val_accuracy: 0.7419
Epoch 3/12
229/229 [==============================] - 1s 2ms/step - loss: 1985.9346 - accuracy: 0.7282 - val_loss: 669.6396 - val_accuracy: 0.7906
Epoch 4/12
229/229 [==============================] - 1s 2ms/step - loss: 1408.7511 - accuracy: 0.7463 - val_loss: 119.1032 - val_accuracy: 0.8070
Epoch 5/12
229/229 [==============================] - 1s 2ms/step - loss: 1556.4913 - accuracy: 0.7440 - val_loss: 11300.3838 - val_accuracy: 0.5839
Epoch 6/12
229/229 [==============================] - 1s 2ms/step - loss: 1867.8358 - accuracy: 0.7455 - val_loss: 263.1380 - val_accuracy: 0.7928
Epoch 7/12
229/229 [==============================] - 1s 2ms/step - loss: 1463.9934 - accuracy: 0.7610 - val_lo

C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


CNN

In [18]:
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten

In [19]:
model = Sequential()
model.add(Conv1D(64, kernel_size=3, activation='relu', input_shape=(X_train.shape[1], 1)))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation='sigmoid'))  # Adjust for multiclass

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=12, batch_size=32, validation_split=0.2)

y_pred = model.predict (X_test)
y_pred_binary = (y_pred > 0.5).astype(int)
report (y_test, y_pred_binary)


Epoch 1/12
229/229 [==============================] - 2s 6ms/step - loss: 3566.5103 - accuracy: 0.6656 - val_loss: 1640.7477 - val_accuracy: 0.7026
Epoch 2/12
229/229 [==============================] - 1s 5ms/step - loss: 2830.9956 - accuracy: 0.7236 - val_loss: 436.2484 - val_accuracy: 0.7294
Epoch 3/12
229/229 [==============================] - 1s 5ms/step - loss: 1459.8821 - accuracy: 0.7448 - val_loss: 1401.6145 - val_accuracy: 0.7928
Epoch 4/12
229/229 [==============================] - 1s 5ms/step - loss: 1062.3015 - accuracy: 0.7552 - val_loss: 1772.2515 - val_accuracy: 0.6922
Epoch 5/12
229/229 [==============================] - 1s 5ms/step - loss: 719.5474 - accuracy: 0.7677 - val_loss: 156.9949 - val_accuracy: 0.8032
Epoch 6/12
229/229 [==============================] - 1s 5ms/step - loss: 610.9213 - accuracy: 0.7616 - val_loss: 630.4815 - val_accuracy: 0.7747
Epoch 7/12
229/229 [==============================] - 1s 5ms/step - loss: 473.4649 - accuracy: 0.7792 - val_loss: 88

C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


RNN

In [20]:
from tensorflow.keras.layers import SimpleRNN

In [21]:
model = Sequential()
model.add(SimpleRNN(64, activation='relu', input_shape=(X_train.shape[1], 1)))
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation='sigmoid'))  # Adjust for multiclass

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=12, batch_size=32, validation_split=0.2)

y_pred = model.predict (X_test)
y_pred_binary = (y_pred > 0.5).astype(int)
report (y_test, y_pred_binary)

Epoch 1/12
229/229 [==============================] - 4s 11ms/step - loss: 1059.9332 - accuracy: 0.6247 - val_loss: 30.9424 - val_accuracy: 0.7091
Epoch 2/12
229/229 [==============================] - 2s 9ms/step - loss: 272.9770 - accuracy: 0.6361 - val_loss: 322.6546 - val_accuracy: 0.6873
Epoch 3/12
229/229 [==============================] - 2s 9ms/step - loss: 169.0671 - accuracy: 0.6422 - val_loss: 40.7124 - val_accuracy: 0.5216
Epoch 4/12
229/229 [==============================] - 2s 9ms/step - loss: 41.2010 - accuracy: 0.6842 - val_loss: 31.7048 - val_accuracy: 0.6610
Epoch 5/12
229/229 [==============================] - 2s 9ms/step - loss: 29.8932 - accuracy: 0.6729 - val_loss: 9.8775 - val_accuracy: 0.6665
Epoch 6/12
229/229 [==============================] - 2s 10ms/step - loss: 36.2878 - accuracy: 0.6651 - val_loss: 66.3762 - val_accuracy: 0.7294
Epoch 7/12
229/229 [==============================] - 2s 10ms/step - loss: 97.7652 - accuracy: 0.6569 - val_loss: 171.2524 - val_a

C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


LSTM

In [22]:
from tensorflow.keras.layers import LSTM

In [23]:
model = Sequential()
model.add(LSTM(64, activation='relu', input_shape=(X_train.shape[1], 1)))
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation='sigmoid'))  # Adjust for multiclass

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

y_pred = model.predict (X_test)
y_pred_binary = (y_pred > 0.5).astype(int)
report (y_test, y_pred_binary)

Epoch 1/10
229/229 [==============================] - 7s 23ms/step - loss: 885.3028 - accuracy: 0.5739 - val_loss: 788.0908 - val_accuracy: 0.5631
Epoch 2/10
229/229 [==============================] - 5s 22ms/step - loss: 884964928.0000 - accuracy: 0.5144 - val_loss: 55491296.0000 - val_accuracy: 0.5003
Epoch 3/10
229/229 [==============================] - 5s 22ms/step - loss: 32525782.0000 - accuracy: 0.5105 - val_loss: 43138.5078 - val_accuracy: 0.5079
Epoch 4/10
229/229 [==============================] - 5s 22ms/step - loss: 40723.7383 - accuracy: 0.5064 - val_loss: 39767.5156 - val_accuracy: 0.4779
Epoch 5/10
229/229 [==============================] - 5s 22ms/step - loss: 39236.9648 - accuracy: 0.5103 - val_loss: 39572.8086 - val_accuracy: 0.5118
Epoch 6/10
229/229 [==============================] - 5s 23ms/step - loss: 26441.9297 - accuracy: 0.5064 - val_loss: 11467.3770 - val_accuracy: 0.5418
Epoch 7/10
229/229 [==============================] - 5s 23ms/step - loss: 7018.1387 - a

C:\Users\arvin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
